	.align 2
DirectSoundWaveData_bw_strings_69_16::
	.incbin "sound/direct_sound_samples/bw_strings_69_16.bin"

	.align 2
DirectSoundWaveData_bw_strings_77_16::
	.incbin "sound/direct_sound_samples/bw_strings_77_16.bin"

	.align 2
DirectSoundWaveData_bw_strings_84_16::
	.incbin "sound/direct_sound_samples/bw_strings_84_16.bin"

	.align 2
DirectSoundWaveData_bw_timpani_44_16::
	.incbin "sound/direct_sound_samples/bw_timpani_44_16.bin"

	.align 2
DirectSoundWaveData_bw_trumpet_69_16::
	.incbin "sound/direct_sound_samples/bw_trumpet_69_16.bin"

	.align 2
DirectSoundWaveData_bw_trumpet_79_16::
	.incbin "sound/direct_sound_samples/bw_trumpet_79_16.bin"

	.align 2
DirectSoundWaveData_bw_trombone_72_16::
	.incbin "sound/direct_sound_samples/bw_trombone_72_16.bin"

	.align 2
DirectSoundWaveData_bw_vibraphone_60_16::
	.incbin "sound/direct_sound_samples/bw_vibraphone_60_16.bin"

	.align 2
DirectSoundWaveData_bw_vibraphone_72_16::
	.incbin "sound/direct_sound_samples/bw_vibraphone_72_16.bin"

	.align 2
DirectSoundWaveData_bw_vibraphone_84_16::
	.incbin "sound/direct_sound_samples/bw_vibraphone_84_16.bin"

	.align 2
DirectSoundWaveData_bw_marimba_60_16::
	.incbin "sound/direct_sound_samples/bw_marimba_60_16.bin"

	.align 2
DirectSoundWaveData_bw_marimba_72_16::
	.incbin "sound/direct_sound_samples/bw_marimba_72_16.bin"

	.align 2
DirectSoundWaveData_bw_piccolo_84_16::
	.incbin "sound/direct_sound_samples/bw_piccolo_84_16.bin"

	.align 2
DirectSoundWaveData_bw_acoustic_bass_36_16::
	.incbin "sound/direct_sound_samples/bw_acoustic_bass_36_16.bin"

	.align 2
DirectSoundWaveData_bw_acoustic_bass_48_16::
	.incbin "sound/direct_sound_samples/bw_acoustic_bass_48_16.bin"

	.align 2
DirectSoundWaveData_bw_reverse_cymbal_43_16::
	.incbin "sound/direct_sound_samples/bw_reverse_cymbal_43_16.bin"

	.align 2
DirectSoundWaveData_bw_steel_guitar_40_16::
	.incbin "sound/direct_sound_samples/bw_steel_guitar_40_16.bin"

	.align 2
DirectSoundWaveData_bw_steel_guitar_45_16::
	.incbin "sound/direct_sound_samples/bw_steel_guitar_45_16.bin"

	.align 2
DirectSoundWaveData_bw_steel_guitar_50_16::
	.incbin "sound/direct_sound_samples/bw_steel_guitar_50_16.bin"

	.align 2
DirectSoundWaveData_bw_steel_guitar_55_16::
	.incbin "sound/direct_sound_samples/bw_steel_guitar_55_16.bin"

	.align 2
DirectSoundWaveData_bw_steel_guitar_59_16::
	.incbin "sound/direct_sound_samples/bw_steel_guitar_59_16.bin"

	.align 2
DirectSoundWaveData_bw_steel_guitar_64_16::
	.incbin "sound/direct_sound_samples/bw_steel_guitar_64_16.bin"

	.align 2
DirectSoundWaveData_bw_fretless_bass_31_16::
	.incbin "sound/direct_sound_samples/bw_fretless_bass_31_16.bin"

	.align 2
DirectSoundWaveData_bw_fretless_bass_36_16::
	.incbin "sound/direct_sound_samples/bw_fretless_bass_36_16.bin"

	.align 2
DirectSoundWaveData_bw_fretless_bass_43_16::
	.incbin "sound/direct_sound_samples/bw_fretless_bass_43_16.bin"

	.align 2
DirectSoundWaveData_bw_fretless_bass_48_16::
	.incbin "sound/direct_sound_samples/bw_fretless_bass_48_16.bin"

	.align 2
DirectSoundWaveData_bw_brush_drum_31_16::
	.incbin "sound/direct_sound_samples/bw_brush_drum_31_16.bin"

	.align 2
DirectSoundWaveData_bw_brush_drum_36_16::
	.incbin "sound/direct_sound_samples/bw_brush_drum_36_16.bin"

	.align 2
DirectSoundWaveData_bw_brush_drum_39_16::
	.incbin "sound/direct_sound_samples/bw_brush_drum_39_16.bin"

	.align 2
DirectSoundWaveData_bw_brush_drum_41_16::
	.incbin "sound/direct_sound_samples/bw_brush_drum_41_16.bin"

	.align 2
DirectSoundWaveData_bw_brush_drum_42_16::
	.incbin "sound/direct_sound_samples/bw_brush_drum_42_16.bin"

	.align 2
DirectSoundWaveData_bw_brush_drum_46_16::
	.incbin "sound/direct_sound_samples/bw_brush_drum_46_16.bin"

	.align 2
DirectSoundWaveData_bw_brush_cymbal_49_16::
	.incbin "sound/direct_sound_samples/bw_brush_cymbal_49_16.bin"

	.align 2
DirectSoundWaveData_bw_grand_piano_48_16::
	.incbin "sound/direct_sound_samples/bw_grand_piano_48_16.bin"

	.align 2
DirectSoundWaveData_bw_grand_piano_55_16::
	.incbin "sound/direct_sound_samples/bw_grand_piano_55_16.bin"

	.align 2
DirectSoundWaveData_bw_grand_piano_60_16::
	.incbin "sound/direct_sound_samples/bw_grand_piano_60_16.bin"

	.align 2
DirectSoundWaveData_bw_grand_piano_67_16::
	.incbin "sound/direct_sound_samples/bw_grand_piano_67_16.bin"

	.align 2
DirectSoundWaveData_bw_grand_piano_72_16::
	.incbin "sound/direct_sound_samples/bw_grand_piano_72_16.bin"

	.align 2
DirectSoundWaveData_bw_grand_piano_79_16::
	.incbin "sound/direct_sound_samples/bw_grand_piano_79_16.bin"
