Goldenrod_City_MapScripts::
	.byte 0

GoldenrodCity_EventScript_SignRadio::
	msgbox GoldenrodCity_EventScript_SignRadio_Text, MSGBOX_SIGN
	end

GoldenrodCity_EventScript_SignRadio_Text:
	.string "It's a sign.$"

GoldenrodCity_EventScript_SignGameCorner::
	msgbox GoldenrodCity_EventScript_SignGameCorner_Text, MSGBOX_SIGN
	end

GoldenrodCity_EventScript_SignGameCorner_Text:
	.string "It's a sign.$"

GoldenrodCity_EventScript_SignTrain::
	msgbox GoldenrodCity_EventScript_SignTrain_Text, MSGBOX_SIGN
	end

GoldenrodCity_EventScript_SignTrain_Text:
	.string "It's a sign.$"

GoldenrodCity_EventScript_SignUnderground::
	msgbox GoldenrodCity_EventScript_SignUnderground_Text, MSGBOX_SIGN
	end

GoldenrodCity_EventScript_SignUnderground_Text:
	.string "It's a sign.$"

GoldenrodCity_EventScript_SignBike::
	msgbox GoldenrodCity_EventScript_SignBike_Text, MSGBOX_SIGN
	end

GoldenrodCity_EventScript_SignBike_Text:
	.string "A bicycle is on display.$"

GoldenrodCity_EventScript_SignGym::
	msgbox GoldenrodCity_EventScript_SignGym_Text, MSGBOX_SIGN
	end

GoldenrodCity_EventScript_SignGym_Text:
	.string "It's a sign.$"

GoldenrodCity_EventScript_SignFlower::
	msgbox GoldenrodCity_EventScript_SignFlower_Text, MSGBOX_SIGN
	end

GoldenrodCity_EventScript_SignFlower_Text:
	.string "It's a sign.$"

GoldenrodCity_EventScript_SignDept::
	msgbox GoldenrodCity_EventScript_SignDept_Text, MSGBOX_SIGN
	end

GoldenrodCity_EventScript_SignDept_Text:
	.string "It's a sign.$"

GoldenrodCity_EventScript_NameRaterSign::
	msgbox GoldenrodCity_EventScript_NameRaterSign_Text, MSGBOX_SIGN
	end

GoldenrodCity_EventScript_NameRaterSign_Text:
	.string "NAME RATER.$"
