#if OW_POKEMON_OBJECT_EVENTS

static const struct SpriteFrameImage sPicTable_PikachuShadow[] = {
    overworld_ascending_frames(gObjectEventPic_PikachuShadow, 24, 4),
};
#if P_GENDER_DIFFERENCES
static const struct SpriteFrameImage sPicTable_PikachuFShadow[] = {
    overworld_ascending_frames(gObjectEventPic_PikachuFShadow, 24, 4),
};
#endif

static const struct SpriteFrameImage sPicTable_AbsolShadow[] = {
    overworld_ascending_frames(gObjectEventPic_AbsolShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_AggronShadow[] = {
    overworld_ascending_frames(gObjectEventPic_AggronShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_AlakazamShadow[] = {
    overworld_ascending_frames(gObjectEventPic_AlakazamShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_AnnihilapeShadow[] = {
    overworld_ascending_frames(gObjectEventPic_AnnihilapeShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_AraquanidShadow[] = {
    overworld_ascending_frames(gObjectEventPic_AraquanidShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_ArcanineShadow[] = {
    overworld_ascending_frames(gObjectEventPic_ArcanineShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_ArceusShadow[] = {
    overworld_ascending_frames(gObjectEventPic_ArceusShadow, 48, 8),
};

static const struct SpriteFrameImage sPicTable_ArmarougeShadow[] = {
    overworld_ascending_frames(gObjectEventPic_ArmarougeShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_ArticunoShadow[] = {
    overworld_ascending_frames(gObjectEventPic_ArticunoShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_AurorusShadow[] = {
    overworld_ascending_frames(gObjectEventPic_AurorusShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_AzelfShadow[] = {
    overworld_ascending_frames(gObjectEventPic_AzelfShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_BaxcaliburShadow[] = {
    overworld_ascending_frames(gObjectEventPic_BaxcaliburShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_BearticShadow[] = {
    overworld_ascending_frames(gObjectEventPic_BearticShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_BeedrillShadow[] = {
    overworld_ascending_frames(gObjectEventPic_BeedrillShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_BlacephalonShadow[] = {
    overworld_ascending_frames(gObjectEventPic_BlacephalonShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_BlastoiseShadow[] = {
    overworld_ascending_frames(gObjectEventPic_BlastoiseShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_BlazikenShadow[] = {
    overworld_ascending_frames(gObjectEventPic_BlazikenShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_BlisseyShadow[] = {
    overworld_ascending_frames(gObjectEventPic_BlisseyShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_BisharpShadow[] = {
    overworld_ascending_frames(gObjectEventPic_BisharpShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_BuzzwoleShadow[] = {
    overworld_ascending_frames(gObjectEventPic_BuzzwoleShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_CalyrexShadow[] = {
    overworld_ascending_frames(gObjectEventPic_CalyrexShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_CameruptShadow[] = {
    overworld_ascending_frames(gObjectEventPic_CameruptShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_CelesteelaShadow[] = {
    overworld_ascending_frames(gObjectEventPic_CelesteelaShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_CentiskorchShadow[] = {
    overworld_ascending_frames(gObjectEventPic_CentiskorchShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_CeruledgeShadow[] = {
    overworld_ascending_frames(gObjectEventPic_CeruledgeShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_ChandelureShadow[] = {
    overworld_ascending_frames(gObjectEventPic_ChandelureShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_CharizardShadow[] = {
    overworld_ascending_frames(gObjectEventPic_CharizardShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_ChesnaughtShadow[] = {
    overworld_ascending_frames(gObjectEventPic_ChesnaughtShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_ChienPaoShadow[] = {
    overworld_ascending_frames(gObjectEventPic_ChienPaoShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_ChiYuShadow[] = {
    overworld_ascending_frames(gObjectEventPic_ChiYuShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_ClawitzerShadow[] = {
    overworld_ascending_frames(gObjectEventPic_ClawitzerShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_ClodsireShadow[] = {
    overworld_ascending_frames(gObjectEventPic_ClodsireShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_CobalionShadow[] = {
    overworld_ascending_frames(gObjectEventPic_CobalionShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_CopperajahShadow[] = {
    overworld_ascending_frames(gObjectEventPic_CopperajahShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_CorviknightShadow[] = {
    overworld_ascending_frames(gObjectEventPic_CorviknightShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_CresseliaShadow[] = {
    overworld_ascending_frames(gObjectEventPic_CresseliaShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_CrobatShadow[] = {
    overworld_ascending_frames(gObjectEventPic_CrobatShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_DarkraiShadow[] = {
    overworld_ascending_frames(gObjectEventPic_DarkraiShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_DecidueyeShadow[] = {
    overworld_ascending_frames(gObjectEventPic_DecidueyeShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_DeoxysShadow[] = {
    overworld_ascending_frames(gObjectEventPic_DeoxysShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_DelphoxShadow[] = {
    overworld_ascending_frames(gObjectEventPic_DelphoxShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_DialgaShadow[] = {
    overworld_ascending_frames(gObjectEventPic_DialgaShadow, 48, 8),
};

static const struct SpriteFrameImage sPicTable_DiancieShadow[] = {
    overworld_ascending_frames(gObjectEventPic_DiancieShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_DonphanShadow[] = {
    overworld_ascending_frames(gObjectEventPic_DonphanShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_DragalgeShadow[] = {
    overworld_ascending_frames(gObjectEventPic_DragalgeShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_DragoniteShadow[] = {
    overworld_ascending_frames(gObjectEventPic_DragoniteShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_DragapultShadow[] = {
    overworld_ascending_frames(gObjectEventPic_DragapultShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_DrampaShadow[] = {
    overworld_ascending_frames(gObjectEventPic_DrampaShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_DusknoirShadow[] = {
    overworld_ascending_frames(gObjectEventPic_DusknoirShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_EelektrossShadow[] = {
    overworld_ascending_frames(gObjectEventPic_EelektrossShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_ElectivireShadow[] = {
    overworld_ascending_frames(gObjectEventPic_ElectivireShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_EmboarShadow[] = {
    overworld_ascending_frames(gObjectEventPic_EmboarShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_EmpoleonShadow[] = {
    overworld_ascending_frames(gObjectEventPic_EmpoleonShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_EnamorusShadow[] = {
    overworld_ascending_frames(gObjectEventPic_EnamorusShadow, 48, 8),
};

static const struct SpriteFrameImage sPicTable_EnteiShadow[] = {
    overworld_ascending_frames(gObjectEventPic_EnteiShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_EternatusShadow[] = {
    overworld_ascending_frames(gObjectEventPic_EternatusShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_FalinksShadow[] = {
    overworld_ascending_frames(gObjectEventPic_FalinksShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_FeraligatrShadow[] = {
    overworld_ascending_frames(gObjectEventPic_FeraligatrShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_FlygonShadow[] = {
    overworld_ascending_frames(gObjectEventPic_FlygonShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_FlutterManeShadow[] = {
    overworld_ascending_frames(gObjectEventPic_FlutterManeShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_GalvantulaShadow[] = {
    overworld_ascending_frames(gObjectEventPic_GalvantulaShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_GarchompShadow[] = {
    overworld_ascending_frames(gObjectEventPic_GarchompShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_GenesectShadow[] = {
    overworld_ascending_frames(gObjectEventPic_GenesectShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_GholdengoShadow[] = {
    overworld_ascending_frames(gObjectEventPic_GholdengoShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_GiratinaShadow[] = {
    overworld_ascending_frames(gObjectEventPic_GiratinaShadow, 48, 8),
};

static const struct SpriteFrameImage sPicTable_GolisopodShadow[] = {
    overworld_ascending_frames(gObjectEventPic_GolisopodShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_GoodraShadow[] = {
    overworld_ascending_frames(gObjectEventPic_GoodraShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_GreatTuskShadow[] = {
    overworld_ascending_frames(gObjectEventPic_GreatTuskShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_GreninjaShadow[] = {
    overworld_ascending_frames(gObjectEventPic_GreninjaShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_GrimmsnarlShadow[] = {
    overworld_ascending_frames(gObjectEventPic_GrimmsnarlShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_GroudonShadow[] = {
    overworld_ascending_frames(gObjectEventPic_GroudonShadow, 48, 8),
};

static const struct SpriteFrameImage sPicTable_GuzzlordShadow[] = {
    overworld_ascending_frames(gObjectEventPic_GuzzlordShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_GyaradosShadow[] = {
    overworld_ascending_frames(gObjectEventPic_GyaradosShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_HattereneShadow[] = {
    overworld_ascending_frames(gObjectEventPic_HattereneShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_HeatranShadow[] = {
    overworld_ascending_frames(gObjectEventPic_HeatranShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_HoOhShadow[] = {
    overworld_ascending_frames(gObjectEventPic_HoOhShadow, 48, 8),
};

static const struct SpriteFrameImage sPicTable_HonchkrowShadow[] = {
    overworld_ascending_frames(gObjectEventPic_HonchkrowShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_HoopaShadow[] = {
    overworld_ascending_frames(gObjectEventPic_HoopaShadow, 48, 8),
};

static const struct SpriteFrameImage sPicTable_HoundoomShadow[] = {
    overworld_ascending_frames(gObjectEventPic_HoundoomShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_HydreigonShadow[] = {
    overworld_ascending_frames(gObjectEventPic_HydreigonShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_IncineroarShadow[] = {
    overworld_ascending_frames(gObjectEventPic_IncineroarShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_InfernapeShadow[] = {
    overworld_ascending_frames(gObjectEventPic_InfernapeShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_InteleonShadow[] = {
    overworld_ascending_frames(gObjectEventPic_InteleonShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_IronBundleShadow[] = {
    overworld_ascending_frames(gObjectEventPic_IronBundleShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_IronCrownShadow[] = {
    overworld_ascending_frames(gObjectEventPic_IronCrownShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_IronHandsShadow[] = {
    overworld_ascending_frames(gObjectEventPic_IronHandsShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_IronTreadsShadow[] = {
    overworld_ascending_frames(gObjectEventPic_IronTreadsShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_JirachiShadow[] = {
    overworld_ascending_frames(gObjectEventPic_JirachiShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_KartanaShadow[] = {
    overworld_ascending_frames(gObjectEventPic_KartanaShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_KeldeoShadow[] = {
    overworld_ascending_frames(gObjectEventPic_KeldeoShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_KingdraShadow[] = {
    overworld_ascending_frames(gObjectEventPic_KingdraShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_KommoOShadow[] = {
    overworld_ascending_frames(gObjectEventPic_KommoOShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_KoraidonShadow[] = {
    overworld_ascending_frames(gObjectEventPic_KoraidonShadow, 48, 8),
};

static const struct SpriteFrameImage sPicTable_KrookodileShadow[] = {
    overworld_ascending_frames(gObjectEventPic_KrookodileShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_KyogreShadow[] = {
    overworld_ascending_frames(gObjectEventPic_KyogreShadow, 48, 8),
};

static const struct SpriteFrameImage sPicTable_KyuremShadow[] = {
    overworld_ascending_frames(gObjectEventPic_KyuremShadow, 48, 8),
};

static const struct SpriteFrameImage sPicTable_LandorusShadow[] = {
    overworld_ascending_frames(gObjectEventPic_LandorusShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_LatiasShadow[] = {
    overworld_ascending_frames(gObjectEventPic_LatiasShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_LatiosShadow[] = {
    overworld_ascending_frames(gObjectEventPic_LatiosShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_LucarioShadow[] = {
    overworld_ascending_frames(gObjectEventPic_LucarioShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_LunalaShadow[] = {
    overworld_ascending_frames(gObjectEventPic_LunalaShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_MagearnaShadow[] = {
    overworld_ascending_frames(gObjectEventPic_MagearnaShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_MagnezoneShadow[] = {
    overworld_ascending_frames(gObjectEventPic_MagnezoneShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_MalamarShadow[] = {
    overworld_ascending_frames(gObjectEventPic_MalamarShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_ManaphyShadow[] = {
    overworld_ascending_frames(gObjectEventPic_ManaphyShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_ManectricShadow[] = {
    overworld_ascending_frames(gObjectEventPic_ManectricShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_MarshadowShadow[] = {
    overworld_ascending_frames(gObjectEventPic_MarshadowShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_MeganiumShadow[] = {
    overworld_ascending_frames(gObjectEventPic_MeganiumShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_MelmetalShadow[] = {
    overworld_ascending_frames(gObjectEventPic_MelmetalShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_MeloettaShadow[] = {
    overworld_ascending_frames(gObjectEventPic_MeloettaShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_MespritShadow[] = {
    overworld_ascending_frames(gObjectEventPic_MespritShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_MeowscaradaShadow[] = {
    overworld_ascending_frames(gObjectEventPic_MeowscaradaShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_MewShadow[] = {
    overworld_ascending_frames(gObjectEventPic_MewShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_MewtwoShadow[] = {
    overworld_ascending_frames(gObjectEventPic_MewtwoShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_MiloticShadow[] = {
    overworld_ascending_frames(gObjectEventPic_MiloticShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_MimikyuShadow[] = {
    overworld_ascending_frames(gObjectEventPic_MimikyuShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_MiraidonShadow[] = {
    overworld_ascending_frames(gObjectEventPic_MiraidonShadow, 48, 8),
};

static const struct SpriteFrameImage sPicTable_MoltresShadow[] = {
    overworld_ascending_frames(gObjectEventPic_MoltresShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_NaganadelShadow[] = {
    overworld_ascending_frames(gObjectEventPic_NaganadelShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_NecrozmaShadow[] = {
    overworld_ascending_frames(gObjectEventPic_NecrozmaShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_NidokingShadow[] = {
    overworld_ascending_frames(gObjectEventPic_NidokingShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_NihilegoShadow[] = {
    overworld_ascending_frames(gObjectEventPic_NihilegoShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_ObstagoonShadow[] = {
    overworld_ascending_frames(gObjectEventPic_ObstagoonShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_PalossandShadow[] = {
    overworld_ascending_frames(gObjectEventPic_PalossandShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_PalkiaShadow[] = {
    overworld_ascending_frames(gObjectEventPic_PalkiaShadow, 48, 8),
};

static const struct SpriteFrameImage sPicTable_PangoroShadow[] = {
    overworld_ascending_frames(gObjectEventPic_PangoroShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_PecharuntShadow[] = {
    overworld_ascending_frames(gObjectEventPic_PecharuntShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_PheromosaShadow[] = {
    overworld_ascending_frames(gObjectEventPic_PheromosaShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_PrimarinaShadow[] = {
    overworld_ascending_frames(gObjectEventPic_PrimarinaShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_QuaquavalShadow[] = {
    overworld_ascending_frames(gObjectEventPic_QuaquavalShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_RaikouShadow[] = {
    overworld_ascending_frames(gObjectEventPic_RaikouShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_RayquazaShadow[] = {
    overworld_ascending_frames(gObjectEventPic_RayquazaShadow, 48, 8),
};

static const struct SpriteFrameImage sPicTable_RegiceShadow[] = {
    overworld_ascending_frames(gObjectEventPic_RegiceShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_RegidragoShadow[] = {
    overworld_ascending_frames(gObjectEventPic_RegidragoShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_RegielekiShadow[] = {
    overworld_ascending_frames(gObjectEventPic_RegielekiShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_RegigigasShadow[] = {
    overworld_ascending_frames(gObjectEventPic_RegigigasShadow, 48, 8),
};

static const struct SpriteFrameImage sPicTable_RegirockShadow[] = {
    overworld_ascending_frames(gObjectEventPic_RegirockShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_RegisteelShadow[] = {
    overworld_ascending_frames(gObjectEventPic_RegisteelShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_ReuniclusShadow[] = {
    overworld_ascending_frames(gObjectEventPic_ReuniclusShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_ReshiramShadow[] = {
    overworld_ascending_frames(gObjectEventPic_ReshiramShadow, 48, 8),
};

static const struct SpriteFrameImage sPicTable_RhyperiorShadow[] = {
    overworld_ascending_frames(gObjectEventPic_RhyperiorShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_RillaboomShadow[] = {
    overworld_ascending_frames(gObjectEventPic_RillaboomShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_SalamenceShadow[] = {
    overworld_ascending_frames(gObjectEventPic_SalamenceShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_SalazzleShadow[] = {
    overworld_ascending_frames(gObjectEventPic_SalazzleShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_SamurottShadow[] = {
    overworld_ascending_frames(gObjectEventPic_SamurottShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_SceptileShadow[] = {
    overworld_ascending_frames(gObjectEventPic_SceptileShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_ScreamTailShadow[] = {
    overworld_ascending_frames(gObjectEventPic_ScreamTailShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_SerperiorShadow[] = {
    overworld_ascending_frames(gObjectEventPic_SerperiorShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_LugiaShadow[] = {
    overworld_ascending_frames(gObjectEventPic_LugiaShadow, 48, 8),
};

static const struct SpriteFrameImage sPicTable_SharpedoShadow[] = {
    overworld_ascending_frames(gObjectEventPic_SharpedoShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_SilvallyShadow[] = {
    overworld_ascending_frames(gObjectEventPic_SilvallyShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_SkarmoryShadow[] = {
    overworld_ascending_frames(gObjectEventPic_SkarmoryShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_SkeledirgeShadow[] = {
    overworld_ascending_frames(gObjectEventPic_SkeledirgeShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_SnorlaxShadow[] = {
    overworld_ascending_frames(gObjectEventPic_SnorlaxShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_SolgaleoShadow[] = {
    overworld_ascending_frames(gObjectEventPic_SolgaleoShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_StakatakaShadow[] = {
    overworld_ascending_frames(gObjectEventPic_StakatakaShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_SteelixShadow[] = {
    overworld_ascending_frames(gObjectEventPic_SteelixShadow, 48, 8),
};

static const struct SpriteFrameImage sPicTable_SuicuneShadow[] = {
    overworld_ascending_frames(gObjectEventPic_SuicuneShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_SwampertShadow[] = {
    overworld_ascending_frames(gObjectEventPic_SwampertShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_TapuBuluShadow[] = {
    overworld_ascending_frames(gObjectEventPic_TapuBuluShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_TapuFiniShadow[] = {
    overworld_ascending_frames(gObjectEventPic_TapuFiniShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_TapuKokoShadow[] = {
    overworld_ascending_frames(gObjectEventPic_TapuKokoShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_TapuLeleShadow[] = {
    overworld_ascending_frames(gObjectEventPic_TapuLeleShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_TalonflameShadow[] = {
    overworld_ascending_frames(gObjectEventPic_TalonflameShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_TerapagosShadow[] = {
    overworld_ascending_frames(gObjectEventPic_TerapagosShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_TerrakionShadow[] = {
    overworld_ascending_frames(gObjectEventPic_TerrakionShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_ThundurusShadow[] = {
    overworld_ascending_frames(gObjectEventPic_ThundurusShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_TingLuShadow[] = {
    overworld_ascending_frames(gObjectEventPic_TingLuShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_TornadusShadow[] = {
    overworld_ascending_frames(gObjectEventPic_TornadusShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_TorterraShadow[] = {
    overworld_ascending_frames(gObjectEventPic_TorterraShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_ToxapexShadow[] = {
    overworld_ascending_frames(gObjectEventPic_ToxapexShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_TyphlosionShadow[] = {
    overworld_ascending_frames(gObjectEventPic_TyphlosionShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_TyranitarShadow[] = {
    overworld_ascending_frames(gObjectEventPic_TyranitarShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_TyrantrumShadow[] = {
    overworld_ascending_frames(gObjectEventPic_TyrantrumShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_UxieShadow[] = {
    overworld_ascending_frames(gObjectEventPic_UxieShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_VenusaurShadow[] = {
    overworld_ascending_frames(gObjectEventPic_VenusaurShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_VictiniShadow[] = {
    overworld_ascending_frames(gObjectEventPic_VictiniShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_VikavoltShadow[] = {
    overworld_ascending_frames(gObjectEventPic_VikavoltShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_VirizionShadow[] = {
    overworld_ascending_frames(gObjectEventPic_VirizionShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_VolcanionShadow[] = {
    overworld_ascending_frames(gObjectEventPic_VolcanionShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_VolcaronaShadow[] = {
    overworld_ascending_frames(gObjectEventPic_VolcaronaShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_WalreinShadow[] = {
    overworld_ascending_frames(gObjectEventPic_WalreinShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_WeavileShadow[] = {
    overworld_ascending_frames(gObjectEventPic_WeavileShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_WoChienShadow[] = {
    overworld_ascending_frames(gObjectEventPic_WoChienShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_XerneasShadow[] = {
    overworld_ascending_frames(gObjectEventPic_XerneasShadow, 48, 8),
};

static const struct SpriteFrameImage sPicTable_XurkitreeShadow[] = {
    overworld_ascending_frames(gObjectEventPic_XurkitreeShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_YveltalShadow[] = {
    overworld_ascending_frames(gObjectEventPic_YveltalShadow, 48, 8),
};

static const struct SpriteFrameImage sPicTable_ZacianShadow[] = {
    overworld_ascending_frames(gObjectEventPic_ZacianShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_ZamazentaShadow[] = {
    overworld_ascending_frames(gObjectEventPic_ZamazentaShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_ZapdosShadow[] = {
    overworld_ascending_frames(gObjectEventPic_ZapdosShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_ZarudeShadow[] = {
    overworld_ascending_frames(gObjectEventPic_ZarudeShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_ZekromShadow[] = {
    overworld_ascending_frames(gObjectEventPic_ZekromShadow, 48, 8),
};

static const struct SpriteFrameImage sPicTable_ZeraoraShadow[] = {
    overworld_ascending_frames(gObjectEventPic_ZeraoraShadow, 24, 4),
};

static const struct SpriteFrameImage sPicTable_ZygardeShadow[] = {
    overworld_ascending_frames(gObjectEventPic_ZygardeShadow, 48, 8),
};

static const struct SpriteFrameImage *const sShadowOverworldPicTables[NUM_SPECIES] = {
    [SPECIES_PIKACHU] = sPicTable_PikachuShadow,
    [SPECIES_ABSOL] = sPicTable_AbsolShadow,
    [SPECIES_AGGRON] = sPicTable_AggronShadow,
    [SPECIES_ALAKAZAM] = sPicTable_AlakazamShadow,
    [SPECIES_ANNIHILAPE] = sPicTable_AnnihilapeShadow,
    [SPECIES_ARAQUANID] = sPicTable_AraquanidShadow,
    [SPECIES_ARCANINE] = sPicTable_ArcanineShadow,
    [SPECIES_ARCEUS] = sPicTable_ArceusShadow,
    [SPECIES_ARMAROUGE] = sPicTable_ArmarougeShadow,
    [SPECIES_ARTICUNO] = sPicTable_ArticunoShadow,
    [SPECIES_AURORUS] = sPicTable_AurorusShadow,
    [SPECIES_AZELF] = sPicTable_AzelfShadow,
    [SPECIES_BAXCALIBUR] = sPicTable_BaxcaliburShadow,
    [SPECIES_BEARTIC] = sPicTable_BearticShadow,
    [SPECIES_BEEDRILL] = sPicTable_BeedrillShadow,
    [SPECIES_BLACEPHALON] = sPicTable_BlacephalonShadow,
    [SPECIES_BLASTOISE] = sPicTable_BlastoiseShadow,
    [SPECIES_BLAZIKEN] = sPicTable_BlazikenShadow,
    [SPECIES_BLISSEY] = sPicTable_BlisseyShadow,
    [SPECIES_BISHARP] = sPicTable_BisharpShadow,
    [SPECIES_BUZZWOLE] = sPicTable_BuzzwoleShadow,
    [SPECIES_CALYREX] = sPicTable_CalyrexShadow,
    [SPECIES_CAMERUPT] = sPicTable_CameruptShadow,
    [SPECIES_CELESTEELA] = sPicTable_CelesteelaShadow,
    [SPECIES_CENTISKORCH] = sPicTable_CentiskorchShadow,
    [SPECIES_CERULEDGE] = sPicTable_CeruledgeShadow,
    [SPECIES_CHANDELURE] = sPicTable_ChandelureShadow,
    [SPECIES_CHARIZARD] = sPicTable_CharizardShadow,
    [SPECIES_CHESNAUGHT] = sPicTable_ChesnaughtShadow,
    [SPECIES_CHIEN_PAO] = sPicTable_ChienPaoShadow,
    [SPECIES_CHI_YU] = sPicTable_ChiYuShadow,
    [SPECIES_CLAWITZER] = sPicTable_ClawitzerShadow,
    [SPECIES_CLODSIRE] = sPicTable_ClodsireShadow,
    [SPECIES_COBALION] = sPicTable_CobalionShadow,
    [SPECIES_COPPERAJAH] = sPicTable_CopperajahShadow,
    [SPECIES_CORVIKNIGHT] = sPicTable_CorviknightShadow,
    [SPECIES_CRESSELIA] = sPicTable_CresseliaShadow,
    [SPECIES_CROBAT] = sPicTable_CrobatShadow,
    [SPECIES_DARKRAI] = sPicTable_DarkraiShadow,
    [SPECIES_DECIDUEYE] = sPicTable_DecidueyeShadow,
    [SPECIES_DEOXYS] = sPicTable_DeoxysShadow,
    [SPECIES_DELPHOX] = sPicTable_DelphoxShadow,
    [SPECIES_DIALGA] = sPicTable_DialgaShadow,
    [SPECIES_DIANCIE] = sPicTable_DiancieShadow,
    [SPECIES_DONPHAN] = sPicTable_DonphanShadow,
    [SPECIES_DRAGALGE] = sPicTable_DragalgeShadow,
    [SPECIES_DRAGONITE] = sPicTable_DragoniteShadow,
    [SPECIES_DRAGAPULT] = sPicTable_DragapultShadow,
    [SPECIES_DRAMPA] = sPicTable_DrampaShadow,
    [SPECIES_DUSKNOIR] = sPicTable_DusknoirShadow,
    [SPECIES_EELEKTROSS] = sPicTable_EelektrossShadow,
    [SPECIES_ELECTIVIRE] = sPicTable_ElectivireShadow,
    [SPECIES_EMBOAR] = sPicTable_EmboarShadow,
    [SPECIES_EMPOLEON] = sPicTable_EmpoleonShadow,
    [SPECIES_ENAMORUS] = sPicTable_EnamorusShadow,
    [SPECIES_ENTEI] = sPicTable_EnteiShadow,
    [SPECIES_ETERNATUS] = sPicTable_EternatusShadow,
    [SPECIES_FALINKS] = sPicTable_FalinksShadow,
    [SPECIES_FERALIGATR] = sPicTable_FeraligatrShadow,
    [SPECIES_FLYGON] = sPicTable_FlygonShadow,
    [SPECIES_FLUTTER_MANE] = sPicTable_FlutterManeShadow,
    [SPECIES_GALVANTULA] = sPicTable_GalvantulaShadow,
    [SPECIES_GARCHOMP] = sPicTable_GarchompShadow,
    [SPECIES_GENESECT] = sPicTable_GenesectShadow,
    [SPECIES_GHOLDENGO] = sPicTable_GholdengoShadow,
    [SPECIES_GIRATINA] = sPicTable_GiratinaShadow,
    [SPECIES_GOLISOPOD] = sPicTable_GolisopodShadow,
    [SPECIES_GOODRA] = sPicTable_GoodraShadow,
    [SPECIES_GREAT_TUSK] = sPicTable_GreatTuskShadow,
    [SPECIES_GRENINJA] = sPicTable_GreninjaShadow,
    [SPECIES_GRIMMSNARL] = sPicTable_GrimmsnarlShadow,
    [SPECIES_GROUDON] = sPicTable_GroudonShadow,
    [SPECIES_GUZZLORD] = sPicTable_GuzzlordShadow,
    [SPECIES_GYARADOS] = sPicTable_GyaradosShadow,
    [SPECIES_HATTERENE] = sPicTable_HattereneShadow,
    [SPECIES_HEATRAN] = sPicTable_HeatranShadow,
    [SPECIES_HO_OH] = sPicTable_HoOhShadow,
    [SPECIES_HONCHKROW] = sPicTable_HonchkrowShadow,
    [SPECIES_HOOPA] = sPicTable_HoopaShadow,
    [SPECIES_HOUNDOOM] = sPicTable_HoundoomShadow,
    [SPECIES_HYDREIGON] = sPicTable_HydreigonShadow,
    [SPECIES_INCINEROAR] = sPicTable_IncineroarShadow,
    [SPECIES_INFERNAPE] = sPicTable_InfernapeShadow,
    [SPECIES_INTELEON] = sPicTable_InteleonShadow,
    [SPECIES_IRON_BUNDLE] = sPicTable_IronBundleShadow,
    [SPECIES_IRON_CROWN] = sPicTable_IronCrownShadow,
    [SPECIES_IRON_HANDS] = sPicTable_IronHandsShadow,
    [SPECIES_IRON_TREADS] = sPicTable_IronTreadsShadow,
    [SPECIES_JIRACHI] = sPicTable_JirachiShadow,
    [SPECIES_KARTANA] = sPicTable_KartanaShadow,
    [SPECIES_KELDEO] = sPicTable_KeldeoShadow,
    [SPECIES_KINGDRA] = sPicTable_KingdraShadow,
    [SPECIES_KOMMO_O] = sPicTable_KommoOShadow,
    [SPECIES_KORAIDON] = sPicTable_KoraidonShadow,
    [SPECIES_KROOKODILE] = sPicTable_KrookodileShadow,
    [SPECIES_KYOGRE] = sPicTable_KyogreShadow,
    [SPECIES_KYUREM] = sPicTable_KyuremShadow,
    [SPECIES_LANDORUS] = sPicTable_LandorusShadow,
    [SPECIES_LATIAS] = sPicTable_LatiasShadow,
    [SPECIES_LATIOS] = sPicTable_LatiosShadow,
    [SPECIES_LUCARIO] = sPicTable_LucarioShadow,
    [SPECIES_LUNALA] = sPicTable_LunalaShadow,
    [SPECIES_MAGEARNA] = sPicTable_MagearnaShadow,
    [SPECIES_MAGNEZONE] = sPicTable_MagnezoneShadow,
    [SPECIES_MALAMAR] = sPicTable_MalamarShadow,
    [SPECIES_MANAPHY] = sPicTable_ManaphyShadow,
    [SPECIES_MANECTRIC] = sPicTable_ManectricShadow,
    [SPECIES_MARSHADOW] = sPicTable_MarshadowShadow,
    [SPECIES_MEGANIUM] = sPicTable_MeganiumShadow,
    [SPECIES_MELMETAL] = sPicTable_MelmetalShadow,
    [SPECIES_MELOETTA] = sPicTable_MeloettaShadow,
    [SPECIES_MESPRIT] = sPicTable_MespritShadow,
    [SPECIES_MEOWSCARADA] = sPicTable_MeowscaradaShadow,
    [SPECIES_MEW] = sPicTable_MewShadow,
    [SPECIES_MEWTWO] = sPicTable_MewtwoShadow,
    [SPECIES_MILOTIC] = sPicTable_MiloticShadow,
    [SPECIES_MIMIKYU] = sPicTable_MimikyuShadow,
    [SPECIES_MIRAIDON] = sPicTable_MiraidonShadow,
    [SPECIES_MOLTRES] = sPicTable_MoltresShadow,
    [SPECIES_NAGANADEL] = sPicTable_NaganadelShadow,
    [SPECIES_NECROZMA] = sPicTable_NecrozmaShadow,
    [SPECIES_NIDOKING] = sPicTable_NidokingShadow,
    [SPECIES_NIHILEGO] = sPicTable_NihilegoShadow,
    [SPECIES_OBSTAGOON] = sPicTable_ObstagoonShadow,
    [SPECIES_PALOSSAND] = sPicTable_PalossandShadow,
    [SPECIES_PALKIA] = sPicTable_PalkiaShadow,
    [SPECIES_PANGORO] = sPicTable_PangoroShadow,
    [SPECIES_PECHARUNT] = sPicTable_PecharuntShadow,
    [SPECIES_PHEROMOSA] = sPicTable_PheromosaShadow,
    [SPECIES_PRIMARINA] = sPicTable_PrimarinaShadow,
    [SPECIES_QUAQUAVAL] = sPicTable_QuaquavalShadow,
    [SPECIES_RAIKOU] = sPicTable_RaikouShadow,
    [SPECIES_RAYQUAZA] = sPicTable_RayquazaShadow,
    [SPECIES_REGICE] = sPicTable_RegiceShadow,
    [SPECIES_REGIDRAGO] = sPicTable_RegidragoShadow,
    [SPECIES_REGIELEKI] = sPicTable_RegielekiShadow,
    [SPECIES_REGIGIGAS] = sPicTable_RegigigasShadow,
    [SPECIES_REGIROCK] = sPicTable_RegirockShadow,
    [SPECIES_REGISTEEL] = sPicTable_RegisteelShadow,
    [SPECIES_REUNICLUS] = sPicTable_ReuniclusShadow,
    [SPECIES_RESHIRAM] = sPicTable_ReshiramShadow,
    [SPECIES_RHYPERIOR] = sPicTable_RhyperiorShadow,
    [SPECIES_RILLABOOM] = sPicTable_RillaboomShadow,
    [SPECIES_SALAMENCE] = sPicTable_SalamenceShadow,
    [SPECIES_SALAZZLE] = sPicTable_SalazzleShadow,
    [SPECIES_SAMUROTT] = sPicTable_SamurottShadow,
    [SPECIES_SCEPTILE] = sPicTable_SceptileShadow,
    [SPECIES_SCREAM_TAIL] = sPicTable_ScreamTailShadow,
    [SPECIES_SERPERIOR] = sPicTable_SerperiorShadow,
    [SPECIES_LUGIA] = sPicTable_LugiaShadow,
    [SPECIES_SHARPEDO] = sPicTable_SharpedoShadow,
    [SPECIES_SILVALLY] = sPicTable_SilvallyShadow,
    [SPECIES_SKARMORY] = sPicTable_SkarmoryShadow,
    [SPECIES_SKELEDIRGE] = sPicTable_SkeledirgeShadow,
    [SPECIES_SNORLAX] = sPicTable_SnorlaxShadow,
    [SPECIES_SOLGALEO] = sPicTable_SolgaleoShadow,
    [SPECIES_STAKATAKA] = sPicTable_StakatakaShadow,
    [SPECIES_STEELIX] = sPicTable_SteelixShadow,
    [SPECIES_SUICUNE] = sPicTable_SuicuneShadow,
    [SPECIES_SWAMPERT] = sPicTable_SwampertShadow,
    [SPECIES_TAPU_BULU] = sPicTable_TapuBuluShadow,
    [SPECIES_TAPU_FINI] = sPicTable_TapuFiniShadow,
    [SPECIES_TAPU_KOKO] = sPicTable_TapuKokoShadow,
    [SPECIES_TAPU_LELE] = sPicTable_TapuLeleShadow,
    [SPECIES_TALONFLAME] = sPicTable_TalonflameShadow,
    [SPECIES_TERAPAGOS] = sPicTable_TerapagosShadow,
    [SPECIES_TERRAKION] = sPicTable_TerrakionShadow,
    [SPECIES_THUNDURUS] = sPicTable_ThundurusShadow,
    [SPECIES_TING_LU] = sPicTable_TingLuShadow,
    [SPECIES_TORNADUS] = sPicTable_TornadusShadow,
    [SPECIES_TORTERRA] = sPicTable_TorterraShadow,
    [SPECIES_TOXAPEX] = sPicTable_ToxapexShadow,
    [SPECIES_TYPHLOSION] = sPicTable_TyphlosionShadow,
    [SPECIES_TYRANITAR] = sPicTable_TyranitarShadow,
    [SPECIES_TYRANTRUM] = sPicTable_TyrantrumShadow,
    [SPECIES_UXIE] = sPicTable_UxieShadow,
    [SPECIES_VENUSAUR] = sPicTable_VenusaurShadow,
    [SPECIES_VICTINI] = sPicTable_VictiniShadow,
    [SPECIES_VIKAVOLT] = sPicTable_VikavoltShadow,
    [SPECIES_VIRIZION] = sPicTable_VirizionShadow,
    [SPECIES_VOLCANION] = sPicTable_VolcanionShadow,
    [SPECIES_VOLCARONA] = sPicTable_VolcaronaShadow,
    [SPECIES_WALREIN] = sPicTable_WalreinShadow,
    [SPECIES_WEAVILE] = sPicTable_WeavileShadow,
    [SPECIES_WO_CHIEN] = sPicTable_WoChienShadow,
    [SPECIES_XERNEAS] = sPicTable_XerneasShadow,
    [SPECIES_XURKITREE] = sPicTable_XurkitreeShadow,
    [SPECIES_YVELTAL] = sPicTable_YveltalShadow,
    [SPECIES_ZACIAN] = sPicTable_ZacianShadow,
    [SPECIES_ZAMAZENTA] = sPicTable_ZamazentaShadow,
    [SPECIES_ZAPDOS] = sPicTable_ZapdosShadow,
    [SPECIES_ZARUDE] = sPicTable_ZarudeShadow,
    [SPECIES_ZEKROM] = sPicTable_ZekromShadow,
    [SPECIES_ZERAORA] = sPicTable_ZeraoraShadow,
    [SPECIES_ZYGARDE] = sPicTable_ZygardeShadow,
};

#if P_GENDER_DIFFERENCES
static const struct SpriteFrameImage *const sShadowOverworldPicTables_Female[NUM_SPECIES] = {
    [SPECIES_PIKACHU] = sPicTable_PikachuFShadow,
};
#endif

#if OW_POKEMON_OBJECT_EVENTS && OW_PKMN_OBJECTS_SHARE_PALETTES == FALSE
static const u16 *const sShadowOverworldPalettes[NUM_SPECIES] = {
    [SPECIES_PIKACHU] = gMonPalette_PikachuShadow,
    [SPECIES_ABSOL] = gMonPalette_AbsolShadow,
    [SPECIES_AGGRON] = gMonPalette_AggronShadow,
    [SPECIES_ALAKAZAM] = gMonPalette_AlakazamShadow,
    [SPECIES_ANNIHILAPE] = gMonPalette_AnnihilapeShadow,
    [SPECIES_ARAQUANID] = gMonPalette_AraquanidShadow,
    [SPECIES_ARCANINE] = gMonPalette_ArcanineShadow,
    [SPECIES_ARCEUS] = gMonPalette_ArceusShadow,
    [SPECIES_ARMAROUGE] = gMonPalette_ArmarougeShadow,
    [SPECIES_ARTICUNO] = gMonPalette_ArticunoShadow,
    [SPECIES_AURORUS] = gMonPalette_AurorusShadow,
    [SPECIES_AZELF] = gMonPalette_AzelfShadow,
    [SPECIES_BAXCALIBUR] = gMonPalette_BaxcaliburShadow,
    [SPECIES_BEARTIC] = gMonPalette_BearticShadow,
    [SPECIES_BEEDRILL] = gMonPalette_BeedrillShadow,
    [SPECIES_BLACEPHALON] = gMonPalette_BlacephalonShadow,
    [SPECIES_BLASTOISE] = gMonPalette_BlastoiseShadow,
    [SPECIES_BLAZIKEN] = gMonPalette_BlazikenShadow,
    [SPECIES_BLISSEY] = gMonPalette_BlisseyShadow,
    [SPECIES_BISHARP] = gMonPalette_BisharpShadow,
    [SPECIES_BUZZWOLE] = gMonPalette_BuzzwoleShadow,
    [SPECIES_CALYREX] = gMonPalette_CalyrexShadow,
    [SPECIES_CAMERUPT] = gMonPalette_CameruptShadow,
    [SPECIES_CELESTEELA] = gMonPalette_CelesteelaShadow,
    [SPECIES_CENTISKORCH] = gMonPalette_CentiskorchShadow,
    [SPECIES_CERULEDGE] = gMonPalette_CeruledgeShadow,
    [SPECIES_CHANDELURE] = gMonPalette_ChandelureShadow,
    [SPECIES_CHARIZARD] = gMonPalette_CharizardShadow,
    [SPECIES_CHESNAUGHT] = gMonPalette_ChesnaughtShadow,
    [SPECIES_CHIEN_PAO] = gMonPalette_ChienPaoShadow,
    [SPECIES_CHI_YU] = gMonPalette_ChiYuShadow,
    [SPECIES_CLAWITZER] = gMonPalette_ClawitzerShadow,
    [SPECIES_CLODSIRE] = gMonPalette_ClodsireShadow,
    [SPECIES_COBALION] = gMonPalette_CobalionShadow,
    [SPECIES_COPPERAJAH] = gMonPalette_CopperajahShadow,
    [SPECIES_CORVIKNIGHT] = gMonPalette_CorviknightShadow,
    [SPECIES_CRESSELIA] = gMonPalette_CresseliaShadow,
    [SPECIES_CROBAT] = gMonPalette_CrobatShadow,
    [SPECIES_DARKRAI] = gMonPalette_DarkraiShadow,
    [SPECIES_DECIDUEYE] = gMonPalette_DecidueyeShadow,
    [SPECIES_DEOXYS] = gMonPalette_DeoxysShadow,
    [SPECIES_DELPHOX] = gMonPalette_DelphoxShadow,
    [SPECIES_DIALGA] = gMonPalette_DialgaShadow,
    [SPECIES_DIANCIE] = gMonPalette_DiancieShadow,
    [SPECIES_DONPHAN] = gMonPalette_DonphanShadow,
    [SPECIES_DRAGALGE] = gMonPalette_DragalgeShadow,
    [SPECIES_DRAGONITE] = gMonPalette_DragoniteShadow,
    [SPECIES_DRAGAPULT] = gMonPalette_DragapultShadow,
    [SPECIES_DRAMPA] = gMonPalette_DrampaShadow,
    [SPECIES_DUSKNOIR] = gMonPalette_DusknoirShadow,
    [SPECIES_EELEKTROSS] = gMonPalette_EelektrossShadow,
    [SPECIES_ELECTIVIRE] = gMonPalette_ElectivireShadow,
    [SPECIES_EMBOAR] = gMonPalette_EmboarShadow,
    [SPECIES_EMPOLEON] = gMonPalette_EmpoleonShadow,
    [SPECIES_ENAMORUS] = gMonPalette_EnamorusShadow,
    [SPECIES_ENTEI] = gMonPalette_EnteiShadow,
    [SPECIES_ETERNATUS] = gMonPalette_EternatusShadow,
    [SPECIES_FALINKS] = gMonPalette_FalinksShadow,
    [SPECIES_FERALIGATR] = gMonPalette_FeraligatrShadow,
    [SPECIES_FLYGON] = gMonPalette_FlygonShadow,
    [SPECIES_FLUTTER_MANE] = gMonPalette_FlutterManeShadow,
    [SPECIES_GALVANTULA] = gMonPalette_GalvantulaShadow,
    [SPECIES_GARCHOMP] = gMonPalette_GarchompShadow,
    [SPECIES_GENESECT] = gMonPalette_GenesectShadow,
    [SPECIES_GHOLDENGO] = gMonPalette_GholdengoShadow,
    [SPECIES_GIRATINA] = gMonPalette_GiratinaShadow,
    [SPECIES_GOLISOPOD] = gMonPalette_GolisopodShadow,
    [SPECIES_GOODRA] = gMonPalette_GoodraShadow,
    [SPECIES_GREAT_TUSK] = gMonPalette_GreatTuskShadow,
    [SPECIES_GRENINJA] = gMonPalette_GreninjaShadow,
    [SPECIES_GRIMMSNARL] = gMonPalette_GrimmsnarlShadow,
    [SPECIES_GROUDON] = gMonPalette_GroudonShadow,
    [SPECIES_GUZZLORD] = gMonPalette_GuzzlordShadow,
    [SPECIES_GYARADOS] = gMonPalette_GyaradosShadow,
    [SPECIES_HATTERENE] = gMonPalette_HattereneShadow,
    [SPECIES_HEATRAN] = gMonPalette_HeatranShadow,
    [SPECIES_HO_OH] = gMonPalette_HoOhShadow,
    [SPECIES_HONCHKROW] = gMonPalette_HonchkrowShadow,
    [SPECIES_HOUNDOOM] = gMonPalette_HoundoomShadow,
    [SPECIES_HYDREIGON] = gMonPalette_HydreigonShadow,
    [SPECIES_INCINEROAR] = gMonPalette_IncineroarShadow,
    [SPECIES_INFERNAPE] = gMonPalette_InfernapeShadow,
    [SPECIES_INTELEON] = gMonPalette_InteleonShadow,
    [SPECIES_IRON_BUNDLE] = gMonPalette_IronBundleShadow,
    [SPECIES_IRON_CROWN] = gMonPalette_IronCrownShadow,
    [SPECIES_IRON_HANDS] = gMonPalette_IronHandsShadow,
    [SPECIES_IRON_TREADS] = gMonPalette_IronTreadsShadow,
    [SPECIES_JIRACHI] = gMonPalette_JirachiShadow,
    [SPECIES_KARTANA] = gMonPalette_KartanaShadow,
    [SPECIES_KELDEO] = gMonPalette_KeldeoShadow,
    [SPECIES_KINGDRA] = gMonPalette_KingdraShadow,
    [SPECIES_KOMMO_O] = gMonPalette_KommoOShadow,
    [SPECIES_KORAIDON] = gMonPalette_KoraidonShadow,
    [SPECIES_KROOKODILE] = gMonPalette_KrookodileShadow,
    [SPECIES_KYOGRE] = gMonPalette_KyogreShadow,
    [SPECIES_KYUREM] = gMonPalette_KyuremShadow,
    [SPECIES_LANDORUS] = gMonPalette_LandorusShadow,
    [SPECIES_LATIAS] = gMonPalette_LatiasShadow,
    [SPECIES_LATIOS] = gMonPalette_LatiosShadow,
    [SPECIES_LUCARIO] = gMonPalette_LucarioShadow,
    [SPECIES_LUNALA] = gMonPalette_LunalaShadow,
    [SPECIES_MAGEARNA] = gMonPalette_MagearnaShadow,
    [SPECIES_MAGNEZONE] = gMonPalette_MagnezoneShadow,
    [SPECIES_MALAMAR] = gMonPalette_MalamarShadow,
    [SPECIES_MANAPHY] = gMonPalette_ManaphyShadow,
    [SPECIES_MANECTRIC] = gMonPalette_ManectricShadow,
    [SPECIES_MARSHADOW] = gMonPalette_MarshadowShadow,
    [SPECIES_MEGANIUM] = gMonPalette_MeganiumShadow,
    [SPECIES_MELMETAL] = gMonPalette_MelmetalShadow,
    [SPECIES_MELOETTA] = gMonPalette_MeloettaShadow,
    [SPECIES_MESPRIT] = gMonPalette_MespritShadow,
    [SPECIES_MEOWSCARADA] = gMonPalette_MeowscaradaShadow,
    [SPECIES_MEW] = gMonPalette_MewShadow,
    [SPECIES_MEWTWO] = gMonPalette_MewtwoShadow,
    [SPECIES_MILOTIC] = gMonPalette_MiloticShadow,
    [SPECIES_MIMIKYU] = gMonPalette_MimikyuShadow,
    [SPECIES_MIRAIDON] = gMonPalette_MiraidonShadow,
    [SPECIES_MOLTRES] = gMonPalette_MoltresShadow,
    [SPECIES_NAGANADEL] = gMonPalette_NaganadelShadow,
    [SPECIES_NECROZMA] = gMonPalette_NecrozmaShadow,
    [SPECIES_NIDOKING] = gMonPalette_NidokingShadow,
    [SPECIES_NIHILEGO] = gMonPalette_NihilegoShadow,
    [SPECIES_OBSTAGOON] = gMonPalette_ObstagoonShadow,
    [SPECIES_PALOSSAND] = gMonPalette_PalossandShadow,
    [SPECIES_PALKIA] = gMonPalette_PalkiaShadow,
    [SPECIES_PANGORO] = gMonPalette_PangoroShadow,
    [SPECIES_PECHARUNT] = gMonPalette_PecharuntShadow,
    [SPECIES_PHEROMOSA] = gMonPalette_PheromosaShadow,
    [SPECIES_PRIMARINA] = gMonPalette_PrimarinaShadow,
    [SPECIES_QUAQUAVAL] = gMonPalette_QuaquavalShadow,
    [SPECIES_RAIKOU] = gMonPalette_RaikouShadow,
    [SPECIES_RAYQUAZA] = gMonPalette_RayquazaShadow,
    [SPECIES_REGICE] = gMonPalette_RegiceShadow,
    [SPECIES_REGIDRAGO] = gMonPalette_RegidragoShadow,
    [SPECIES_REGIELEKI] = gMonPalette_RegielekiShadow,
    [SPECIES_REGIGIGAS] = gMonPalette_RegigigasShadow,
    [SPECIES_REGIROCK] = gMonPalette_RegirockShadow,
    [SPECIES_REGISTEEL] = gMonPalette_RegisteelShadow,
    [SPECIES_REUNICLUS] = gMonPalette_ReuniclusShadow,
    [SPECIES_RESHIRAM] = gMonPalette_ReshiramShadow,
    [SPECIES_RHYPERIOR] = gMonPalette_RhyperiorShadow,
    [SPECIES_RILLABOOM] = gMonPalette_RillaboomShadow,
    [SPECIES_SALAMENCE] = gMonPalette_SalamenceShadow,
    [SPECIES_SALAZZLE] = gMonPalette_SalazzleShadow,
    [SPECIES_SAMUROTT] = gMonPalette_SamurottShadow,
    [SPECIES_SCEPTILE] = gMonPalette_SceptileShadow,
    [SPECIES_SCREAM_TAIL] = gMonPalette_ScreamTailShadow,
    [SPECIES_SERPERIOR] = gMonPalette_SerperiorShadow,
    [SPECIES_LUGIA] = gMonPalette_LugiaShadow,
    [SPECIES_SHARPEDO] = gMonPalette_SharpedoShadow,
    [SPECIES_SILVALLY] = gMonPalette_SilvallyShadow,
    [SPECIES_SKARMORY] = gMonPalette_SkarmoryShadow,
    [SPECIES_SKELEDIRGE] = gMonPalette_SkeledirgeShadow,
    [SPECIES_SNORLAX] = gMonPalette_SnorlaxShadow,
    [SPECIES_SOLGALEO] = gMonPalette_SolgaleoShadow,
    [SPECIES_STAKATAKA] = gMonPalette_StakatakaShadow,
    [SPECIES_STEELIX] = gMonPalette_SteelixShadow,
    [SPECIES_SUICUNE] = gMonPalette_SuicuneShadow,
    [SPECIES_SWAMPERT] = gMonPalette_SwampertShadow,
    [SPECIES_TAPU_BULU] = gMonPalette_TapuBuluShadow,
    [SPECIES_TAPU_FINI] = gMonPalette_TapuFiniShadow,
    [SPECIES_TAPU_KOKO] = gMonPalette_TapuKokoShadow,
    [SPECIES_TAPU_LELE] = gMonPalette_TapuLeleShadow,
    [SPECIES_TALONFLAME] = gMonPalette_TalonflameShadow,
    [SPECIES_TERAPAGOS] = gMonPalette_TerapagosShadow,
    [SPECIES_TERRAKION] = gMonPalette_TerrakionShadow,
    [SPECIES_THUNDURUS] = gMonPalette_ThundurusShadow,
    [SPECIES_TING_LU] = gMonPalette_TingLuShadow,
    [SPECIES_TORNADUS] = gMonPalette_TornadusShadow,
    [SPECIES_TORTERRA] = gMonPalette_TorterraShadow,
    [SPECIES_TOXAPEX] = gMonPalette_ToxapexShadow,
    [SPECIES_TYPHLOSION] = gMonPalette_TyphlosionShadow,
    [SPECIES_TYRANITAR] = gMonPalette_TyranitarShadow,
    [SPECIES_TYRANTRUM] = gMonPalette_TyrantrumShadow,
    [SPECIES_UXIE] = gMonPalette_UxieShadow,
    [SPECIES_VENUSAUR] = gMonPalette_VenusaurShadow,
    [SPECIES_VICTINI] = gMonPalette_VictiniShadow,
    [SPECIES_VIKAVOLT] = gMonPalette_VikavoltShadow,
    [SPECIES_VIRIZION] = gMonPalette_VirizionShadow,
    [SPECIES_VOLCANION] = gMonPalette_VolcanionShadow,
    [SPECIES_VOLCARONA] = gMonPalette_VolcaronaShadow,
    [SPECIES_WALREIN] = gMonPalette_WalreinShadow,
    [SPECIES_WEAVILE] = gMonPalette_WeavileShadow,
    [SPECIES_WO_CHIEN] = gMonPalette_WoChienShadow,
    [SPECIES_XERNEAS] = gMonPalette_XerneasShadow,
    [SPECIES_XURKITREE] = gMonPalette_XurkitreeShadow,
    [SPECIES_YVELTAL] = gMonPalette_YveltalShadow,
    [SPECIES_ZACIAN] = gMonPalette_ZacianShadow,
    [SPECIES_ZAMAZENTA] = gMonPalette_ZamazentaShadow,
    [SPECIES_ZAPDOS] = gMonPalette_ZapdosShadow,
    [SPECIES_ZARUDE] = gMonPalette_ZarudeShadow,
    [SPECIES_ZEKROM] = gMonPalette_ZekromShadow,
    [SPECIES_ZERAORA] = gMonPalette_ZeraoraShadow,
    [SPECIES_ZYGARDE] = gMonPalette_ZygardeShadow,
};
#endif
#endif
