const u32 gMonFrontPic_PikachuShadow[] = INCBIN_U32("graphics/pokemon/pikachu/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_PikachuShadow[] = INCBIN_U32("graphics/pokemon/pikachu/shadow/back.4bpp.lz");
const u16 gMonPalette_PikachuShadow[] = INCBIN_U16("graphics/pokemon/pikachu/shadow/shadow.gbapal");
const u8 gMonIcon_PikachuShadow[] = INCBIN_U8("graphics/pokemon/pikachu/shadow/icon.4bpp");
#if P_GENDER_DIFFERENCES && P_CUSTOM_GENDER_DIFF_ICONS
const u8 gMonIcon_PikachuFShadow[] = INCBIN_U8("graphics/pokemon/pikachu/shadow/iconf.4bpp");
#endif
#if P_GENDER_DIFFERENCES
const u32 gMonFrontPic_PikachuFShadow[] = INCBIN_U32("graphics/pokemon/pikachu/shadow/anim_frontf.4bpp.lz");
const u32 gMonBackPic_PikachuFShadow[] = INCBIN_U32("graphics/pokemon/pikachu/shadow/backf.4bpp.lz");
#endif
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_PikachuShadow[] = INCBIN_COMP("graphics/pokemon/pikachu/shadow/overworld.4bpp");
#if P_GENDER_DIFFERENCES
const u32 gObjectEventPic_PikachuFShadow[] = INCBIN_COMP("graphics/pokemon/pikachu/shadow/overworldf.4bpp");
#endif
#endif

const u32 gMonFrontPic_AbsolShadow[] = INCBIN_U32("graphics/pokemon/absol/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_AbsolShadow[] = INCBIN_U32("graphics/pokemon/absol/shadow/back.4bpp.lz");
const u16 gMonPalette_AbsolShadow[] = INCBIN_U16("graphics/pokemon/absol/shadow/absol_shadow.pal");
const u8 gMonIcon_AbsolShadow[] = INCBIN_U8("graphics/pokemon/absol/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_AbsolShadow[] = INCBIN_COMP("graphics/pokemon/absol/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_AggronShadow[] = INCBIN_U32("graphics/pokemon/aggron/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_AggronShadow[] = INCBIN_U32("graphics/pokemon/aggron/shadow/back.4bpp.lz");
const u16 gMonPalette_AggronShadow[] = INCBIN_U16("graphics/pokemon/aggron/shadow/aggron_shadow.pal");
const u8 gMonIcon_AggronShadow[] = INCBIN_U8("graphics/pokemon/aggron/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_AggronShadow[] = INCBIN_COMP("graphics/pokemon/aggron/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_AlakazamShadow[] = INCBIN_U32("graphics/pokemon/alakazam/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_AlakazamShadow[] = INCBIN_U32("graphics/pokemon/alakazam/shadow/back.4bpp.lz");
const u16 gMonPalette_AlakazamShadow[] = INCBIN_U16("graphics/pokemon/alakazam/shadow/alakazam_shadow.pal");
const u8 gMonIcon_AlakazamShadow[] = INCBIN_U8("graphics/pokemon/alakazam/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_AlakazamShadow[] = INCBIN_COMP("graphics/pokemon/alakazam/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_AnnihilapeShadow[] = INCBIN_U32("graphics/pokemon/annihilape/shadow/front.4bpp.lz");
const u32 gMonBackPic_AnnihilapeShadow[] = INCBIN_U32("graphics/pokemon/annihilape/shadow/back.4bpp.lz");
const u16 gMonPalette_AnnihilapeShadow[] = INCBIN_U16("graphics/pokemon/annihilape/shadow/annihilape_shadow.pal");
const u8 gMonIcon_AnnihilapeShadow[] = INCBIN_U8("graphics/pokemon/annihilape/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_AnnihilapeShadow[] = INCBIN_COMP("graphics/pokemon/annihilape/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_AraquanidShadow[] = INCBIN_U32("graphics/pokemon/araquanid/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_AraquanidShadow[] = INCBIN_U32("graphics/pokemon/araquanid/shadow/back.4bpp.lz");
const u16 gMonPalette_AraquanidShadow[] = INCBIN_U16("graphics/pokemon/araquanid/shadow/araquanid_shadow.pal");
const u8 gMonIcon_AraquanidShadow[] = INCBIN_U8("graphics/pokemon/araquanid/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_AraquanidShadow[] = INCBIN_COMP("graphics/pokemon/araquanid/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_ArcanineShadow[] = INCBIN_U32("graphics/pokemon/arcanine/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_ArcanineShadow[] = INCBIN_U32("graphics/pokemon/arcanine/shadow/back.4bpp.lz");
const u16 gMonPalette_ArcanineShadow[] = INCBIN_U16("graphics/pokemon/arcanine/shadow/arcanine_shadow.pal");
const u8 gMonIcon_ArcanineShadow[] = INCBIN_U8("graphics/pokemon/arcanine/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_ArcanineShadow[] = INCBIN_COMP("graphics/pokemon/arcanine/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_ArceusShadow[] = INCBIN_U32("graphics/pokemon/arceus/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_ArceusShadow[] = INCBIN_U32("graphics/pokemon/arceus/shadow/back.4bpp.lz");
const u16 gMonPalette_ArceusShadow[] = INCBIN_U16("graphics/pokemon/arceus/shadow/arceus_shadow.pal");
const u8 gMonIcon_ArceusShadow[] = INCBIN_U8("graphics/pokemon/arceus/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_ArceusShadow[] = INCBIN_COMP("graphics/pokemon/arceus/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_ArmarougeShadow[] = INCBIN_U32("graphics/pokemon/armarouge/shadow/front.4bpp.lz");
const u32 gMonBackPic_ArmarougeShadow[] = INCBIN_U32("graphics/pokemon/armarouge/shadow/back.4bpp.lz");
const u16 gMonPalette_ArmarougeShadow[] = INCBIN_U16("graphics/pokemon/armarouge/shadow/armarouge_shadow.pal");
const u8 gMonIcon_ArmarougeShadow[] = INCBIN_U8("graphics/pokemon/armarouge/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_ArmarougeShadow[] = INCBIN_COMP("graphics/pokemon/armarouge/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_ArticunoShadow[] = INCBIN_U32("graphics/pokemon/articuno/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_ArticunoShadow[] = INCBIN_U32("graphics/pokemon/articuno/shadow/back.4bpp.lz");
const u16 gMonPalette_ArticunoShadow[] = INCBIN_U16("graphics/pokemon/articuno/shadow/articuno_shadow.pal");
const u8 gMonIcon_ArticunoShadow[] = INCBIN_U8("graphics/pokemon/articuno/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_ArticunoShadow[] = INCBIN_COMP("graphics/pokemon/articuno/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_AurorusShadow[] = INCBIN_U32("graphics/pokemon/aurorus/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_AurorusShadow[] = INCBIN_U32("graphics/pokemon/aurorus/shadow/back.4bpp.lz");
const u16 gMonPalette_AurorusShadow[] = INCBIN_U16("graphics/pokemon/aurorus/shadow/aurorus_shadow.pal");
const u8 gMonIcon_AurorusShadow[] = INCBIN_U8("graphics/pokemon/aurorus/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_AurorusShadow[] = INCBIN_COMP("graphics/pokemon/aurorus/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_AzelfShadow[] = INCBIN_U32("graphics/pokemon/azelf/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_AzelfShadow[] = INCBIN_U32("graphics/pokemon/azelf/shadow/back.4bpp.lz");
const u16 gMonPalette_AzelfShadow[] = INCBIN_U16("graphics/pokemon/azelf/shadow/azelf_shadow.pal");
const u8 gMonIcon_AzelfShadow[] = INCBIN_U8("graphics/pokemon/azelf/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_AzelfShadow[] = INCBIN_COMP("graphics/pokemon/azelf/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_BaxcaliburShadow[] = INCBIN_U32("graphics/pokemon/baxcalibur/shadow/front.4bpp.lz");
const u32 gMonBackPic_BaxcaliburShadow[] = INCBIN_U32("graphics/pokemon/baxcalibur/shadow/back.4bpp.lz");
const u16 gMonPalette_BaxcaliburShadow[] = INCBIN_U16("graphics/pokemon/baxcalibur/shadow/baxcalibur_shadow.pal");
const u8 gMonIcon_BaxcaliburShadow[] = INCBIN_U8("graphics/pokemon/baxcalibur/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_BaxcaliburShadow[] = INCBIN_COMP("graphics/pokemon/baxcalibur/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_BearticShadow[] = INCBIN_U32("graphics/pokemon/beartic/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_BearticShadow[] = INCBIN_U32("graphics/pokemon/beartic/shadow/back.4bpp.lz");
const u16 gMonPalette_BearticShadow[] = INCBIN_U16("graphics/pokemon/beartic/shadow/beartic_shadow.pal");
const u8 gMonIcon_BearticShadow[] = INCBIN_U8("graphics/pokemon/beartic/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_BearticShadow[] = INCBIN_COMP("graphics/pokemon/beartic/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_BeedrillShadow[] = INCBIN_U32("graphics/pokemon/beedrill/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_BeedrillShadow[] = INCBIN_U32("graphics/pokemon/beedrill/shadow/back.4bpp.lz");
const u16 gMonPalette_BeedrillShadow[] = INCBIN_U16("graphics/pokemon/beedrill/shadow/beedrill_shadow.pal");
const u8 gMonIcon_BeedrillShadow[] = INCBIN_U8("graphics/pokemon/beedrill/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_BeedrillShadow[] = INCBIN_COMP("graphics/pokemon/beedrill/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_BlacephalonShadow[] = INCBIN_U32("graphics/pokemon/blacephalon/shadow/front.4bpp.lz");
const u32 gMonBackPic_BlacephalonShadow[] = INCBIN_U32("graphics/pokemon/blacephalon/shadow/back.4bpp.lz");
const u16 gMonPalette_BlacephalonShadow[] = INCBIN_U16("graphics/pokemon/blacephalon/shadow/blacephalon_shadow.pal");
const u8 gMonIcon_BlacephalonShadow[] = INCBIN_U8("graphics/pokemon/blacephalon/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_BlacephalonShadow[] = INCBIN_COMP("graphics/pokemon/blacephalon/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_BlastoiseShadow[] = INCBIN_U32("graphics/pokemon/blastoise/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_BlastoiseShadow[] = INCBIN_U32("graphics/pokemon/blastoise/shadow/back.4bpp.lz");
const u16 gMonPalette_BlastoiseShadow[] = INCBIN_U16("graphics/pokemon/blastoise/shadow/blastoise_shadow.pal");
const u8 gMonIcon_BlastoiseShadow[] = INCBIN_U8("graphics/pokemon/blastoise/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_BlastoiseShadow[] = INCBIN_COMP("graphics/pokemon/blastoise/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_BlazikenShadow[] = INCBIN_U32("graphics/pokemon/blaziken/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_BlazikenShadow[] = INCBIN_U32("graphics/pokemon/blaziken/shadow/back.4bpp.lz");
const u16 gMonPalette_BlazikenShadow[] = INCBIN_U16("graphics/pokemon/blaziken/shadow/blaziken_shadow.pal");
const u8 gMonIcon_BlazikenShadow[] = INCBIN_U8("graphics/pokemon/blaziken/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_BlazikenShadow[] = INCBIN_COMP("graphics/pokemon/blaziken/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_BlisseyShadow[] = INCBIN_U32("graphics/pokemon/blissey/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_BlisseyShadow[] = INCBIN_U32("graphics/pokemon/blissey/shadow/back.4bpp.lz");
const u16 gMonPalette_BlisseyShadow[] = INCBIN_U16("graphics/pokemon/blissey/shadow/blissey_shadow.pal");
const u8 gMonIcon_BlisseyShadow[] = INCBIN_U8("graphics/pokemon/blissey/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_BlisseyShadow[] = INCBIN_COMP("graphics/pokemon/blissey/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_BisharpShadow[] = INCBIN_U32("graphics/pokemon/bisharp/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_BisharpShadow[] = INCBIN_U32("graphics/pokemon/bisharp/shadow/back.4bpp.lz");
const u16 gMonPalette_BisharpShadow[] = INCBIN_U16("graphics/pokemon/bisharp/shadow/bisharp_shadow.pal");
const u8 gMonIcon_BisharpShadow[] = INCBIN_U8("graphics/pokemon/bisharp/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_BisharpShadow[] = INCBIN_COMP("graphics/pokemon/bisharp/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_BuzzwoleShadow[] = INCBIN_U32("graphics/pokemon/buzzwole/shadow/front.4bpp.lz");
const u32 gMonBackPic_BuzzwoleShadow[] = INCBIN_U32("graphics/pokemon/buzzwole/shadow/back.4bpp.lz");
const u16 gMonPalette_BuzzwoleShadow[] = INCBIN_U16("graphics/pokemon/buzzwole/shadow/buzzwole_shadow.pal");
const u8 gMonIcon_BuzzwoleShadow[] = INCBIN_U8("graphics/pokemon/buzzwole/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_BuzzwoleShadow[] = INCBIN_COMP("graphics/pokemon/buzzwole/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_CameruptShadow[] = INCBIN_U32("graphics/pokemon/camerupt/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_CameruptShadow[] = INCBIN_U32("graphics/pokemon/camerupt/shadow/back.4bpp.lz");
const u16 gMonPalette_CameruptShadow[] = INCBIN_U16("graphics/pokemon/camerupt/shadow/camerupt_shadow.pal");
const u8 gMonIcon_CameruptShadow[] = INCBIN_U8("graphics/pokemon/camerupt/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_CameruptShadow[] = INCBIN_COMP("graphics/pokemon/camerupt/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_CelesteelaShadow[] = INCBIN_U32("graphics/pokemon/celesteela/shadow/front.4bpp.lz");
const u32 gMonBackPic_CelesteelaShadow[] = INCBIN_U32("graphics/pokemon/celesteela/shadow/back.4bpp.lz");
const u16 gMonPalette_CelesteelaShadow[] = INCBIN_U16("graphics/pokemon/celesteela/shadow/celesteela_shadow.pal");
const u8 gMonIcon_CelesteelaShadow[] = INCBIN_U8("graphics/pokemon/celesteela/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_CelesteelaShadow[] = INCBIN_COMP("graphics/pokemon/celesteela/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_CentiskorchShadow[] = INCBIN_U32("graphics/pokemon/centiskorch/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_CentiskorchShadow[] = INCBIN_U32("graphics/pokemon/centiskorch/shadow/back.4bpp.lz");
const u16 gMonPalette_CentiskorchShadow[] = INCBIN_U16("graphics/pokemon/centiskorch/shadow/centiskorch_shadow.pal");
const u8 gMonIcon_CentiskorchShadow[] = INCBIN_U8("graphics/pokemon/centiskorch/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_CentiskorchShadow[] = INCBIN_COMP("graphics/pokemon/centiskorch/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_CeruledgeShadow[] = INCBIN_U32("graphics/pokemon/ceruledge/shadow/front.4bpp.lz");
const u32 gMonBackPic_CeruledgeShadow[] = INCBIN_U32("graphics/pokemon/ceruledge/shadow/back.4bpp.lz");
const u16 gMonPalette_CeruledgeShadow[] = INCBIN_U16("graphics/pokemon/ceruledge/shadow/ceruledge_shadow.pal");
const u8 gMonIcon_CeruledgeShadow[] = INCBIN_U8("graphics/pokemon/ceruledge/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_CeruledgeShadow[] = INCBIN_COMP("graphics/pokemon/ceruledge/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_ChandelureShadow[] = INCBIN_U32("graphics/pokemon/chandelure/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_ChandelureShadow[] = INCBIN_U32("graphics/pokemon/chandelure/shadow/back.4bpp.lz");
const u16 gMonPalette_ChandelureShadow[] = INCBIN_U16("graphics/pokemon/chandelure/shadow/chandelure_shadow.pal");
const u8 gMonIcon_ChandelureShadow[] = INCBIN_U8("graphics/pokemon/chandelure/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_ChandelureShadow[] = INCBIN_COMP("graphics/pokemon/chandelure/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_CharizardShadow[] = INCBIN_U32("graphics/pokemon/charizard/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_CharizardShadow[] = INCBIN_U32("graphics/pokemon/charizard/shadow/back.4bpp.lz");
const u16 gMonPalette_CharizardShadow[] = INCBIN_U16("graphics/pokemon/charizard/shadow/charizard_shadow.pal");
const u8 gMonIcon_CharizardShadow[] = INCBIN_U8("graphics/pokemon/charizard/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_CharizardShadow[] = INCBIN_COMP("graphics/pokemon/charizard/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_ChesnaughtShadow[] = INCBIN_U32("graphics/pokemon/chesnaught/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_ChesnaughtShadow[] = INCBIN_U32("graphics/pokemon/chesnaught/shadow/back.4bpp.lz");
const u16 gMonPalette_ChesnaughtShadow[] = INCBIN_U16("graphics/pokemon/chesnaught/shadow/chesnaught_shadow.pal");
const u8 gMonIcon_ChesnaughtShadow[] = INCBIN_U8("graphics/pokemon/chesnaught/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_ChesnaughtShadow[] = INCBIN_COMP("graphics/pokemon/chesnaught/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_ChienPaoShadow[] = INCBIN_U32("graphics/pokemon/chien_pao/shadow/front.4bpp.lz");
const u32 gMonBackPic_ChienPaoShadow[] = INCBIN_U32("graphics/pokemon/chien_pao/shadow/back.4bpp.lz");
const u16 gMonPalette_ChienPaoShadow[] = INCBIN_U16("graphics/pokemon/chien_pao/shadow/chien_pao_shadow.pal");
const u8 gMonIcon_ChienPaoShadow[] = INCBIN_U8("graphics/pokemon/chien_pao/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_ChienPaoShadow[] = INCBIN_COMP("graphics/pokemon/chien_pao/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_ChiYuShadow[] = INCBIN_U32("graphics/pokemon/chi_yu/shadow/front.4bpp.lz");
const u32 gMonBackPic_ChiYuShadow[] = INCBIN_U32("graphics/pokemon/chi_yu/shadow/back.4bpp.lz");
const u16 gMonPalette_ChiYuShadow[] = INCBIN_U16("graphics/pokemon/chi_yu/shadow/chi_yu_shadow.pal");
const u8 gMonIcon_ChiYuShadow[] = INCBIN_U8("graphics/pokemon/chi_yu/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_ChiYuShadow[] = INCBIN_COMP("graphics/pokemon/chi_yu/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_ClawitzerShadow[] = INCBIN_U32("graphics/pokemon/clawitzer/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_ClawitzerShadow[] = INCBIN_U32("graphics/pokemon/clawitzer/shadow/back.4bpp.lz");
const u16 gMonPalette_ClawitzerShadow[] = INCBIN_U16("graphics/pokemon/clawitzer/shadow/clawitzer_shadow.pal");
const u8 gMonIcon_ClawitzerShadow[] = INCBIN_U8("graphics/pokemon/clawitzer/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_ClawitzerShadow[] = INCBIN_COMP("graphics/pokemon/clawitzer/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_ClodsireShadow[] = INCBIN_U32("graphics/pokemon/clodsire/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_ClodsireShadow[] = INCBIN_U32("graphics/pokemon/clodsire/shadow/back.4bpp.lz");
const u16 gMonPalette_ClodsireShadow[] = INCBIN_U16("graphics/pokemon/clodsire/shadow/clodsire_shadow.pal");
const u8 gMonIcon_ClodsireShadow[] = INCBIN_U8("graphics/pokemon/clodsire/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_ClodsireShadow[] = INCBIN_COMP("graphics/pokemon/clodsire/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_CobalionShadow[] = INCBIN_U32("graphics/pokemon/cobalion/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_CobalionShadow[] = INCBIN_U32("graphics/pokemon/cobalion/shadow/back.4bpp.lz");
const u16 gMonPalette_CobalionShadow[] = INCBIN_U16("graphics/pokemon/cobalion/shadow/cobalion_shadow.pal");
const u8 gMonIcon_CobalionShadow[] = INCBIN_U8("graphics/pokemon/cobalion/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_CobalionShadow[] = INCBIN_COMP("graphics/pokemon/cobalion/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_CopperajahShadow[] = INCBIN_U32("graphics/pokemon/copperajah/shadow/front.4bpp.lz");
const u32 gMonBackPic_CopperajahShadow[] = INCBIN_U32("graphics/pokemon/copperajah/shadow/back.4bpp.lz");
const u16 gMonPalette_CopperajahShadow[] = INCBIN_U16("graphics/pokemon/copperajah/shadow/copperajah_shadow.pal");
const u8 gMonIcon_CopperajahShadow[] = INCBIN_U8("graphics/pokemon/copperajah/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_CopperajahShadow[] = INCBIN_COMP("graphics/pokemon/copperajah/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_CorviknightShadow[] = INCBIN_U32("graphics/pokemon/corviknight/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_CorviknightShadow[] = INCBIN_U32("graphics/pokemon/corviknight/shadow/back.4bpp.lz");
const u16 gMonPalette_CorviknightShadow[] = INCBIN_U16("graphics/pokemon/corviknight/shadow/corviknight_shadow.pal");
const u8 gMonIcon_CorviknightShadow[] = INCBIN_U8("graphics/pokemon/corviknight/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_CorviknightShadow[] = INCBIN_COMP("graphics/pokemon/corviknight/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_CresseliaShadow[] = INCBIN_U32("graphics/pokemon/cresselia/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_CresseliaShadow[] = INCBIN_U32("graphics/pokemon/cresselia/shadow/back.4bpp.lz");
const u16 gMonPalette_CresseliaShadow[] = INCBIN_U16("graphics/pokemon/cresselia/shadow/cresselia_shadow.pal");
const u8 gMonIcon_CresseliaShadow[] = INCBIN_U8("graphics/pokemon/cresselia/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_CresseliaShadow[] = INCBIN_COMP("graphics/pokemon/cresselia/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_CrobatShadow[] = INCBIN_U32("graphics/pokemon/crobat/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_CrobatShadow[] = INCBIN_U32("graphics/pokemon/crobat/shadow/back.4bpp.lz");
const u16 gMonPalette_CrobatShadow[] = INCBIN_U16("graphics/pokemon/crobat/shadow/crobat_shadow.pal");
const u8 gMonIcon_CrobatShadow[] = INCBIN_U8("graphics/pokemon/crobat/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_CrobatShadow[] = INCBIN_COMP("graphics/pokemon/crobat/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_DarkraiShadow[] = INCBIN_U32("graphics/pokemon/darkrai/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_DarkraiShadow[] = INCBIN_U32("graphics/pokemon/darkrai/shadow/back.4bpp.lz");
const u16 gMonPalette_DarkraiShadow[] = INCBIN_U16("graphics/pokemon/darkrai/shadow/darkrai_shadow.pal");
const u8 gMonIcon_DarkraiShadow[] = INCBIN_U8("graphics/pokemon/darkrai/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_DarkraiShadow[] = INCBIN_COMP("graphics/pokemon/darkrai/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_DecidueyeShadow[] = INCBIN_U32("graphics/pokemon/decidueye/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_DecidueyeShadow[] = INCBIN_U32("graphics/pokemon/decidueye/shadow/back.4bpp.lz");
const u16 gMonPalette_DecidueyeShadow[] = INCBIN_U16("graphics/pokemon/decidueye/shadow/decidueye_shadow.pal");
const u8 gMonIcon_DecidueyeShadow[] = INCBIN_U8("graphics/pokemon/decidueye/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_DecidueyeShadow[] = INCBIN_COMP("graphics/pokemon/decidueye/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_DeoxysShadow[] = INCBIN_U32("graphics/pokemon/deoxys/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_DeoxysShadow[] = INCBIN_U32("graphics/pokemon/deoxys/shadow/back.4bpp.lz");
const u16 gMonPalette_DeoxysShadow[] = INCBIN_U16("graphics/pokemon/deoxys/shadow/deoxys_shadow.pal");
const u8 gMonIcon_DeoxysShadow[] = INCBIN_U8("graphics/pokemon/deoxys/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_DeoxysShadow[] = INCBIN_COMP("graphics/pokemon/deoxys/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_DelphoxShadow[] = INCBIN_U32("graphics/pokemon/delphox/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_DelphoxShadow[] = INCBIN_U32("graphics/pokemon/delphox/shadow/back.4bpp.lz");
const u16 gMonPalette_DelphoxShadow[] = INCBIN_U16("graphics/pokemon/delphox/shadow/delphox_shadow.pal");
const u8 gMonIcon_DelphoxShadow[] = INCBIN_U8("graphics/pokemon/delphox/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_DelphoxShadow[] = INCBIN_COMP("graphics/pokemon/delphox/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_DialgaShadow[] = INCBIN_U32("graphics/pokemon/dialga/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_DialgaShadow[] = INCBIN_U32("graphics/pokemon/dialga/shadow/back.4bpp.lz");
const u16 gMonPalette_DialgaShadow[] = INCBIN_U16("graphics/pokemon/dialga/shadow/dialga_shadow.pal");
const u8 gMonIcon_DialgaShadow[] = INCBIN_U8("graphics/pokemon/dialga/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_DialgaShadow[] = INCBIN_COMP("graphics/pokemon/dialga/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_DiancieShadow[] = INCBIN_U32("graphics/pokemon/diancie/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_DiancieShadow[] = INCBIN_U32("graphics/pokemon/diancie/shadow/back.4bpp.lz");
const u16 gMonPalette_DiancieShadow[] = INCBIN_U16("graphics/pokemon/diancie/shadow/diancie_shadow.pal");
const u8 gMonIcon_DiancieShadow[] = INCBIN_U8("graphics/pokemon/diancie/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_DiancieShadow[] = INCBIN_COMP("graphics/pokemon/diancie/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_DonphanShadow[] = INCBIN_U32("graphics/pokemon/donphan/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_DonphanShadow[] = INCBIN_U32("graphics/pokemon/donphan/shadow/back.4bpp.lz");
const u16 gMonPalette_DonphanShadow[] = INCBIN_U16("graphics/pokemon/donphan/shadow/donphan_shadow.pal");
const u8 gMonIcon_DonphanShadow[] = INCBIN_U8("graphics/pokemon/donphan/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_DonphanShadow[] = INCBIN_COMP("graphics/pokemon/donphan/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_DragalgeShadow[] = INCBIN_U32("graphics/pokemon/dragalge/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_DragalgeShadow[] = INCBIN_U32("graphics/pokemon/dragalge/shadow/back.4bpp.lz");
const u16 gMonPalette_DragalgeShadow[] = INCBIN_U16("graphics/pokemon/dragalge/shadow/dragalge_shadow.pal");
const u8 gMonIcon_DragalgeShadow[] = INCBIN_U8("graphics/pokemon/dragalge/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_DragalgeShadow[] = INCBIN_COMP("graphics/pokemon/dragalge/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_DragoniteShadow[] = INCBIN_U32("graphics/pokemon/dragonite/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_DragoniteShadow[] = INCBIN_U32("graphics/pokemon/dragonite/shadow/back.4bpp.lz");
const u16 gMonPalette_DragoniteShadow[] = INCBIN_U16("graphics/pokemon/dragonite/shadow/dragonite_shadow.pal");
const u8 gMonIcon_DragoniteShadow[] = INCBIN_U8("graphics/pokemon/dragonite/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_DragoniteShadow[] = INCBIN_COMP("graphics/pokemon/dragonite/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_DragapultShadow[] = INCBIN_U32("graphics/pokemon/dragapult/shadow/front.4bpp.lz");
const u32 gMonBackPic_DragapultShadow[] = INCBIN_U32("graphics/pokemon/dragapult/shadow/back.4bpp.lz");
const u16 gMonPalette_DragapultShadow[] = INCBIN_U16("graphics/pokemon/dragapult/shadow/dragapult_shadow.pal");
const u8 gMonIcon_DragapultShadow[] = INCBIN_U8("graphics/pokemon/dragapult/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_DragapultShadow[] = INCBIN_COMP("graphics/pokemon/dragapult/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_DrampaShadow[] = INCBIN_U32("graphics/pokemon/drampa/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_DrampaShadow[] = INCBIN_U32("graphics/pokemon/drampa/shadow/back.4bpp.lz");
const u16 gMonPalette_DrampaShadow[] = INCBIN_U16("graphics/pokemon/drampa/shadow/drampa_shadow.pal");
const u8 gMonIcon_DrampaShadow[] = INCBIN_U8("graphics/pokemon/drampa/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_DrampaShadow[] = INCBIN_COMP("graphics/pokemon/drampa/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_DusknoirShadow[] = INCBIN_U32("graphics/pokemon/dusknoir/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_DusknoirShadow[] = INCBIN_U32("graphics/pokemon/dusknoir/shadow/back.4bpp.lz");
const u16 gMonPalette_DusknoirShadow[] = INCBIN_U16("graphics/pokemon/dusknoir/shadow/dusknoir_shadow.pal");
const u8 gMonIcon_DusknoirShadow[] = INCBIN_U8("graphics/pokemon/dusknoir/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_DusknoirShadow[] = INCBIN_COMP("graphics/pokemon/dusknoir/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_EelektrossShadow[] = INCBIN_U32("graphics/pokemon/eelektross/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_EelektrossShadow[] = INCBIN_U32("graphics/pokemon/eelektross/shadow/back.4bpp.lz");
const u16 gMonPalette_EelektrossShadow[] = INCBIN_U16("graphics/pokemon/eelektross/shadow/eelektross_shadow.pal");
const u8 gMonIcon_EelektrossShadow[] = INCBIN_U8("graphics/pokemon/eelektross/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_EelektrossShadow[] = INCBIN_COMP("graphics/pokemon/eelektross/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_ElectivireShadow[] = INCBIN_U32("graphics/pokemon/electivire/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_ElectivireShadow[] = INCBIN_U32("graphics/pokemon/electivire/shadow/back.4bpp.lz");
const u16 gMonPalette_ElectivireShadow[] = INCBIN_U16("graphics/pokemon/electivire/shadow/electivire_shadow.pal");
const u8 gMonIcon_ElectivireShadow[] = INCBIN_U8("graphics/pokemon/electivire/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_ElectivireShadow[] = INCBIN_COMP("graphics/pokemon/electivire/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_EmboarShadow[] = INCBIN_U32("graphics/pokemon/emboar/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_EmboarShadow[] = INCBIN_U32("graphics/pokemon/emboar/shadow/back.4bpp.lz");
const u16 gMonPalette_EmboarShadow[] = INCBIN_U16("graphics/pokemon/emboar/shadow/emboar_shadow.pal");
const u8 gMonIcon_EmboarShadow[] = INCBIN_U8("graphics/pokemon/emboar/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_EmboarShadow[] = INCBIN_COMP("graphics/pokemon/emboar/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_EmpoleonShadow[] = INCBIN_U32("graphics/pokemon/empoleon/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_EmpoleonShadow[] = INCBIN_U32("graphics/pokemon/empoleon/shadow/back.4bpp.lz");
const u16 gMonPalette_EmpoleonShadow[] = INCBIN_U16("graphics/pokemon/empoleon/shadow/empoleon_shadow.pal");
const u8 gMonIcon_EmpoleonShadow[] = INCBIN_U8("graphics/pokemon/empoleon/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_EmpoleonShadow[] = INCBIN_COMP("graphics/pokemon/empoleon/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_EnamorusShadow[] = INCBIN_U32("graphics/pokemon/enamorus/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_EnamorusShadow[] = INCBIN_U32("graphics/pokemon/enamorus/shadow/back.4bpp.lz");
const u16 gMonPalette_EnamorusShadow[] = INCBIN_U16("graphics/pokemon/enamorus/shadow/enamorus_shadow.pal");
const u8 gMonIcon_EnamorusShadow[] = INCBIN_U8("graphics/pokemon/enamorus/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_EnamorusShadow[] = INCBIN_COMP("graphics/pokemon/enamorus/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_EnteiShadow[] = INCBIN_U32("graphics/pokemon/entei/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_EnteiShadow[] = INCBIN_U32("graphics/pokemon/entei/shadow/back.4bpp.lz");
const u16 gMonPalette_EnteiShadow[] = INCBIN_U16("graphics/pokemon/entei/shadow/entei_shadow.pal");
const u8 gMonIcon_EnteiShadow[] = INCBIN_U8("graphics/pokemon/entei/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_EnteiShadow[] = INCBIN_COMP("graphics/pokemon/entei/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_EternatusShadow[] = INCBIN_U32("graphics/pokemon/eternatus/shadow/front.4bpp.lz");
const u32 gMonBackPic_EternatusShadow[] = INCBIN_U32("graphics/pokemon/eternatus/shadow/back.4bpp.lz");
const u16 gMonPalette_EternatusShadow[] = INCBIN_U16("graphics/pokemon/eternatus/shadow/eternatus_shadow.pal");
const u8 gMonIcon_EternatusShadow[] = INCBIN_U8("graphics/pokemon/eternatus/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_EternatusShadow[] = INCBIN_COMP("graphics/pokemon/eternatus/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_FalinksShadow[] = INCBIN_U32("graphics/pokemon/falinks/shadow/front.4bpp.lz");
const u32 gMonBackPic_FalinksShadow[] = INCBIN_U32("graphics/pokemon/falinks/shadow/back.4bpp.lz");
const u16 gMonPalette_FalinksShadow[] = INCBIN_U16("graphics/pokemon/falinks/shadow/falinks_shadow.pal");
const u8 gMonIcon_FalinksShadow[] = INCBIN_U8("graphics/pokemon/falinks/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_FalinksShadow[] = INCBIN_COMP("graphics/pokemon/falinks/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_FeraligatrShadow[] = INCBIN_U32("graphics/pokemon/feraligatr/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_FeraligatrShadow[] = INCBIN_U32("graphics/pokemon/feraligatr/shadow/back.4bpp.lz");
const u16 gMonPalette_FeraligatrShadow[] = INCBIN_U16("graphics/pokemon/feraligatr/shadow/feraligatr_shadow.pal");
const u8 gMonIcon_FeraligatrShadow[] = INCBIN_U8("graphics/pokemon/feraligatr/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_FeraligatrShadow[] = INCBIN_COMP("graphics/pokemon/feraligatr/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_FlygonShadow[] = INCBIN_U32("graphics/pokemon/flygon/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_FlygonShadow[] = INCBIN_U32("graphics/pokemon/flygon/shadow/back.4bpp.lz");
const u16 gMonPalette_FlygonShadow[] = INCBIN_U16("graphics/pokemon/flygon/shadow/flygon_shadow.pal");
const u8 gMonIcon_FlygonShadow[] = INCBIN_U8("graphics/pokemon/flygon/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_FlygonShadow[] = INCBIN_COMP("graphics/pokemon/flygon/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_FlutterManeShadow[] = INCBIN_U32("graphics/pokemon/flutter_mane/shadow/front.4bpp.lz");
const u32 gMonBackPic_FlutterManeShadow[] = INCBIN_U32("graphics/pokemon/flutter_mane/shadow/back.4bpp.lz");
const u16 gMonPalette_FlutterManeShadow[] = INCBIN_U16("graphics/pokemon/flutter_mane/shadow/flutter_mane_shadow.pal");
const u8 gMonIcon_FlutterManeShadow[] = INCBIN_U8("graphics/pokemon/flutter_mane/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_FlutterManeShadow[] = INCBIN_COMP("graphics/pokemon/flutter_mane/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_GalvantulaShadow[] = INCBIN_U32("graphics/pokemon/galvantula/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_GalvantulaShadow[] = INCBIN_U32("graphics/pokemon/galvantula/shadow/back.4bpp.lz");
const u16 gMonPalette_GalvantulaShadow[] = INCBIN_U16("graphics/pokemon/galvantula/shadow/galvantula_shadow.pal");
const u8 gMonIcon_GalvantulaShadow[] = INCBIN_U8("graphics/pokemon/galvantula/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_GalvantulaShadow[] = INCBIN_COMP("graphics/pokemon/galvantula/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_GarchompShadow[] = INCBIN_U32("graphics/pokemon/garchomp/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_GarchompShadow[] = INCBIN_U32("graphics/pokemon/garchomp/shadow/back.4bpp.lz");
const u16 gMonPalette_GarchompShadow[] = INCBIN_U16("graphics/pokemon/garchomp/shadow/garchomp_shadow.pal");
const u8 gMonIcon_GarchompShadow[] = INCBIN_U8("graphics/pokemon/garchomp/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_GarchompShadow[] = INCBIN_COMP("graphics/pokemon/garchomp/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_GenesectShadow[] = INCBIN_U32("graphics/pokemon/genesect/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_GenesectShadow[] = INCBIN_U32("graphics/pokemon/genesect/shadow/back.4bpp.lz");
const u16 gMonPalette_GenesectShadow[] = INCBIN_U16("graphics/pokemon/genesect/shadow/genesect_shadow.pal");
const u8 gMonIcon_GenesectShadow[] = INCBIN_U8("graphics/pokemon/genesect/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_GenesectShadow[] = INCBIN_COMP("graphics/pokemon/genesect/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_GholdengoShadow[] = INCBIN_U32("graphics/pokemon/gholdengo/shadow/front.4bpp.lz");
const u32 gMonBackPic_GholdengoShadow[] = INCBIN_U32("graphics/pokemon/gholdengo/shadow/back.4bpp.lz");
const u16 gMonPalette_GholdengoShadow[] = INCBIN_U16("graphics/pokemon/gholdengo/shadow/gholdengo_shadow.pal");
const u8 gMonIcon_GholdengoShadow[] = INCBIN_U8("graphics/pokemon/gholdengo/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_GholdengoShadow[] = INCBIN_COMP("graphics/pokemon/gholdengo/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_GiratinaShadow[] = INCBIN_U32("graphics/pokemon/giratina/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_GiratinaShadow[] = INCBIN_U32("graphics/pokemon/giratina/shadow/back.4bpp.lz");
const u16 gMonPalette_GiratinaShadow[] = INCBIN_U16("graphics/pokemon/giratina/shadow/giratina_shadow.pal");
const u8 gMonIcon_GiratinaShadow[] = INCBIN_U8("graphics/pokemon/giratina/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_GiratinaShadow[] = INCBIN_COMP("graphics/pokemon/giratina/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_GolisopodShadow[] = INCBIN_U32("graphics/pokemon/golisopod/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_GolisopodShadow[] = INCBIN_U32("graphics/pokemon/golisopod/shadow/back.4bpp.lz");
const u16 gMonPalette_GolisopodShadow[] = INCBIN_U16("graphics/pokemon/golisopod/shadow/golisopod_shadow.pal");
const u8 gMonIcon_GolisopodShadow[] = INCBIN_U8("graphics/pokemon/golisopod/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_GolisopodShadow[] = INCBIN_COMP("graphics/pokemon/golisopod/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_GoodraShadow[] = INCBIN_U32("graphics/pokemon/goodra/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_GoodraShadow[] = INCBIN_U32("graphics/pokemon/goodra/shadow/back.4bpp.lz");
const u16 gMonPalette_GoodraShadow[] = INCBIN_U16("graphics/pokemon/goodra/shadow/goodra_shadow.pal");
const u8 gMonIcon_GoodraShadow[] = INCBIN_U8("graphics/pokemon/goodra/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_GoodraShadow[] = INCBIN_COMP("graphics/pokemon/goodra/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_GreatTuskShadow[] = INCBIN_U32("graphics/pokemon/great_tusk/shadow/front.4bpp.lz");
const u32 gMonBackPic_GreatTuskShadow[] = INCBIN_U32("graphics/pokemon/great_tusk/shadow/back.4bpp.lz");
const u16 gMonPalette_GreatTuskShadow[] = INCBIN_U16("graphics/pokemon/great_tusk/shadow/great_tusk_shadow.pal");
const u8 gMonIcon_GreatTuskShadow[] = INCBIN_U8("graphics/pokemon/great_tusk/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_GreatTuskShadow[] = INCBIN_COMP("graphics/pokemon/great_tusk/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_GreninjaShadow[] = INCBIN_U32("graphics/pokemon/greninja/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_GreninjaShadow[] = INCBIN_U32("graphics/pokemon/greninja/shadow/back.4bpp.lz");
const u16 gMonPalette_GreninjaShadow[] = INCBIN_U16("graphics/pokemon/greninja/shadow/greninja_shadow.pal");
const u8 gMonIcon_GreninjaShadow[] = INCBIN_U8("graphics/pokemon/greninja/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_GreninjaShadow[] = INCBIN_COMP("graphics/pokemon/greninja/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_GrimmsnarlShadow[] = INCBIN_U32("graphics/pokemon/grimmsnarl/shadow/front.4bpp.lz");
const u32 gMonBackPic_GrimmsnarlShadow[] = INCBIN_U32("graphics/pokemon/grimmsnarl/shadow/back.4bpp.lz");
const u16 gMonPalette_GrimmsnarlShadow[] = INCBIN_U16("graphics/pokemon/grimmsnarl/shadow/grimmsnarl_shadow.pal");
const u8 gMonIcon_GrimmsnarlShadow[] = INCBIN_U8("graphics/pokemon/grimmsnarl/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_GrimmsnarlShadow[] = INCBIN_COMP("graphics/pokemon/grimmsnarl/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_GroudonShadow[] = INCBIN_U32("graphics/pokemon/groudon/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_GroudonShadow[] = INCBIN_U32("graphics/pokemon/groudon/shadow/back.4bpp.lz");
const u16 gMonPalette_GroudonShadow[] = INCBIN_U16("graphics/pokemon/groudon/shadow/groudon_shadow.pal");
const u8 gMonIcon_GroudonShadow[] = INCBIN_U8("graphics/pokemon/groudon/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_GroudonShadow[] = INCBIN_COMP("graphics/pokemon/groudon/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_GuzzlordShadow[] = INCBIN_U32("graphics/pokemon/guzzlord/shadow/front.4bpp.lz");
const u32 gMonBackPic_GuzzlordShadow[] = INCBIN_U32("graphics/pokemon/guzzlord/shadow/back.4bpp.lz");
const u16 gMonPalette_GuzzlordShadow[] = INCBIN_U16("graphics/pokemon/guzzlord/shadow/guzzlord_shadow.pal");
const u8 gMonIcon_GuzzlordShadow[] = INCBIN_U8("graphics/pokemon/guzzlord/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_GuzzlordShadow[] = INCBIN_COMP("graphics/pokemon/guzzlord/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_GyaradosShadow[] = INCBIN_U32("graphics/pokemon/gyarados/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_GyaradosShadow[] = INCBIN_U32("graphics/pokemon/gyarados/shadow/back.4bpp.lz");
const u16 gMonPalette_GyaradosShadow[] = INCBIN_U16("graphics/pokemon/gyarados/shadow/gyarados_shadow.pal");
const u8 gMonIcon_GyaradosShadow[] = INCBIN_U8("graphics/pokemon/gyarados/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_GyaradosShadow[] = INCBIN_COMP("graphics/pokemon/gyarados/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_HattereneShadow[] = INCBIN_U32("graphics/pokemon/hatterene/shadow/front.4bpp.lz");
const u32 gMonBackPic_HattereneShadow[] = INCBIN_U32("graphics/pokemon/hatterene/shadow/back.4bpp.lz");
const u16 gMonPalette_HattereneShadow[] = INCBIN_U16("graphics/pokemon/hatterene/shadow/hatterene_shadow.pal");
const u8 gMonIcon_HattereneShadow[] = INCBIN_U8("graphics/pokemon/hatterene/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_HattereneShadow[] = INCBIN_COMP("graphics/pokemon/hatterene/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_HeatranShadow[] = INCBIN_U32("graphics/pokemon/heatran/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_HeatranShadow[] = INCBIN_U32("graphics/pokemon/heatran/shadow/back.4bpp.lz");
const u16 gMonPalette_HeatranShadow[] = INCBIN_U16("graphics/pokemon/heatran/shadow/heatran_shadow.pal");
const u8 gMonIcon_HeatranShadow[] = INCBIN_U8("graphics/pokemon/heatran/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_HeatranShadow[] = INCBIN_COMP("graphics/pokemon/heatran/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_HoOhShadow[] = INCBIN_U32("graphics/pokemon/ho_oh/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_HoOhShadow[] = INCBIN_U32("graphics/pokemon/ho_oh/shadow/back.4bpp.lz");
const u16 gMonPalette_HoOhShadow[] = INCBIN_U16("graphics/pokemon/ho_oh/shadow/ho_oh_shadow.pal");
const u8 gMonIcon_HoOhShadow[] = INCBIN_U8("graphics/pokemon/ho_oh/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_HoOhShadow[] = INCBIN_COMP("graphics/pokemon/ho_oh/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_HonchkrowShadow[] = INCBIN_U32("graphics/pokemon/honchkrow/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_HonchkrowShadow[] = INCBIN_U32("graphics/pokemon/honchkrow/shadow/back.4bpp.lz");
const u16 gMonPalette_HonchkrowShadow[] = INCBIN_U16("graphics/pokemon/honchkrow/shadow/honchkrow_shadow.pal");
const u8 gMonIcon_HonchkrowShadow[] = INCBIN_U8("graphics/pokemon/honchkrow/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_HonchkrowShadow[] = INCBIN_COMP("graphics/pokemon/honchkrow/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_HoopaShadow[] = INCBIN_U32("graphics/pokemon/hoopa/unbound/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_HoopaShadow[] = INCBIN_U32("graphics/pokemon/hoopa/unbound/shadow/back.4bpp.lz");
const u8 gMonIcon_HoopaShadow[] = INCBIN_U8("graphics/pokemon/hoopa/unbound/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_HoopaShadow[] = INCBIN_COMP("graphics/pokemon/hoopa/unbound/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_HoundoomShadow[] = INCBIN_U32("graphics/pokemon/houndoom/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_HoundoomShadow[] = INCBIN_U32("graphics/pokemon/houndoom/shadow/back.4bpp.lz");
const u16 gMonPalette_HoundoomShadow[] = INCBIN_U16("graphics/pokemon/houndoom/shadow/houndoom_shadow.pal");
const u8 gMonIcon_HoundoomShadow[] = INCBIN_U8("graphics/pokemon/houndoom/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_HoundoomShadow[] = INCBIN_COMP("graphics/pokemon/houndoom/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_HydreigonShadow[] = INCBIN_U32("graphics/pokemon/hydreigon/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_HydreigonShadow[] = INCBIN_U32("graphics/pokemon/hydreigon/shadow/back.4bpp.lz");
const u16 gMonPalette_HydreigonShadow[] = INCBIN_U16("graphics/pokemon/hydreigon/shadow/hydreigon_shadow.pal");
const u8 gMonIcon_HydreigonShadow[] = INCBIN_U8("graphics/pokemon/hydreigon/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_HydreigonShadow[] = INCBIN_COMP("graphics/pokemon/hydreigon/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_IncineroarShadow[] = INCBIN_U32("graphics/pokemon/incineroar/shadow/front.4bpp.lz");
const u32 gMonBackPic_IncineroarShadow[] = INCBIN_U32("graphics/pokemon/incineroar/shadow/back.4bpp.lz");
const u16 gMonPalette_IncineroarShadow[] = INCBIN_U16("graphics/pokemon/incineroar/shadow/incineroar_shadow.pal");
const u8 gMonIcon_IncineroarShadow[] = INCBIN_U8("graphics/pokemon/incineroar/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_IncineroarShadow[] = INCBIN_COMP("graphics/pokemon/incineroar/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_InfernapeShadow[] = INCBIN_U32("graphics/pokemon/infernape/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_InfernapeShadow[] = INCBIN_U32("graphics/pokemon/infernape/shadow/back.4bpp.lz");
const u16 gMonPalette_InfernapeShadow[] = INCBIN_U16("graphics/pokemon/infernape/shadow/infernape_shadow.pal");
const u8 gMonIcon_InfernapeShadow[] = INCBIN_U8("graphics/pokemon/infernape/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_InfernapeShadow[] = INCBIN_COMP("graphics/pokemon/infernape/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_InteleonShadow[] = INCBIN_U32("graphics/pokemon/inteleon/shadow/front.4bpp.lz");
const u32 gMonBackPic_InteleonShadow[] = INCBIN_U32("graphics/pokemon/inteleon/shadow/back.4bpp.lz");
const u16 gMonPalette_InteleonShadow[] = INCBIN_U16("graphics/pokemon/inteleon/shadow/inteleon_shadow.pal");
const u8 gMonIcon_InteleonShadow[] = INCBIN_U8("graphics/pokemon/inteleon/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_InteleonShadow[] = INCBIN_COMP("graphics/pokemon/inteleon/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_IronBundleShadow[] = INCBIN_U32("graphics/pokemon/iron_bundle/shadow/front.4bpp.lz");
const u32 gMonBackPic_IronBundleShadow[] = INCBIN_U32("graphics/pokemon/iron_bundle/shadow/back.4bpp.lz");
const u16 gMonPalette_IronBundleShadow[] = INCBIN_U16("graphics/pokemon/iron_bundle/shadow/iron_bundle_shadow.pal");
const u8 gMonIcon_IronBundleShadow[] = INCBIN_U8("graphics/pokemon/iron_bundle/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_IronBundleShadow[] = INCBIN_COMP("graphics/pokemon/iron_bundle/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_IronCrownShadow[] = INCBIN_U32("graphics/pokemon/iron_crown/shadow/front.4bpp.lz");
const u32 gMonBackPic_IronCrownShadow[] = INCBIN_U32("graphics/pokemon/iron_crown/shadow/back.4bpp.lz");
const u16 gMonPalette_IronCrownShadow[] = INCBIN_U16("graphics/pokemon/iron_crown/shadow/iron_crown_shadow.pal");
const u8 gMonIcon_IronCrownShadow[] = INCBIN_U8("graphics/pokemon/iron_crown/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_IronCrownShadow[] = INCBIN_COMP("graphics/pokemon/iron_crown/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_IronHandsShadow[] = INCBIN_U32("graphics/pokemon/iron_hands/shadow/front.4bpp.lz");
const u32 gMonBackPic_IronHandsShadow[] = INCBIN_U32("graphics/pokemon/iron_hands/shadow/back.4bpp.lz");
const u16 gMonPalette_IronHandsShadow[] = INCBIN_U16("graphics/pokemon/iron_hands/shadow/iron_hands_shadow.pal");
const u8 gMonIcon_IronHandsShadow[] = INCBIN_U8("graphics/pokemon/iron_hands/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_IronHandsShadow[] = INCBIN_COMP("graphics/pokemon/iron_hands/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_IronTreadsShadow[] = INCBIN_U32("graphics/pokemon/iron_treads/shadow/front.4bpp.lz");
const u32 gMonBackPic_IronTreadsShadow[] = INCBIN_U32("graphics/pokemon/iron_treads/shadow/back.4bpp.lz");
const u16 gMonPalette_IronTreadsShadow[] = INCBIN_U16("graphics/pokemon/iron_treads/shadow/iron_treads_shadow.pal");
const u8 gMonIcon_IronTreadsShadow[] = INCBIN_U8("graphics/pokemon/iron_treads/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_IronTreadsShadow[] = INCBIN_COMP("graphics/pokemon/iron_treads/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_JirachiShadow[] = INCBIN_U32("graphics/pokemon/jirachi/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_JirachiShadow[] = INCBIN_U32("graphics/pokemon/jirachi/shadow/back.4bpp.lz");
const u16 gMonPalette_JirachiShadow[] = INCBIN_U16("graphics/pokemon/jirachi/shadow/jirachi_shadow.pal");
const u8 gMonIcon_JirachiShadow[] = INCBIN_U8("graphics/pokemon/jirachi/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_JirachiShadow[] = INCBIN_COMP("graphics/pokemon/jirachi/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_KartanaShadow[] = INCBIN_U32("graphics/pokemon/kartana/shadow/front.4bpp.lz");
const u32 gMonBackPic_KartanaShadow[] = INCBIN_U32("graphics/pokemon/kartana/shadow/back.4bpp.lz");
const u16 gMonPalette_KartanaShadow[] = INCBIN_U16("graphics/pokemon/kartana/shadow/kartana_shadow.pal");
const u8 gMonIcon_KartanaShadow[] = INCBIN_U8("graphics/pokemon/kartana/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_KartanaShadow[] = INCBIN_COMP("graphics/pokemon/kartana/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_KeldeoShadow[] = INCBIN_U32("graphics/pokemon/keldeo/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_KeldeoShadow[] = INCBIN_U32("graphics/pokemon/keldeo/shadow/back.4bpp.lz");
const u16 gMonPalette_KeldeoShadow[] = INCBIN_U16("graphics/pokemon/keldeo/shadow/keldeo_shadow.pal");
const u8 gMonIcon_KeldeoShadow[] = INCBIN_U8("graphics/pokemon/keldeo/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_KeldeoShadow[] = INCBIN_COMP("graphics/pokemon/keldeo/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_KingdraShadow[] = INCBIN_U32("graphics/pokemon/kingdra/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_KingdraShadow[] = INCBIN_U32("graphics/pokemon/kingdra/shadow/back.4bpp.lz");
const u16 gMonPalette_KingdraShadow[] = INCBIN_U16("graphics/pokemon/kingdra/shadow/kingdra_shadow.pal");
const u8 gMonIcon_KingdraShadow[] = INCBIN_U8("graphics/pokemon/kingdra/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_KingdraShadow[] = INCBIN_COMP("graphics/pokemon/kingdra/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_KommoOShadow[] = INCBIN_U32("graphics/pokemon/kommo_o/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_KommoOShadow[] = INCBIN_U32("graphics/pokemon/kommo_o/shadow/back.4bpp.lz");
const u16 gMonPalette_KommoOShadow[] = INCBIN_U16("graphics/pokemon/kommo_o/shadow/kommo_o_shadow.pal");
const u8 gMonIcon_KommoOShadow[] = INCBIN_U8("graphics/pokemon/kommo_o/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_KommoOShadow[] = INCBIN_COMP("graphics/pokemon/kommo_o/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_KoraidonShadow[] = INCBIN_U32("graphics/pokemon/koraidon/shadow/front.4bpp.lz");
const u32 gMonBackPic_KoraidonShadow[] = INCBIN_U32("graphics/pokemon/koraidon/shadow/back.4bpp.lz");
const u16 gMonPalette_KoraidonShadow[] = INCBIN_U16("graphics/pokemon/koraidon/shadow/koraidon_shadow.pal");
const u8 gMonIcon_KoraidonShadow[] = INCBIN_U8("graphics/pokemon/koraidon/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_KoraidonShadow[] = INCBIN_COMP("graphics/pokemon/koraidon/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_KrookodileShadow[] = INCBIN_U32("graphics/pokemon/krookodile/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_KrookodileShadow[] = INCBIN_U32("graphics/pokemon/krookodile/shadow/back.4bpp.lz");
const u16 gMonPalette_KrookodileShadow[] = INCBIN_U16("graphics/pokemon/krookodile/shadow/krookodile_shadow.pal");
const u8 gMonIcon_KrookodileShadow[] = INCBIN_U8("graphics/pokemon/krookodile/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_KrookodileShadow[] = INCBIN_COMP("graphics/pokemon/krookodile/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_KyogreShadow[] = INCBIN_U32("graphics/pokemon/kyogre/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_KyogreShadow[] = INCBIN_U32("graphics/pokemon/kyogre/shadow/back.4bpp.lz");
const u16 gMonPalette_KyogreShadow[] = INCBIN_U16("graphics/pokemon/kyogre/shadow/kyogre_shadow.pal");
const u8 gMonIcon_KyogreShadow[] = INCBIN_U8("graphics/pokemon/kyogre/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_KyogreShadow[] = INCBIN_COMP("graphics/pokemon/kyogre/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_KyuremShadow[] = INCBIN_U32("graphics/pokemon/kyurem/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_KyuremShadow[] = INCBIN_U32("graphics/pokemon/kyurem/shadow/back.4bpp.lz");
const u16 gMonPalette_KyuremShadow[] = INCBIN_U16("graphics/pokemon/kyurem/shadow/kyurem_shadow.pal");
const u8 gMonIcon_KyuremShadow[] = INCBIN_U8("graphics/pokemon/kyurem/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_KyuremShadow[] = INCBIN_COMP("graphics/pokemon/kyurem/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_LandorusShadow[] = INCBIN_U32("graphics/pokemon/landorus/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_LandorusShadow[] = INCBIN_U32("graphics/pokemon/landorus/shadow/back.4bpp.lz");
const u16 gMonPalette_LandorusShadow[] = INCBIN_U16("graphics/pokemon/landorus/shadow/landorus_shadow.pal");
const u8 gMonIcon_LandorusShadow[] = INCBIN_U8("graphics/pokemon/landorus/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_LandorusShadow[] = INCBIN_COMP("graphics/pokemon/landorus/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_LatiasShadow[] = INCBIN_U32("graphics/pokemon/latias/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_LatiasShadow[] = INCBIN_U32("graphics/pokemon/latias/shadow/back.4bpp.lz");
const u16 gMonPalette_LatiasShadow[] = INCBIN_U16("graphics/pokemon/latias/shadow/latias_shadow.pal");
const u8 gMonIcon_LatiasShadow[] = INCBIN_U8("graphics/pokemon/latias/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_LatiasShadow[] = INCBIN_COMP("graphics/pokemon/latias/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_LatiosShadow[] = INCBIN_U32("graphics/pokemon/latios/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_LatiosShadow[] = INCBIN_U32("graphics/pokemon/latios/shadow/back.4bpp.lz");
const u16 gMonPalette_LatiosShadow[] = INCBIN_U16("graphics/pokemon/latios/shadow/latios_shadow.pal");
const u8 gMonIcon_LatiosShadow[] = INCBIN_U8("graphics/pokemon/latios/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_LatiosShadow[] = INCBIN_COMP("graphics/pokemon/latios/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_LucarioShadow[] = INCBIN_U32("graphics/pokemon/lucario/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_LucarioShadow[] = INCBIN_U32("graphics/pokemon/lucario/shadow/back.4bpp.lz");
const u16 gMonPalette_LucarioShadow[] = INCBIN_U16("graphics/pokemon/lucario/shadow/lucario_shadow.pal");
const u8 gMonIcon_LucarioShadow[] = INCBIN_U8("graphics/pokemon/lucario/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_LucarioShadow[] = INCBIN_COMP("graphics/pokemon/lucario/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_LunalaShadow[] = INCBIN_U32("graphics/pokemon/lunala/shadow/front.4bpp.lz");
const u32 gMonBackPic_LunalaShadow[] = INCBIN_U32("graphics/pokemon/lunala/shadow/back.4bpp.lz");
const u16 gMonPalette_LunalaShadow[] = INCBIN_U16("graphics/pokemon/lunala/shadow/lunala_shadow.pal");
const u8 gMonIcon_LunalaShadow[] = INCBIN_U8("graphics/pokemon/lunala/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_LunalaShadow[] = INCBIN_COMP("graphics/pokemon/lunala/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_MagearnaShadow[] = INCBIN_U32("graphics/pokemon/magearna/shadow/front.4bpp.lz");
const u32 gMonBackPic_MagearnaShadow[] = INCBIN_U32("graphics/pokemon/magearna/shadow/back.4bpp.lz");
const u16 gMonPalette_MagearnaShadow[] = INCBIN_U16("graphics/pokemon/magearna/shadow/magearna_shadow.pal");
const u8 gMonIcon_MagearnaShadow[] = INCBIN_U8("graphics/pokemon/magearna/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_MagearnaShadow[] = INCBIN_COMP("graphics/pokemon/magearna/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_MagnezoneShadow[] = INCBIN_U32("graphics/pokemon/magnezone/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_MagnezoneShadow[] = INCBIN_U32("graphics/pokemon/magnezone/shadow/back.4bpp.lz");
const u16 gMonPalette_MagnezoneShadow[] = INCBIN_U16("graphics/pokemon/magnezone/shadow/magnezone_shadow.pal");
const u8 gMonIcon_MagnezoneShadow[] = INCBIN_U8("graphics/pokemon/magnezone/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_MagnezoneShadow[] = INCBIN_COMP("graphics/pokemon/magnezone/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_MalamarShadow[] = INCBIN_U32("graphics/pokemon/malamar/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_MalamarShadow[] = INCBIN_U32("graphics/pokemon/malamar/shadow/back.4bpp.lz");
const u16 gMonPalette_MalamarShadow[] = INCBIN_U16("graphics/pokemon/malamar/shadow/malamar_shadow.pal");
const u8 gMonIcon_MalamarShadow[] = INCBIN_U8("graphics/pokemon/malamar/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_MalamarShadow[] = INCBIN_COMP("graphics/pokemon/malamar/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_ManaphyShadow[] = INCBIN_U32("graphics/pokemon/manaphy/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_ManaphyShadow[] = INCBIN_U32("graphics/pokemon/manaphy/shadow/back.4bpp.lz");
const u16 gMonPalette_ManaphyShadow[] = INCBIN_U16("graphics/pokemon/manaphy/shadow/manaphy_shadow.pal");
const u8 gMonIcon_ManaphyShadow[] = INCBIN_U8("graphics/pokemon/manaphy/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_ManaphyShadow[] = INCBIN_COMP("graphics/pokemon/manaphy/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_ManectricShadow[] = INCBIN_U32("graphics/pokemon/manectric/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_ManectricShadow[] = INCBIN_U32("graphics/pokemon/manectric/shadow/back.4bpp.lz");
const u16 gMonPalette_ManectricShadow[] = INCBIN_U16("graphics/pokemon/manectric/shadow/manectric_shadow.pal");
const u8 gMonIcon_ManectricShadow[] = INCBIN_U8("graphics/pokemon/manectric/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_ManectricShadow[] = INCBIN_COMP("graphics/pokemon/manectric/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_MarshadowShadow[] = INCBIN_U32("graphics/pokemon/marshadow/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_MarshadowShadow[] = INCBIN_U32("graphics/pokemon/marshadow/shadow/back.4bpp.lz");
const u16 gMonPalette_MarshadowShadow[] = INCBIN_U16("graphics/pokemon/marshadow/shadow/marshadow_shadow.pal");
const u8 gMonIcon_MarshadowShadow[] = INCBIN_U8("graphics/pokemon/marshadow/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_MarshadowShadow[] = INCBIN_COMP("graphics/pokemon/marshadow/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_MeganiumShadow[] = INCBIN_U32("graphics/pokemon/meganium/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_MeganiumShadow[] = INCBIN_U32("graphics/pokemon/meganium/shadow/back.4bpp.lz");
const u16 gMonPalette_MeganiumShadow[] = INCBIN_U16("graphics/pokemon/meganium/shadow/meganium_shadow.pal");
const u8 gMonIcon_MeganiumShadow[] = INCBIN_U8("graphics/pokemon/meganium/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_MeganiumShadow[] = INCBIN_COMP("graphics/pokemon/meganium/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_MelmetalShadow[] = INCBIN_U32("graphics/pokemon/melmetal/shadow/front.4bpp.lz");
const u32 gMonBackPic_MelmetalShadow[] = INCBIN_U32("graphics/pokemon/melmetal/shadow/back.4bpp.lz");
const u16 gMonPalette_MelmetalShadow[] = INCBIN_U16("graphics/pokemon/melmetal/shadow/melmetal_shadow.pal");
const u8 gMonIcon_MelmetalShadow[] = INCBIN_U8("graphics/pokemon/melmetal/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_MelmetalShadow[] = INCBIN_COMP("graphics/pokemon/melmetal/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_MeloettaShadow[] = INCBIN_U32("graphics/pokemon/meloetta/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_MeloettaShadow[] = INCBIN_U32("graphics/pokemon/meloetta/shadow/back.4bpp.lz");
const u16 gMonPalette_MeloettaShadow[] = INCBIN_U16("graphics/pokemon/meloetta/shadow/meloetta_shadow.pal");
const u8 gMonIcon_MeloettaShadow[] = INCBIN_U8("graphics/pokemon/meloetta/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_MeloettaShadow[] = INCBIN_COMP("graphics/pokemon/meloetta/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_MespritShadow[] = INCBIN_U32("graphics/pokemon/mesprit/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_MespritShadow[] = INCBIN_U32("graphics/pokemon/mesprit/shadow/back.4bpp.lz");
const u16 gMonPalette_MespritShadow[] = INCBIN_U16("graphics/pokemon/mesprit/shadow/mesprit_shadow.pal");
const u8 gMonIcon_MespritShadow[] = INCBIN_U8("graphics/pokemon/mesprit/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_MespritShadow[] = INCBIN_COMP("graphics/pokemon/mesprit/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_MeowscaradaShadow[] = INCBIN_U32("graphics/pokemon/meowscarada/shadow/front.4bpp.lz");
const u32 gMonBackPic_MeowscaradaShadow[] = INCBIN_U32("graphics/pokemon/meowscarada/shadow/back.4bpp.lz");
const u16 gMonPalette_MeowscaradaShadow[] = INCBIN_U16("graphics/pokemon/meowscarada/shadow/meowscarada_shadow.pal");
const u8 gMonIcon_MeowscaradaShadow[] = INCBIN_U8("graphics/pokemon/meowscarada/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_MeowscaradaShadow[] = INCBIN_COMP("graphics/pokemon/meowscarada/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_MewShadow[] = INCBIN_U32("graphics/pokemon/mew/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_MewShadow[] = INCBIN_U32("graphics/pokemon/mew/shadow/back.4bpp.lz");
const u16 gMonPalette_MewShadow[] = INCBIN_U16("graphics/pokemon/mew/shadow/mew_shadow.pal");
const u8 gMonIcon_MewShadow[] = INCBIN_U8("graphics/pokemon/mew/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_MewShadow[] = INCBIN_COMP("graphics/pokemon/mew/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_MewtwoShadow[] = INCBIN_U32("graphics/pokemon/mewtwo/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_MewtwoShadow[] = INCBIN_U32("graphics/pokemon/mewtwo/shadow/back.4bpp.lz");
const u16 gMonPalette_MewtwoShadow[] = INCBIN_U16("graphics/pokemon/mewtwo/shadow/mewtwo_shadow.pal");
const u8 gMonIcon_MewtwoShadow[] = INCBIN_U8("graphics/pokemon/mewtwo/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_MewtwoShadow[] = INCBIN_COMP("graphics/pokemon/mewtwo/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_MiloticShadow[] = INCBIN_U32("graphics/pokemon/milotic/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_MiloticShadow[] = INCBIN_U32("graphics/pokemon/milotic/shadow/back.4bpp.lz");
const u16 gMonPalette_MiloticShadow[] = INCBIN_U16("graphics/pokemon/milotic/shadow/milotic_shadow.pal");
const u8 gMonIcon_MiloticShadow[] = INCBIN_U8("graphics/pokemon/milotic/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_MiloticShadow[] = INCBIN_COMP("graphics/pokemon/milotic/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_MimikyuShadow[] = INCBIN_U32("graphics/pokemon/mimikyu/shadow/front.4bpp.lz");
const u32 gMonBackPic_MimikyuShadow[] = INCBIN_U32("graphics/pokemon/mimikyu/shadow/back.4bpp.lz");
const u16 gMonPalette_MimikyuShadow[] = INCBIN_U16("graphics/pokemon/mimikyu/shadow/mimikyu_shadow.pal");
const u8 gMonIcon_MimikyuShadow[] = INCBIN_U8("graphics/pokemon/mimikyu/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_MimikyuShadow[] = INCBIN_COMP("graphics/pokemon/mimikyu/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_MimikyuBustedShadow[] = INCBIN_U32("graphics/pokemon/mimikyu/busted/shadow/front.4bpp.lz");
const u32 gMonBackPic_MimikyuBustedShadow[] = INCBIN_U32("graphics/pokemon/mimikyu/busted/shadow/back.4bpp.lz");
const u16 gMonPalette_MimikyuBustedShadow[] = INCBIN_U16("graphics/pokemon/mimikyu/busted/shadow/mimikyu_busted_shadow.pal");
const u8 gMonIcon_MimikyuBustedShadow[] = INCBIN_U8("graphics/pokemon/mimikyu/busted/shadow/icon.4bpp");

const u32 gMonFrontPic_MiraidonShadow[] = INCBIN_U32("graphics/pokemon/miraidon/shadow/front.4bpp.lz");
const u32 gMonBackPic_MiraidonShadow[] = INCBIN_U32("graphics/pokemon/miraidon/shadow/back.4bpp.lz");
const u16 gMonPalette_MiraidonShadow[] = INCBIN_U16("graphics/pokemon/miraidon/shadow/miraidon_shadow.pal");
const u8 gMonIcon_MiraidonShadow[] = INCBIN_U8("graphics/pokemon/miraidon/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_MiraidonShadow[] = INCBIN_COMP("graphics/pokemon/miraidon/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_MoltresShadow[] = INCBIN_U32("graphics/pokemon/moltres/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_MoltresShadow[] = INCBIN_U32("graphics/pokemon/moltres/shadow/back.4bpp.lz");
const u16 gMonPalette_MoltresShadow[] = INCBIN_U16("graphics/pokemon/moltres/shadow/moltres_shadow.pal");
const u8 gMonIcon_MoltresShadow[] = INCBIN_U8("graphics/pokemon/moltres/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_MoltresShadow[] = INCBIN_COMP("graphics/pokemon/moltres/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_NaganadelShadow[] = INCBIN_U32("graphics/pokemon/naganadel/shadow/front.4bpp.lz");
const u32 gMonBackPic_NaganadelShadow[] = INCBIN_U32("graphics/pokemon/naganadel/shadow/back.4bpp.lz");
const u16 gMonPalette_NaganadelShadow[] = INCBIN_U16("graphics/pokemon/naganadel/shadow/naganadel_shadow.pal");
const u8 gMonIcon_NaganadelShadow[] = INCBIN_U8("graphics/pokemon/naganadel/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_NaganadelShadow[] = INCBIN_COMP("graphics/pokemon/naganadel/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_NecrozmaShadow[] = INCBIN_U32("graphics/pokemon/necrozma/shadow/front.4bpp.lz");
const u32 gMonBackPic_NecrozmaShadow[] = INCBIN_U32("graphics/pokemon/necrozma/shadow/back.4bpp.lz");
const u16 gMonPalette_NecrozmaShadow[] = INCBIN_U16("graphics/pokemon/necrozma/shadow/necrozma_shadow.pal");
const u8 gMonIcon_NecrozmaShadow[] = INCBIN_U8("graphics/pokemon/necrozma/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_NecrozmaShadow[] = INCBIN_COMP("graphics/pokemon/necrozma/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_NidokingShadow[] = INCBIN_U32("graphics/pokemon/nidoking/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_NidokingShadow[] = INCBIN_U32("graphics/pokemon/nidoking/shadow/back.4bpp.lz");
const u16 gMonPalette_NidokingShadow[] = INCBIN_U16("graphics/pokemon/nidoking/shadow/nidoking_shadow.pal");
const u8 gMonIcon_NidokingShadow[] = INCBIN_U8("graphics/pokemon/nidoking/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_NidokingShadow[] = INCBIN_COMP("graphics/pokemon/nidoking/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_NihilegoShadow[] = INCBIN_U32("graphics/pokemon/nihilego/shadow/front.4bpp.lz");
const u32 gMonBackPic_NihilegoShadow[] = INCBIN_U32("graphics/pokemon/nihilego/shadow/back.4bpp.lz");
const u16 gMonPalette_NihilegoShadow[] = INCBIN_U16("graphics/pokemon/nihilego/shadow/nihilego_shadow.pal");
const u8 gMonIcon_NihilegoShadow[] = INCBIN_U8("graphics/pokemon/nihilego/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_NihilegoShadow[] = INCBIN_COMP("graphics/pokemon/nihilego/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_ObstagoonShadow[] = INCBIN_U32("graphics/pokemon/obstagoon/shadow/front.4bpp.lz");
const u32 gMonBackPic_ObstagoonShadow[] = INCBIN_U32("graphics/pokemon/obstagoon/shadow/back.4bpp.lz");
const u16 gMonPalette_ObstagoonShadow[] = INCBIN_U16("graphics/pokemon/obstagoon/shadow/obstagoon_shadow.pal");
const u8 gMonIcon_ObstagoonShadow[] = INCBIN_U8("graphics/pokemon/obstagoon/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_ObstagoonShadow[] = INCBIN_COMP("graphics/pokemon/obstagoon/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_PalossandShadow[] = INCBIN_U32("graphics/pokemon/palossand/shadow/front.4bpp.lz");
const u32 gMonBackPic_PalossandShadow[] = INCBIN_U32("graphics/pokemon/palossand/shadow/back.4bpp.lz");
const u16 gMonPalette_PalossandShadow[] = INCBIN_U16("graphics/pokemon/palossand/shadow/palossand_shadow.pal");
const u8 gMonIcon_PalossandShadow[] = INCBIN_U8("graphics/pokemon/palossand/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_PalossandShadow[] = INCBIN_COMP("graphics/pokemon/palossand/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_PalkiaShadow[] = INCBIN_U32("graphics/pokemon/palkia/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_PalkiaShadow[] = INCBIN_U32("graphics/pokemon/palkia/shadow/back.4bpp.lz");
const u16 gMonPalette_PalkiaShadow[] = INCBIN_U16("graphics/pokemon/palkia/shadow/palkia_shadow.pal");
const u8 gMonIcon_PalkiaShadow[] = INCBIN_U8("graphics/pokemon/palkia/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_PalkiaShadow[] = INCBIN_COMP("graphics/pokemon/palkia/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_PangoroShadow[] = INCBIN_U32("graphics/pokemon/pangoro/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_PangoroShadow[] = INCBIN_U32("graphics/pokemon/pangoro/shadow/back.4bpp.lz");
const u16 gMonPalette_PangoroShadow[] = INCBIN_U16("graphics/pokemon/pangoro/shadow/pangoro_shadow.pal");
const u8 gMonIcon_PangoroShadow[] = INCBIN_U8("graphics/pokemon/pangoro/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_PangoroShadow[] = INCBIN_COMP("graphics/pokemon/pangoro/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_PecharuntShadow[] = INCBIN_U32("graphics/pokemon/pecharunt/shadow/front.4bpp.lz");
const u32 gMonBackPic_PecharuntShadow[] = INCBIN_U32("graphics/pokemon/pecharunt/shadow/back.4bpp.lz");
const u16 gMonPalette_PecharuntShadow[] = INCBIN_U16("graphics/pokemon/pecharunt/shadow/pecharunt_shadow.pal");
const u8 gMonIcon_PecharuntShadow[] = INCBIN_U8("graphics/pokemon/pecharunt/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_PecharuntShadow[] = INCBIN_COMP("graphics/pokemon/pecharunt/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_PheromosaShadow[] = INCBIN_U32("graphics/pokemon/pheromosa/shadow/front.4bpp.lz");
const u32 gMonBackPic_PheromosaShadow[] = INCBIN_U32("graphics/pokemon/pheromosa/shadow/back.4bpp.lz");
const u16 gMonPalette_PheromosaShadow[] = INCBIN_U16("graphics/pokemon/pheromosa/shadow/pheromosa_shadow.pal");
const u8 gMonIcon_PheromosaShadow[] = INCBIN_U8("graphics/pokemon/pheromosa/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_PheromosaShadow[] = INCBIN_COMP("graphics/pokemon/pheromosa/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_PrimarinaShadow[] = INCBIN_U32("graphics/pokemon/primarina/shadow/front.4bpp.lz");
const u32 gMonBackPic_PrimarinaShadow[] = INCBIN_U32("graphics/pokemon/primarina/shadow/back.4bpp.lz");
const u16 gMonPalette_PrimarinaShadow[] = INCBIN_U16("graphics/pokemon/primarina/shadow/primarina_shadow.pal");
const u8 gMonIcon_PrimarinaShadow[] = INCBIN_U8("graphics/pokemon/primarina/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_PrimarinaShadow[] = INCBIN_COMP("graphics/pokemon/primarina/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_QuaquavalShadow[] = INCBIN_U32("graphics/pokemon/quaquaval/shadow/front.4bpp.lz");
const u32 gMonBackPic_QuaquavalShadow[] = INCBIN_U32("graphics/pokemon/quaquaval/shadow/back.4bpp.lz");
const u16 gMonPalette_QuaquavalShadow[] = INCBIN_U16("graphics/pokemon/quaquaval/shadow/quaquaval_shadow.pal");
const u8 gMonIcon_QuaquavalShadow[] = INCBIN_U8("graphics/pokemon/quaquaval/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_QuaquavalShadow[] = INCBIN_COMP("graphics/pokemon/quaquaval/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_RaikouShadow[] = INCBIN_U32("graphics/pokemon/raikou/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_RaikouShadow[] = INCBIN_U32("graphics/pokemon/raikou/shadow/back.4bpp.lz");
const u16 gMonPalette_RaikouShadow[] = INCBIN_U16("graphics/pokemon/raikou/shadow/raikou_shadow.pal");
const u8 gMonIcon_RaikouShadow[] = INCBIN_U8("graphics/pokemon/raikou/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_RaikouShadow[] = INCBIN_COMP("graphics/pokemon/raikou/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_RayquazaShadow[] = INCBIN_U32("graphics/pokemon/rayquaza/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_RayquazaShadow[] = INCBIN_U32("graphics/pokemon/rayquaza/shadow/back.4bpp.lz");
const u16 gMonPalette_RayquazaShadow[] = INCBIN_U16("graphics/pokemon/rayquaza/shadow/rayquaza_shadow.pal");
const u8 gMonIcon_RayquazaShadow[] = INCBIN_U8("graphics/pokemon/rayquaza/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_RayquazaShadow[] = INCBIN_COMP("graphics/pokemon/rayquaza/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_RegiceShadow[] = INCBIN_U32("graphics/pokemon/regice/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_RegiceShadow[] = INCBIN_U32("graphics/pokemon/regice/shadow/back.4bpp.lz");
const u16 gMonPalette_RegiceShadow[] = INCBIN_U16("graphics/pokemon/regice/shadow/regice_shadow.pal");
const u8 gMonIcon_RegiceShadow[] = INCBIN_U8("graphics/pokemon/regice/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_RegiceShadow[] = INCBIN_COMP("graphics/pokemon/regice/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_RegidragoShadow[] = INCBIN_U32("graphics/pokemon/regidrago/shadow/front.4bpp.lz");
const u32 gMonBackPic_RegidragoShadow[] = INCBIN_U32("graphics/pokemon/regidrago/shadow/back.4bpp.lz");
const u16 gMonPalette_RegidragoShadow[] = INCBIN_U16("graphics/pokemon/regidrago/shadow/regidrago_shadow.pal");
const u8 gMonIcon_RegidragoShadow[] = INCBIN_U8("graphics/pokemon/regidrago/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_RegidragoShadow[] = INCBIN_COMP("graphics/pokemon/regidrago/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_RegielekiShadow[] = INCBIN_U32("graphics/pokemon/regieleki/shadow/front.4bpp.lz");
const u32 gMonBackPic_RegielekiShadow[] = INCBIN_U32("graphics/pokemon/regieleki/shadow/back.4bpp.lz");
const u16 gMonPalette_RegielekiShadow[] = INCBIN_U16("graphics/pokemon/regieleki/shadow/regieleki_shadow.pal");
const u8 gMonIcon_RegielekiShadow[] = INCBIN_U8("graphics/pokemon/regieleki/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_RegielekiShadow[] = INCBIN_COMP("graphics/pokemon/regieleki/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_RegigigasShadow[] = INCBIN_U32("graphics/pokemon/regigigas/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_RegigigasShadow[] = INCBIN_U32("graphics/pokemon/regigigas/shadow/back.4bpp.lz");
const u16 gMonPalette_RegigigasShadow[] = INCBIN_U16("graphics/pokemon/regigigas/shadow/regigigas_shadow.pal");
const u8 gMonIcon_RegigigasShadow[] = INCBIN_U8("graphics/pokemon/regigigas/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_RegigigasShadow[] = INCBIN_COMP("graphics/pokemon/regigigas/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_RegirockShadow[] = INCBIN_U32("graphics/pokemon/regirock/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_RegirockShadow[] = INCBIN_U32("graphics/pokemon/regirock/shadow/back.4bpp.lz");
const u16 gMonPalette_RegirockShadow[] = INCBIN_U16("graphics/pokemon/regirock/shadow/regirock_shadow.pal");
const u8 gMonIcon_RegirockShadow[] = INCBIN_U8("graphics/pokemon/regirock/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_RegirockShadow[] = INCBIN_COMP("graphics/pokemon/regirock/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_RegisteelShadow[] = INCBIN_U32("graphics/pokemon/registeel/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_RegisteelShadow[] = INCBIN_U32("graphics/pokemon/registeel/shadow/back.4bpp.lz");
const u16 gMonPalette_RegisteelShadow[] = INCBIN_U16("graphics/pokemon/registeel/shadow/registeel_shadow.pal");
const u8 gMonIcon_RegisteelShadow[] = INCBIN_U8("graphics/pokemon/registeel/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_RegisteelShadow[] = INCBIN_COMP("graphics/pokemon/registeel/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_ReuniclusShadow[] = INCBIN_U32("graphics/pokemon/reuniclus/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_ReuniclusShadow[] = INCBIN_U32("graphics/pokemon/reuniclus/shadow/back.4bpp.lz");
const u16 gMonPalette_ReuniclusShadow[] = INCBIN_U16("graphics/pokemon/reuniclus/shadow/reuniclus_shadow.pal");
const u8 gMonIcon_ReuniclusShadow[] = INCBIN_U8("graphics/pokemon/reuniclus/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_ReuniclusShadow[] = INCBIN_COMP("graphics/pokemon/reuniclus/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_ReshiramShadow[] = INCBIN_U32("graphics/pokemon/reshiram/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_ReshiramShadow[] = INCBIN_U32("graphics/pokemon/reshiram/shadow/back.4bpp.lz");
const u16 gMonPalette_ReshiramShadow[] = INCBIN_U16("graphics/pokemon/reshiram/shadow/reshiram_shadow.pal");
const u8 gMonIcon_ReshiramShadow[] = INCBIN_U8("graphics/pokemon/reshiram/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_ReshiramShadow[] = INCBIN_COMP("graphics/pokemon/reshiram/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_RhyperiorShadow[] = INCBIN_U32("graphics/pokemon/rhyperior/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_RhyperiorShadow[] = INCBIN_U32("graphics/pokemon/rhyperior/shadow/back.4bpp.lz");
const u16 gMonPalette_RhyperiorShadow[] = INCBIN_U16("graphics/pokemon/rhyperior/shadow/rhyperior_shadow.pal");
const u8 gMonIcon_RhyperiorShadow[] = INCBIN_U8("graphics/pokemon/rhyperior/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_RhyperiorShadow[] = INCBIN_COMP("graphics/pokemon/rhyperior/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_RillaboomShadow[] = INCBIN_U32("graphics/pokemon/rillaboom/shadow/front.4bpp.lz");
const u32 gMonBackPic_RillaboomShadow[] = INCBIN_U32("graphics/pokemon/rillaboom/shadow/back.4bpp.lz");
const u16 gMonPalette_RillaboomShadow[] = INCBIN_U16("graphics/pokemon/rillaboom/shadow/rillaboom_shadow.pal");
const u8 gMonIcon_RillaboomShadow[] = INCBIN_U8("graphics/pokemon/rillaboom/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_RillaboomShadow[] = INCBIN_COMP("graphics/pokemon/rillaboom/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_SalamenceShadow[] = INCBIN_U32("graphics/pokemon/salamence/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_SalamenceShadow[] = INCBIN_U32("graphics/pokemon/salamence/shadow/back.4bpp.lz");
const u16 gMonPalette_SalamenceShadow[] = INCBIN_U16("graphics/pokemon/salamence/shadow/salamence_shadow.pal");
const u8 gMonIcon_SalamenceShadow[] = INCBIN_U8("graphics/pokemon/salamence/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_SalamenceShadow[] = INCBIN_COMP("graphics/pokemon/salamence/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_SalazzleShadow[] = INCBIN_U32("graphics/pokemon/salazzle/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_SalazzleShadow[] = INCBIN_U32("graphics/pokemon/salazzle/shadow/back.4bpp.lz");
const u16 gMonPalette_SalazzleShadow[] = INCBIN_U16("graphics/pokemon/salazzle/shadow/salazzle_shadow.pal");
const u8 gMonIcon_SalazzleShadow[] = INCBIN_U8("graphics/pokemon/salazzle/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_SalazzleShadow[] = INCBIN_COMP("graphics/pokemon/salazzle/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_SamurottShadow[] = INCBIN_U32("graphics/pokemon/samurott/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_SamurottShadow[] = INCBIN_U32("graphics/pokemon/samurott/shadow/back.4bpp.lz");
const u16 gMonPalette_SamurottShadow[] = INCBIN_U16("graphics/pokemon/samurott/shadow/samurott_shadow.pal");
const u8 gMonIcon_SamurottShadow[] = INCBIN_U8("graphics/pokemon/samurott/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_SamurottShadow[] = INCBIN_COMP("graphics/pokemon/samurott/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_SceptileShadow[] = INCBIN_U32("graphics/pokemon/sceptile/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_SceptileShadow[] = INCBIN_U32("graphics/pokemon/sceptile/shadow/back.4bpp.lz");
const u16 gMonPalette_SceptileShadow[] = INCBIN_U16("graphics/pokemon/sceptile/shadow/sceptile_shadow.pal");
const u8 gMonIcon_SceptileShadow[] = INCBIN_U8("graphics/pokemon/sceptile/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_SceptileShadow[] = INCBIN_COMP("graphics/pokemon/sceptile/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_ScreamTailShadow[] = INCBIN_U32("graphics/pokemon/scream_tail/shadow/front.4bpp.lz");
const u32 gMonBackPic_ScreamTailShadow[] = INCBIN_U32("graphics/pokemon/scream_tail/shadow/back.4bpp.lz");
const u16 gMonPalette_ScreamTailShadow[] = INCBIN_U16("graphics/pokemon/scream_tail/shadow/scream_tail_shadow.pal");
const u8 gMonIcon_ScreamTailShadow[] = INCBIN_U8("graphics/pokemon/scream_tail/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_ScreamTailShadow[] = INCBIN_COMP("graphics/pokemon/scream_tail/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_SerperiorShadow[] = INCBIN_U32("graphics/pokemon/serperior/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_SerperiorShadow[] = INCBIN_U32("graphics/pokemon/serperior/shadow/back.4bpp.lz");
const u16 gMonPalette_SerperiorShadow[] = INCBIN_U16("graphics/pokemon/serperior/shadow/serperior_shadow.pal");
const u8 gMonIcon_SerperiorShadow[] = INCBIN_U8("graphics/pokemon/serperior/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_SerperiorShadow[] = INCBIN_COMP("graphics/pokemon/serperior/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_LugiaShadow[] = INCBIN_U32("graphics/pokemon/lugia/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_LugiaShadow[] = INCBIN_U32("graphics/pokemon/lugia/shadow/back.4bpp.lz");
const u16 gMonPalette_LugiaShadow[] = INCBIN_U16("graphics/pokemon/lugia/shadow/lugia_shadow.pal");
const u8 gMonIcon_LugiaShadow[] = INCBIN_U8("graphics/pokemon/lugia/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_LugiaShadow[] = INCBIN_COMP("graphics/pokemon/lugia/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_SharpedoShadow[] = INCBIN_U32("graphics/pokemon/sharpedo/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_SharpedoShadow[] = INCBIN_U32("graphics/pokemon/sharpedo/shadow/back.4bpp.lz");
const u16 gMonPalette_SharpedoShadow[] = INCBIN_U16("graphics/pokemon/sharpedo/shadow/sharpedo_shadow.pal");
const u8 gMonIcon_SharpedoShadow[] = INCBIN_U8("graphics/pokemon/sharpedo/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_SharpedoShadow[] = INCBIN_COMP("graphics/pokemon/sharpedo/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_SilvallyShadow[] = INCBIN_U32("graphics/pokemon/silvally/shadow/front.4bpp.lz");
const u32 gMonBackPic_SilvallyShadow[] = INCBIN_U32("graphics/pokemon/silvally/shadow/back.4bpp.lz");
const u16 gMonPalette_SilvallyShadow[] = INCBIN_U16("graphics/pokemon/silvally/shadow/silvally_shadow.pal");
const u8 gMonIcon_SilvallyShadow[] = INCBIN_U8("graphics/pokemon/silvally/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_SilvallyShadow[] = INCBIN_COMP("graphics/pokemon/silvally/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_SkarmoryShadow[] = INCBIN_U32("graphics/pokemon/skarmory/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_SkarmoryShadow[] = INCBIN_U32("graphics/pokemon/skarmory/shadow/back.4bpp.lz");
const u16 gMonPalette_SkarmoryShadow[] = INCBIN_U16("graphics/pokemon/skarmory/shadow/skarmory_shadow.pal");
const u8 gMonIcon_SkarmoryShadow[] = INCBIN_U8("graphics/pokemon/skarmory/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_SkarmoryShadow[] = INCBIN_COMP("graphics/pokemon/skarmory/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_SkeledirgeShadow[] = INCBIN_U32("graphics/pokemon/skeledirge/shadow/front.4bpp.lz");
const u32 gMonBackPic_SkeledirgeShadow[] = INCBIN_U32("graphics/pokemon/skeledirge/shadow/back.4bpp.lz");
const u16 gMonPalette_SkeledirgeShadow[] = INCBIN_U16("graphics/pokemon/skeledirge/shadow/skeledirge_shadow.pal");
const u8 gMonIcon_SkeledirgeShadow[] = INCBIN_U8("graphics/pokemon/skeledirge/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_SkeledirgeShadow[] = INCBIN_COMP("graphics/pokemon/skeledirge/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_SnorlaxShadow[] = INCBIN_U32("graphics/pokemon/snorlax/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_SnorlaxShadow[] = INCBIN_U32("graphics/pokemon/snorlax/shadow/back.4bpp.lz");
const u16 gMonPalette_SnorlaxShadow[] = INCBIN_U16("graphics/pokemon/snorlax/shadow/snorlax_shadow.pal");
const u8 gMonIcon_SnorlaxShadow[] = INCBIN_U8("graphics/pokemon/snorlax/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_SnorlaxShadow[] = INCBIN_COMP("graphics/pokemon/snorlax/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_SolgaleoShadow[] = INCBIN_U32("graphics/pokemon/solgaleo/shadow/front.4bpp.lz");
const u32 gMonBackPic_SolgaleoShadow[] = INCBIN_U32("graphics/pokemon/solgaleo/shadow/back.4bpp.lz");
const u16 gMonPalette_SolgaleoShadow[] = INCBIN_U16("graphics/pokemon/solgaleo/shadow/solgaleo_shadow.pal");
const u8 gMonIcon_SolgaleoShadow[] = INCBIN_U8("graphics/pokemon/solgaleo/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_SolgaleoShadow[] = INCBIN_COMP("graphics/pokemon/solgaleo/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_StakatakaShadow[] = INCBIN_U32("graphics/pokemon/stakataka/shadow/front.4bpp.lz");
const u32 gMonBackPic_StakatakaShadow[] = INCBIN_U32("graphics/pokemon/stakataka/shadow/back.4bpp.lz");
const u16 gMonPalette_StakatakaShadow[] = INCBIN_U16("graphics/pokemon/stakataka/shadow/stakataka_shadow.pal");
const u8 gMonIcon_StakatakaShadow[] = INCBIN_U8("graphics/pokemon/stakataka/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_StakatakaShadow[] = INCBIN_COMP("graphics/pokemon/stakataka/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_SteelixShadow[] = INCBIN_U32("graphics/pokemon/steelix/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_SteelixShadow[] = INCBIN_U32("graphics/pokemon/steelix/shadow/back.4bpp.lz");
const u16 gMonPalette_SteelixShadow[] = INCBIN_U16("graphics/pokemon/steelix/shadow/steelix_shadow.pal");
const u8 gMonIcon_SteelixShadow[] = INCBIN_U8("graphics/pokemon/steelix/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_SteelixShadow[] = INCBIN_COMP("graphics/pokemon/steelix/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_SuicuneShadow[] = INCBIN_U32("graphics/pokemon/suicune/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_SuicuneShadow[] = INCBIN_U32("graphics/pokemon/suicune/shadow/back.4bpp.lz");
const u16 gMonPalette_SuicuneShadow[] = INCBIN_U16("graphics/pokemon/suicune/shadow/suicune_shadow.pal");
const u8 gMonIcon_SuicuneShadow[] = INCBIN_U8("graphics/pokemon/suicune/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_SuicuneShadow[] = INCBIN_COMP("graphics/pokemon/suicune/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_SwampertShadow[] = INCBIN_U32("graphics/pokemon/swampert/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_SwampertShadow[] = INCBIN_U32("graphics/pokemon/swampert/shadow/back.4bpp.lz");
const u16 gMonPalette_SwampertShadow[] = INCBIN_U16("graphics/pokemon/swampert/shadow/swampert_shadow.pal");
const u8 gMonIcon_SwampertShadow[] = INCBIN_U8("graphics/pokemon/swampert/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_SwampertShadow[] = INCBIN_COMP("graphics/pokemon/swampert/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_TapuBuluShadow[] = INCBIN_U32("graphics/pokemon/tapu_bulu/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_TapuBuluShadow[] = INCBIN_U32("graphics/pokemon/tapu_bulu/shadow/back.4bpp.lz");
const u16 gMonPalette_TapuBuluShadow[] = INCBIN_U16("graphics/pokemon/tapu_bulu/shadow/tapu_bulu_shadow.pal");
const u8 gMonIcon_TapuBuluShadow[] = INCBIN_U8("graphics/pokemon/tapu_bulu/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_TapuBuluShadow[] = INCBIN_COMP("graphics/pokemon/tapu_bulu/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_TapuFiniShadow[] = INCBIN_U32("graphics/pokemon/tapu_fini/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_TapuFiniShadow[] = INCBIN_U32("graphics/pokemon/tapu_fini/shadow/back.4bpp.lz");
const u16 gMonPalette_TapuFiniShadow[] = INCBIN_U16("graphics/pokemon/tapu_fini/shadow/tapu_fini_shadow.pal");
const u8 gMonIcon_TapuFiniShadow[] = INCBIN_U8("graphics/pokemon/tapu_fini/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_TapuFiniShadow[] = INCBIN_COMP("graphics/pokemon/tapu_fini/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_TapuKokoShadow[] = INCBIN_U32("graphics/pokemon/tapu_koko/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_TapuKokoShadow[] = INCBIN_U32("graphics/pokemon/tapu_koko/shadow/back.4bpp.lz");
const u16 gMonPalette_TapuKokoShadow[] = INCBIN_U16("graphics/pokemon/tapu_koko/shadow/tapu_koko_shadow.pal");
const u8 gMonIcon_TapuKokoShadow[] = INCBIN_U8("graphics/pokemon/tapu_koko/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_TapuKokoShadow[] = INCBIN_COMP("graphics/pokemon/tapu_koko/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_TapuLeleShadow[] = INCBIN_U32("graphics/pokemon/tapu_lele/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_TapuLeleShadow[] = INCBIN_U32("graphics/pokemon/tapu_lele/shadow/back.4bpp.lz");
const u16 gMonPalette_TapuLeleShadow[] = INCBIN_U16("graphics/pokemon/tapu_lele/shadow/tapu_lele_shadow.pal");
const u8 gMonIcon_TapuLeleShadow[] = INCBIN_U8("graphics/pokemon/tapu_lele/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_TapuLeleShadow[] = INCBIN_COMP("graphics/pokemon/tapu_lele/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_TalonflameShadow[] = INCBIN_U32("graphics/pokemon/talonflame/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_TalonflameShadow[] = INCBIN_U32("graphics/pokemon/talonflame/shadow/back.4bpp.lz");
const u16 gMonPalette_TalonflameShadow[] = INCBIN_U16("graphics/pokemon/talonflame/shadow/talonflame_shadow.pal");
const u8 gMonIcon_TalonflameShadow[] = INCBIN_U8("graphics/pokemon/talonflame/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_TalonflameShadow[] = INCBIN_COMP("graphics/pokemon/talonflame/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_TerapagosShadow[] = INCBIN_U32("graphics/pokemon/terapagos/shadow/front.4bpp.lz");
const u32 gMonBackPic_TerapagosShadow[] = INCBIN_U32("graphics/pokemon/terapagos/shadow/back.4bpp.lz");
const u16 gMonPalette_TerapagosShadow[] = INCBIN_U16("graphics/pokemon/terapagos/shadow/terapagos_shadow.pal");
const u8 gMonIcon_TerapagosShadow[] = INCBIN_U8("graphics/pokemon/terapagos/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_TerapagosShadow[] = INCBIN_COMP("graphics/pokemon/terapagos/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_TerrakionShadow[] = INCBIN_U32("graphics/pokemon/terrakion/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_TerrakionShadow[] = INCBIN_U32("graphics/pokemon/terrakion/shadow/back.4bpp.lz");
const u16 gMonPalette_TerrakionShadow[] = INCBIN_U16("graphics/pokemon/terrakion/shadow/terrakion_shadow.pal");
const u8 gMonIcon_TerrakionShadow[] = INCBIN_U8("graphics/pokemon/terrakion/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_TerrakionShadow[] = INCBIN_COMP("graphics/pokemon/terrakion/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_ThundurusShadow[] = INCBIN_U32("graphics/pokemon/thundurus/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_ThundurusShadow[] = INCBIN_U32("graphics/pokemon/thundurus/shadow/back.4bpp.lz");
const u16 gMonPalette_ThundurusShadow[] = INCBIN_U16("graphics/pokemon/thundurus/shadow/thundurus_shadow.pal");
const u8 gMonIcon_ThundurusShadow[] = INCBIN_U8("graphics/pokemon/thundurus/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_ThundurusShadow[] = INCBIN_COMP("graphics/pokemon/thundurus/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_TingLuShadow[] = INCBIN_U32("graphics/pokemon/ting_lu/shadow/front.4bpp.lz");
const u32 gMonBackPic_TingLuShadow[] = INCBIN_U32("graphics/pokemon/ting_lu/shadow/back.4bpp.lz");
const u16 gMonPalette_TingLuShadow[] = INCBIN_U16("graphics/pokemon/ting_lu/shadow/ting_lu_shadow.pal");
const u8 gMonIcon_TingLuShadow[] = INCBIN_U8("graphics/pokemon/ting_lu/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_TingLuShadow[] = INCBIN_COMP("graphics/pokemon/ting_lu/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_TornadusShadow[] = INCBIN_U32("graphics/pokemon/tornadus/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_TornadusShadow[] = INCBIN_U32("graphics/pokemon/tornadus/shadow/back.4bpp.lz");
const u16 gMonPalette_TornadusShadow[] = INCBIN_U16("graphics/pokemon/tornadus/shadow/tornadus_shadow.pal");
const u8 gMonIcon_TornadusShadow[] = INCBIN_U8("graphics/pokemon/tornadus/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_TornadusShadow[] = INCBIN_COMP("graphics/pokemon/tornadus/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_TorterraShadow[] = INCBIN_U32("graphics/pokemon/torterra/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_TorterraShadow[] = INCBIN_U32("graphics/pokemon/torterra/shadow/back.4bpp.lz");
const u16 gMonPalette_TorterraShadow[] = INCBIN_U16("graphics/pokemon/torterra/shadow/torterra_shadow.pal");
const u8 gMonIcon_TorterraShadow[] = INCBIN_U8("graphics/pokemon/torterra/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_TorterraShadow[] = INCBIN_COMP("graphics/pokemon/torterra/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_ToxapexShadow[] = INCBIN_U32("graphics/pokemon/toxapex/shadow/front.4bpp.lz");
const u32 gMonBackPic_ToxapexShadow[] = INCBIN_U32("graphics/pokemon/toxapex/shadow/back.4bpp.lz");
const u16 gMonPalette_ToxapexShadow[] = INCBIN_U16("graphics/pokemon/toxapex/shadow/toxapex_shadow.pal");
const u8 gMonIcon_ToxapexShadow[] = INCBIN_U8("graphics/pokemon/toxapex/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_ToxapexShadow[] = INCBIN_COMP("graphics/pokemon/toxapex/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_TyphlosionShadow[] = INCBIN_U32("graphics/pokemon/typhlosion/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_TyphlosionShadow[] = INCBIN_U32("graphics/pokemon/typhlosion/shadow/back.4bpp.lz");
const u16 gMonPalette_TyphlosionShadow[] = INCBIN_U16("graphics/pokemon/typhlosion/shadow/typhlosion_shadow.pal");
const u8 gMonIcon_TyphlosionShadow[] = INCBIN_U8("graphics/pokemon/typhlosion/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_TyphlosionShadow[] = INCBIN_COMP("graphics/pokemon/typhlosion/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_TyranitarShadow[] = INCBIN_U32("graphics/pokemon/tyranitar/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_TyranitarShadow[] = INCBIN_U32("graphics/pokemon/tyranitar/shadow/back.4bpp.lz");
const u16 gMonPalette_TyranitarShadow[] = INCBIN_U16("graphics/pokemon/tyranitar/shadow/tyranitar_shadow.pal");
const u8 gMonIcon_TyranitarShadow[] = INCBIN_U8("graphics/pokemon/tyranitar/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_TyranitarShadow[] = INCBIN_COMP("graphics/pokemon/tyranitar/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_TyrantrumShadow[] = INCBIN_U32("graphics/pokemon/tyrantrum/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_TyrantrumShadow[] = INCBIN_U32("graphics/pokemon/tyrantrum/shadow/back.4bpp.lz");
const u16 gMonPalette_TyrantrumShadow[] = INCBIN_U16("graphics/pokemon/tyrantrum/shadow/tyrantrum_shadow.pal");
const u8 gMonIcon_TyrantrumShadow[] = INCBIN_U8("graphics/pokemon/tyrantrum/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_TyrantrumShadow[] = INCBIN_COMP("graphics/pokemon/tyrantrum/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_UxieShadow[] = INCBIN_U32("graphics/pokemon/uxie/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_UxieShadow[] = INCBIN_U32("graphics/pokemon/uxie/shadow/back.4bpp.lz");
const u16 gMonPalette_UxieShadow[] = INCBIN_U16("graphics/pokemon/uxie/shadow/uxie_shadow.pal");
const u8 gMonIcon_UxieShadow[] = INCBIN_U8("graphics/pokemon/uxie/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_UxieShadow[] = INCBIN_COMP("graphics/pokemon/uxie/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_VenusaurShadow[] = INCBIN_U32("graphics/pokemon/venusaur/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_VenusaurShadow[] = INCBIN_U32("graphics/pokemon/venusaur/shadow/back.4bpp.lz");
const u16 gMonPalette_VenusaurShadow[] = INCBIN_U16("graphics/pokemon/venusaur/shadow/venusaur_shadow.pal");
const u8 gMonIcon_VenusaurShadow[] = INCBIN_U8("graphics/pokemon/venusaur/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_VenusaurShadow[] = INCBIN_COMP("graphics/pokemon/venusaur/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_VictiniShadow[] = INCBIN_U32("graphics/pokemon/victini/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_VictiniShadow[] = INCBIN_U32("graphics/pokemon/victini/shadow/back.4bpp.lz");
const u16 gMonPalette_VictiniShadow[] = INCBIN_U16("graphics/pokemon/victini/shadow/victini_shadow.pal");
const u8 gMonIcon_VictiniShadow[] = INCBIN_U8("graphics/pokemon/victini/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_VictiniShadow[] = INCBIN_COMP("graphics/pokemon/victini/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_VikavoltShadow[] = INCBIN_U32("graphics/pokemon/vikavolt/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_VikavoltShadow[] = INCBIN_U32("graphics/pokemon/vikavolt/shadow/back.4bpp.lz");
const u16 gMonPalette_VikavoltShadow[] = INCBIN_U16("graphics/pokemon/vikavolt/shadow/vikavolt_shadow.pal");
const u8 gMonIcon_VikavoltShadow[] = INCBIN_U8("graphics/pokemon/vikavolt/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_VikavoltShadow[] = INCBIN_COMP("graphics/pokemon/vikavolt/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_VirizionShadow[] = INCBIN_U32("graphics/pokemon/virizion/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_VirizionShadow[] = INCBIN_U32("graphics/pokemon/virizion/shadow/back.4bpp.lz");
const u16 gMonPalette_VirizionShadow[] = INCBIN_U16("graphics/pokemon/virizion/shadow/virizion_shadow.pal");
const u8 gMonIcon_VirizionShadow[] = INCBIN_U8("graphics/pokemon/virizion/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_VirizionShadow[] = INCBIN_COMP("graphics/pokemon/virizion/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_VolcanionShadow[] = INCBIN_U32("graphics/pokemon/volcanion/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_VolcanionShadow[] = INCBIN_U32("graphics/pokemon/volcanion/shadow/back.4bpp.lz");
const u16 gMonPalette_VolcanionShadow[] = INCBIN_U16("graphics/pokemon/volcanion/shadow/volcanion_shadow.pal");
const u8 gMonIcon_VolcanionShadow[] = INCBIN_U8("graphics/pokemon/volcanion/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_VolcanionShadow[] = INCBIN_COMP("graphics/pokemon/volcanion/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_VolcaronaShadow[] = INCBIN_U32("graphics/pokemon/volcarona/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_VolcaronaShadow[] = INCBIN_U32("graphics/pokemon/volcarona/shadow/back.4bpp.lz");
const u16 gMonPalette_VolcaronaShadow[] = INCBIN_U16("graphics/pokemon/volcarona/shadow/volcarona_shadow.pal");
const u8 gMonIcon_VolcaronaShadow[] = INCBIN_U8("graphics/pokemon/volcarona/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_VolcaronaShadow[] = INCBIN_COMP("graphics/pokemon/volcarona/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_WalreinShadow[] = INCBIN_U32("graphics/pokemon/walrein/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_WalreinShadow[] = INCBIN_U32("graphics/pokemon/walrein/shadow/back.4bpp.lz");
const u16 gMonPalette_WalreinShadow[] = INCBIN_U16("graphics/pokemon/walrein/shadow/walrein_shadow.pal");
const u8 gMonIcon_WalreinShadow[] = INCBIN_U8("graphics/pokemon/walrein/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_WalreinShadow[] = INCBIN_COMP("graphics/pokemon/walrein/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_WeavileShadow[] = INCBIN_U32("graphics/pokemon/weavile/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_WeavileShadow[] = INCBIN_U32("graphics/pokemon/weavile/shadow/back.4bpp.lz");
const u16 gMonPalette_WeavileShadow[] = INCBIN_U16("graphics/pokemon/weavile/shadow/weavile_shadow.pal");
const u8 gMonIcon_WeavileShadow[] = INCBIN_U8("graphics/pokemon/weavile/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_WeavileShadow[] = INCBIN_COMP("graphics/pokemon/weavile/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_WoChienShadow[] = INCBIN_U32("graphics/pokemon/wo_chien/shadow/front.4bpp.lz");
const u32 gMonBackPic_WoChienShadow[] = INCBIN_U32("graphics/pokemon/wo_chien/shadow/back.4bpp.lz");
const u16 gMonPalette_WoChienShadow[] = INCBIN_U16("graphics/pokemon/wo_chien/shadow/wo_chien_shadow.pal");
const u8 gMonIcon_WoChienShadow[] = INCBIN_U8("graphics/pokemon/wo_chien/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_WoChienShadow[] = INCBIN_COMP("graphics/pokemon/wo_chien/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_XerneasShadow[] = INCBIN_U32("graphics/pokemon/xerneas/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_XerneasShadow[] = INCBIN_U32("graphics/pokemon/xerneas/shadow/back.4bpp.lz");
const u16 gMonPalette_XerneasShadow[] = INCBIN_U16("graphics/pokemon/xerneas/shadow/xerneas_shadow.pal");
const u8 gMonIcon_XerneasShadow[] = INCBIN_U8("graphics/pokemon/xerneas/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_XerneasShadow[] = INCBIN_COMP("graphics/pokemon/xerneas/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_XurkitreeShadow[] = INCBIN_U32("graphics/pokemon/xurkitree/shadow/front.4bpp.lz");
const u32 gMonBackPic_XurkitreeShadow[] = INCBIN_U32("graphics/pokemon/xurkitree/shadow/back.4bpp.lz");
const u16 gMonPalette_XurkitreeShadow[] = INCBIN_U16("graphics/pokemon/xurkitree/shadow/xurkitree_shadow.pal");
const u8 gMonIcon_XurkitreeShadow[] = INCBIN_U8("graphics/pokemon/xurkitree/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_XurkitreeShadow[] = INCBIN_COMP("graphics/pokemon/xurkitree/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_YveltalShadow[] = INCBIN_U32("graphics/pokemon/yveltal/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_YveltalShadow[] = INCBIN_U32("graphics/pokemon/yveltal/shadow/back.4bpp.lz");
const u16 gMonPalette_YveltalShadow[] = INCBIN_U16("graphics/pokemon/yveltal/shadow/yveltal_shadow.pal");
const u8 gMonIcon_YveltalShadow[] = INCBIN_U8("graphics/pokemon/yveltal/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_YveltalShadow[] = INCBIN_COMP("graphics/pokemon/yveltal/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_ZacianShadow[] = INCBIN_U32("graphics/pokemon/zacian/shadow/front.4bpp.lz");
const u32 gMonBackPic_ZacianShadow[] = INCBIN_U32("graphics/pokemon/zacian/shadow/back.4bpp.lz");
const u16 gMonPalette_ZacianShadow[] = INCBIN_U16("graphics/pokemon/zacian/shadow/zacian_shadow.pal");
const u8 gMonIcon_ZacianShadow[] = INCBIN_U8("graphics/pokemon/zacian/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_ZacianShadow[] = INCBIN_COMP("graphics/pokemon/zacian/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_ZamazentaShadow[] = INCBIN_U32("graphics/pokemon/zamazenta/shadow/front.4bpp.lz");
const u32 gMonBackPic_ZamazentaShadow[] = INCBIN_U32("graphics/pokemon/zamazenta/shadow/back.4bpp.lz");
const u16 gMonPalette_ZamazentaShadow[] = INCBIN_U16("graphics/pokemon/zamazenta/shadow/zamazenta_shadow.pal");
const u8 gMonIcon_ZamazentaShadow[] = INCBIN_U8("graphics/pokemon/zamazenta/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_ZamazentaShadow[] = INCBIN_COMP("graphics/pokemon/zamazenta/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_ZapdosShadow[] = INCBIN_U32("graphics/pokemon/zapdos/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_ZapdosShadow[] = INCBIN_U32("graphics/pokemon/zapdos/shadow/back.4bpp.lz");
const u16 gMonPalette_ZapdosShadow[] = INCBIN_U16("graphics/pokemon/zapdos/shadow/zapdos_shadow.pal");
const u8 gMonIcon_ZapdosShadow[] = INCBIN_U8("graphics/pokemon/zapdos/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_ZapdosShadow[] = INCBIN_COMP("graphics/pokemon/zapdos/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_ZarudeShadow[] = INCBIN_U32("graphics/pokemon/zarude/shadow/front.4bpp.lz");
const u32 gMonBackPic_ZarudeShadow[] = INCBIN_U32("graphics/pokemon/zarude/shadow/back.4bpp.lz");
const u16 gMonPalette_ZarudeShadow[] = INCBIN_U16("graphics/pokemon/zarude/shadow/zarude_shadow.pal");
const u8 gMonIcon_ZarudeShadow[] = INCBIN_U8("graphics/pokemon/zarude/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_ZarudeShadow[] = INCBIN_COMP("graphics/pokemon/zarude/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_ZekromShadow[] = INCBIN_U32("graphics/pokemon/zekrom/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_ZekromShadow[] = INCBIN_U32("graphics/pokemon/zekrom/shadow/back.4bpp.lz");
const u16 gMonPalette_ZekromShadow[] = INCBIN_U16("graphics/pokemon/zekrom/shadow/zekrom_shadow.pal");
const u8 gMonIcon_ZekromShadow[] = INCBIN_U8("graphics/pokemon/zekrom/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_ZekromShadow[] = INCBIN_COMP("graphics/pokemon/zekrom/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_ZeraoraShadow[] = INCBIN_U32("graphics/pokemon/zeraora/shadow/front.4bpp.lz");
const u32 gMonBackPic_ZeraoraShadow[] = INCBIN_U32("graphics/pokemon/zeraora/shadow/back.4bpp.lz");
const u16 gMonPalette_ZeraoraShadow[] = INCBIN_U16("graphics/pokemon/zeraora/shadow/zeraora_shadow.pal");
const u8 gMonIcon_ZeraoraShadow[] = INCBIN_U8("graphics/pokemon/zeraora/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_ZeraoraShadow[] = INCBIN_COMP("graphics/pokemon/zeraora/shadow/overworld.4bpp");
#endif

const u32 gMonFrontPic_ZygardeShadow[] = INCBIN_U32("graphics/pokemon/zygarde/shadow/anim_front.4bpp.lz");
const u32 gMonBackPic_ZygardeShadow[] = INCBIN_U32("graphics/pokemon/zygarde/shadow/back.4bpp.lz");
const u16 gMonPalette_ZygardeShadow[] = INCBIN_U16("graphics/pokemon/zygarde/shadow/zygarde_shadow.pal");
const u8 gMonIcon_ZygardeShadow[] = INCBIN_U8("graphics/pokemon/zygarde/shadow/icon.4bpp");
#if OW_POKEMON_OBJECT_EVENTS
const u32 gObjectEventPic_ZygardeShadow[] = INCBIN_COMP("graphics/pokemon/zygarde/shadow/overworld.4bpp");
#endif

