#ifndef GUARD_CONSTANTS_HEADBUTT_H
#define GUARD_CONSTANTS_HEADBUTT_H

#define HEADBUTT_TREE_TRACKED_MAX 64
#define HEADBUTT_TREE_ID_NONE 0xFFFF
#define HEADBUTT_WILD_COUNT 8

enum HeadbuttResult
{
    HEADBUTT_RESULT_NO_MON,
    HEADBUTT_RESULT_TOO_SOON,
    HEADBUTT_RESULT_NO_TREE,
    HEADBUTT_RESULT_NOTHING,
    HEADBUTT_RESULT_APRICORN_1,
    HEADBUTT_RESULT_APRICORN_2,
    HEADBUTT_RESULT_APRICORN_10,
    HEADBUTT_RESULT_BATTLE,
};

#endif // GUARD_CONSTANTS_HEADBUTT_H
