#ifndef GUARD_CONSTANTS_HEAL_LOCATIONS_H
#define GUARD_CONSTANTS_HEAL_LOCATIONS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from src/data/heal_locations.json and Inja template src/data/heal_locations.constants.json.txt
//


enum {
    HEAL_LOCATION_NONE,
    HEAL_LOCATION_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F,
    HEAL_LOCATION_LITTLEROOT_TOWN_MAYS_HOUSE_2F,
    HEAL_LOCATION_PETALBURG_CITY,
    HEAL_LOCATION_SLATEPORT_CITY,
    HEAL_LOCATION_MAUVILLE_CITY,
    HEAL_LOCATION_RUSTBORO_CITY,
    HEAL_LOCATION_FORTREE_CITY,
    HEAL_LOCATION_LILYCOVE_CITY,
    HEAL_LOCATION_MOSSDEEP_CITY,
    HEAL_LOCATION_SOOTOPOLIS_CITY,
    HEAL_LOCATION_EVER_GRANDE_CITY,
    HEAL_LOCATION_LITTLEROOT_TOWN_BRENDANS_HOUSE,
    HEAL_LOCATION_LITTLEROOT_TOWN_MAYS_HOUSE,
    HEAL_LOCATION_OLDALE_TOWN,
    HEAL_LOCATION_DEWFORD_TOWN,
    HEAL_LOCATION_LAVARIDGE_TOWN,
    HEAL_LOCATION_FALLARBOR_TOWN,
    HEAL_LOCATION_VERDANTURF_TOWN,
    HEAL_LOCATION_PACIFIDLOG_TOWN,
    HEAL_LOCATION_EVER_GRANDE_CITY_POKEMON_LEAGUE,
    HEAL_LOCATION_SOUTHERN_ISLAND_EXTERIOR,
    HEAL_LOCATION_BATTLE_FRONTIER_OUTSIDE_EAST,
    HEAL_LOCATION_PEWTER_CITY,
    HEAL_LOCATION_CERULEAN_CITY,
    HEAL_LOCATION_PALLET_TOWN,
    HEAL_LOCATION_CELADON_CITY,
    HEAL_LOCATION_CHERRYGROVE_CITY,
    HEAL_LOCATION_CINNABAR_ISLAND,
    HEAL_LOCATION_ECRUTEAK_CITY,
    HEAL_LOCATION_FUCHSIA_CITY,
    HEAL_LOCATION_GOLDENROD_CITY,
    HEAL_LOCATION_LAVENDER_TOWN,
    HEAL_LOCATION_MAHOGANY_TOWN,
    HEAL_LOCATION_OLIVINE_CITY,
    HEAL_LOCATION_SAFFRON_CITY,
    HEAL_LOCATION_VERMILION_CITY,
    HEAL_LOCATION_VIOLET_CITY,
    HEAL_LOCATION_VIRIDIAN_CITY,
    HEAL_LOCATION_ROUTE4,
    HEAL_LOCATION_ROUTE10,
    HEAL_LOCATION_NEW_BARK_TOWN,
    HEAL_LOCATION_SAFARI_ZONE_GATE_JOHTO,
    HEAL_LOCATION_AZALEA_TOWN,
    HEAL_LOCATION_BLACKTHORN_CITY,
    HEAL_LOCATION_ROUTE32,
    NUM_HEAL_LOCATIONS
};

#endif // GUARD_CONSTANTS_HEAL_LOCATIONS_H
