#ifndef GUARD_CONSTANTS_OPPONENTS_H
#define GUARD_CONSTANTS_OPPONENTS_H

#include "constants/battle_partner.h"

// Start non-vanilla IDs
#define TRAINER_SHADOW_TEST              0
#define TRAINER_TORKIN                   1   // NEW
#define TRAINER_ROCKET_GRUNT_M_1         2
#define TRAINER_ROCKET_GRUNT_F_1         3
#define TRAINER_JJ_VIRIDIAN              4
#define TRAINER_GIOVANNI_1               5
#define TRAINER_BROCK_KANTO              6
#define TRAINER_CAMPER_KANTO             7
#define TRAINER_ARCHER                   8
#define TRAINER_ARIANA                   9
#define TRAINER_BIKER                    10
#define TRAINER_BLAINE                   11
#define TRAINER_BURGLAR                  12
#define TRAINER_CHAMPION_LANCE           13
#define TRAINER_ELITE_FOUR_BRUNO         14
#define TRAINER_ELITE_FOUR_KAREN         15
#define TRAINER_ELITE_FOUR_KOGA          16
#define TRAINER_ELITE_FOUR_WILL          17
#define TRAINER_ENGINEER                 18
#define TRAINER_ERIKA                    19
#define TRAINER_EUSINE                   20
#define TRAINER_FIREBREATHER             21
#define TRAINER_GOLD                     22
#define TRAINER_JANINE                   23
#define TRAINER_JUGGLER                  24
#define TRAINER_KIMONO_GIRL              25
#define TRAINER_LEADER_BLUE              26
#define TRAINER_LEADER_BUGSY             27
#define TRAINER_LEADER_CHUCK             28
#define TRAINER_LEADER_CLAIR             29
#define TRAINER_LEADER_FALKNER           30
#define TRAINER_LEADER_JASMINE           31
#define TRAINER_LEADER_MORTY             32
#define TRAINER_LEADER_PRYCE             33
#define TRAINER_LEADER_WHITNEY           34
#define TRAINER_LYRA                     35
#define TRAINER_MISTY                    36
#define TRAINER_NURSE                    37
#define TRAINER_OFFICER                  38
#define TRAINER_PETREL                   39
#define TRAINER_PROTON                   40
#define TRAINER_PSYCHIC_M2               41
#define TRAINER_SABRINA                  42
#define TRAINER_SAGE                     43
#define TRAINER_SAGE_LEADER              44
#define TRAINER_SILVER                   45
#define TRAINER_SUPER_NERD               46
#define TRAINER_SURGE                    47
#define TRAINER_TWINS2                   48
#define TRAINER_YOUNGSTER2               49
#define TRAINER_VF_BUGCATCHER1           50
#define TRAINER_VF_BUGCATCHER2           51
#define TRAINER_VF_BUGCATCHER3           52
#define TRAINER_VF_ROCKET                53
#define TRAINER_VF_PLASMA                54
#define TRAINER_RT3_YOUNGSTER1           55
#define TRAINER_RT3_YOUNGSTER2           56
#define TRAINER_RT3_LASS                 57
#define TRAINER_RT3_FIREBREATHER         58
#define TRAINER_TEMP_MIROR_B             59
#define TRAINER_RT4_BLACK_BELT           60
#define TRAINER_RT4_ROCKER               61
#define TRAINER_RT4_PICNICKER1           62
#define TRAINER_RT4_PICNICKER2           63
#define TRAINER_RT4_BRENDAN1             64
#define TRAINER_RT4_BRENDAN2             65
#define TRAINER_RT4_BRENDAN3             66
#define TRAINER_LOOKER_CERULEAN          67
#define TRAINER_RT25_YOUNGSTER1          68
#define TRAINER_RT25_LADY                69
#define TRAINER_RT25_COOLTRAINER_F       70
#define TRAINER_RT25_YOUNGSTER2          71
#define TRAINER_RT25_CAMPER              72
#define TRAINER_RT25_LASS                73
#define TRAINER_RT25_SUPER_NERD          74
#define TRAINER_RT25_COOLTRAINER_M       75
#define TRAINER_CERULEAN_GYM_SWIMMER_M   76
#define TRAINER_CERULEAN_GYM_SWIMMER_F1  77
#define TRAINER_CERULEAN_GYM_SWIMMER_F2  78
#define TRAINER_EIN                      79
#define TRAINER_AZALEA_AL                80
#define TRAINER_AZALEA_JOSH              81
#define TRAINER_AZALEA_BENNY             82
#define TRAINER_AZALEA_AMY_AND_MAY       83
#define TRAINER_BUGSY_1                  84
#define TRAINER_EVICE                    85
#define TRAINER_GONZAP                   86
#define TRAINER_LOVRINA                  87
#define TRAINER_GREEVIL                  88
#define TRAINER_ARDOS                    89
#define TRAINER_ELDES                    90
#define TRAINER_VENUS                    91
#define TRAINER_DAKIM                    92
#define TRAINER_NASCOUR                  93
#define TRAINER_CASSIDY_HUNTER           94
#define TRAINER_BUTCH_HUNTER             95
#define TRAINER_SILVER_HUNTER            96
#define TRAINER_HEX_RESIX                97
#define TRAINER_HEX_BLUSIX               98
#define TRAINER_HEX_GREESIX              99
#define TRAINER_HEX_PURPSIX              100
#define TRAINER_HEX_BROWSIX              101
#define TRAINER_HEX_YELLOSIX             102
#define TRAINER_VF_GALACTIC              103
#define TRAINER_VF_SKULL                 104
#define TRAINER_VF_FLARE                 105
#define TRAINER_ROCK_TUNNEL_1F_PLASMA_1  106
#define TRAINER_ROCK_TUNNEL_1F_PLASMA_2  107
#define TRAINER_ROCK_TUNNEL_1F_PLASMA_3  108
#define TRAINER_ROCK_TUNNEL_1F_PLASMA_4  109
#define TRAINER_ROCK_TUNNEL_1F_PLASMA_5  110
#define TRAINER_ROCK_TUNNEL_1F_PLASMA_6  111
#define TRAINER_ROCK_TUNNEL_B1F_PLASMA_1 112
#define TRAINER_ROCK_TUNNEL_B1F_PLASMA_2 113
#define TRAINER_ROCK_TUNNEL_B1F_PLASMA_3 114
#define TRAINER_ROCK_TUNNEL_B1F_PLASMA_4 115
#define TRAINER_ROCK_TUNNEL_B1F_PLASMA_5 116
#define TRAINER_ROCK_TUNNEL_B1F_PLASMA_6 117
#define TRAINER_ROCK_TUNNEL_B1F_PLASMA_7 118
#define TRAINER_ROCK_TUNNEL_B1F_PLASMA_8 119
#define TRAINER_SLOWPOKEWELL_FLARE_1     120
#define TRAINER_SLOWPOKEWELL_FLARE_2     121
#define TRAINER_SLOWPOKEWELL_FLARE_3     122
#define TRAINER_SLOWPOKEWELL_BRYONY      123
#define TRAINER_KURTS_HOUSE_IRONMASK     124
#define TRAINER_VIOLET_GYM_BIRD_KEEPER_1 125
#define TRAINER_VIOLET_GYM_BIRD_KEEPER_2 126
#define TRAINER_ROUTE32_YOUNGSTER        127
#define TRAINER_ROUTE32_PICNICKER        128
#define TRAINER_ROUTE32_FISHERMAN_1      129
#define TRAINER_ROUTE32_FISHERMAN_2      130
#define TRAINER_ROUTE32_FISHERMAN_3      131
#define TRAINER_ROUTE32_BIRD_KEEPER      132
#define TRAINER_ROUTE33_HIKER            133
#define TRAINER_UNION_CAVE_HIKER         134
#define TRAINER_UNION_CAVE_SUPER_NERD    135
#define TRAINER_UNION_CAVE_FIREBREATHER  136
#define TRAINER_ROUTE9_CAMPER_1          137
#define TRAINER_ROUTE9_CAMPER_2          138
#define TRAINER_ROUTE9_PICNICKER_1       139
#define TRAINER_ROUTE9_PICNICKER_2       140
#define TRAINER_ROUTE9_HIKER_1           141
#define TRAINER_ROUTE9_HIKER_2           142
#define TRAINER_JJ_ILEX                  143
#define TRAINER_ROUTE34_CAMPER           144
#define TRAINER_ROUTE34_GENTLEMAN        145
#define TRAINER_ROUTE34_YOUNGSTER        146
#define TRAINER_ILEX_ROCKET_GRUNT_F1     147
#define TRAINER_ILEX_ROCKET_GRUNT_M1     148
#define TRAINER_ILEX_ROCKET_GRUNT_F2     149
#define TRAINER_ILEX_ROCKET_GRUNT_M2     150
#define TRAINER_ILEX_ROCKET_GRUNT_M3     151
#define TRAINER_ILEX_ROCKET_GRUNT_F3     152
#define TRAINER_ILEX_BUG_CATCHER         153
#define TRAINER_POWERPLANT_PLASMA_1     154
#define TRAINER_POWERPLANT_PLASMA_2     155
#define TRAINER_POWERPLANT_PLASMA_3     156
#define TRAINER_ZINZOLIN_POWER_PLANT    157
#define TRAINER_CELADON_SHAUNA          158
#define TRAINER_CELADON_TREVOR          159
#define TRAINER_CELADON_TIERNO          160
#define TRAINER_CELADON_SERENA          161
#define TRAINER_CELADON_CALEM           162
#define TRAINER_CELADON_AETHER_GRUNT_1  163
#define TRAINER_CELADON_AETHER_GRUNT_2  164
#define TRAINER_CELADON_GYM_MICHELLE    165
#define TRAINER_CELADON_GYM_TANYA       166
#define TRAINER_CELADON_GYM_JULIA       167
#define TRAINER_CELADON_GYM_JO_AND_ZOE  168
#define TRAINER_CELADON_GLADION         169
#define TRAINER_VERMILION_GYM_JUGGLER   170
#define TRAINER_VERMILION_GYM_GENTLEMAN 171
#define TRAINER_VERMILION_GYM_ROCKER    172
#define TRAINER_GOLDENROD_GYM_CARRIE    173
#define TRAINER_GOLDENROD_GYM_LEAH      174
#define TRAINER_GOLDENROD_GYM_BROOKE    175
#define TRAINER_GOLDENROD_GYM_MARA      176
#define TRAINER_GIOVANNI_SHADOW_REALM   177
#define TRAINER_NASCOUR_SHADOW_REALM    178
#define TRAINER_GUZMA_SHADOW_REALM      179
#define TRAINER_LUSAMINE_SHADOW_REALM   180
#define TRAINER_COLRESS_SHADOW_REALM    181
#define TRAINER_GHETSIS_SHADOW_REALM    182
#define TRAINER_MAXIE_SHADOW_REALM      183
#define TRAINER_ARCHIE_SHADOW_REALM     184
#define TRAINER_LYSANDRE_SHADOW_REALM   185
#define TRAINER_ROSE_SHADOW_REALM       186
#define TRAINER_SADA_TURO_SHADOW_REALM  187
#define TRAINER_GREEVIL_SHADOW_REALM    188
#define TRAINER_EVICE_SHADOW_REALM      189
#define TRAINER_CYRUS_SHADOW_REALM      190
#define TRAINER_CELADON_ODD_KEYSTONE    191
#define TRAINER_GOLDENROD_ODD_KEYSTONE  192
#define TRAINER_GOLDENROD_RADIO_CIPHER_F1 193
#define TRAINER_GOLDENROD_RADIO_CIPHER_F2 194
#define TRAINER_GOLDENROD_RADIO_CIPHER_F3 195
#define TRAINER_GOLDENROD_RADIO_CIPHER_F4 196
#define TRAINER_GOLDENROD_RADIO_CIPHER_F5 197
#define TRAINER_GOLDENROD_RADIO_CIPHER_F6 198
#define TRAINER_GOLDENROD_RADIO_CIPHER_F7 199
#define TRAINER_UNION_CAVE_FIREBREATHER_WALT 200
#define TRAINER_ROUTE32_YOUNGSTER_2     201
#define TRAINER_ROUTE32_COOLTRAINER     202
#define TRAINER_GOLDENROD_RADIO_CIPHER_M1 203



// NOTE: Because each Trainer uses a flag to determine when they are defeated, there is only space for 9 additional trainers before trainer flag space overflows
//       More space can be made by shifting flags around in constants/flags.h or changing how trainer flags are handled
//       MAX_TRAINERS_COUNT can be increased but will take up additional saveblock space
#define TRAINERS_COUNT                      204
#define MAX_TRAINERS_COUNT                  1000
#define TRAINER_PARTNER(partner)           (MAX_TRAINERS_COUNT + partner)

#endif  // GUARD_CONSTANTS_OPPONENTS_H
