#ifndef GUARD_CONSTANTS_POKEMON_ICON_H
#define GUARD_CONSTANTS_POKEMON_ICON_H

#define POKE_ICON_BASE_PAL_TAG 56000
#define POKE_ICON_SHADOW_PAL_TAG (POKE_ICON_BASE_PAL_TAG + 6)
#define POKE_ICON_SHINY_PAL_TAG (POKE_ICON_SHADOW_PAL_TAG + 6)
#define POKE_ICON_GIFT_AURA_PAL_TAG (POKE_ICON_SHINY_PAL_TAG + 6)
#define POKE_ICON_SHADOW_MEOWTH_PAL_TAG 56150
#define POKE_ICON_SHADOW_MIMIKYU_PAL_TAG 56151
#define POKE_ICON_SHADOW_PANGORO_PAL_TAG 56152
#define POKE_ICON_SHADOW_UNIQUE_PAL_TAG_START 56400
#define POKE_ICON_SHADOW_UNIQUE_PAL_TAG_COUNT 64

#endif  // GUARD_CONSTANTS_POKEMON_ICON_H
