Olivine_City_MapScripts::
	.byte 0

OlivineCity_EventScript_GymSign::
	msgbox OlivineCity_EventScript_GymSign_Text, MSGBOX_SIGN
	end

OlivineCity_EventScript_GymSign_Text:
	.string "A POKéMON GYM statue.$"

OlivineCity_EventScript_LighthouseSign::
	msgbox OlivineCity_EventScript_LighthouseSign_Text, MSGBOX_SIGN
	end

OlivineCity_EventScript_LighthouseSign_Text:
	.string "OLIVINE LIGHTHOUSE.$"

OlivineCity_EventScript_PortSign::
	msgbox OlivineCity_EventScript_PortSign_Text, MSGBOX_SIGN
	end

OlivineCity_EventScript_PortSign_Text:
	.string "OLIVINE PORT.$"

OlivineCity_EventScript_Sign::
	msgbox OlivineCity_EventScript_Sign_Text, MSGBOX_SIGN
	end

OlivineCity_EventScript_Sign_Text:
	.string "It's a sign.$"

OlivineCity_EventScript_CafeSign::
	msgbox OlivineCity_EventScript_CafeSign_Text, MSGBOX_SIGN
	end

OlivineCity_EventScript_CafeSign_Text:
	.string "OLIVINE CAFE.$"
