GoldenrodCity_RadioTower_3F_MapScripts::
	.byte 0

GoldenrodCity_RadioTower_3F_EventScript_Sign1::
	msgbox GoldenrodCity_RadioTower_3F_EventScript_Sign1_Text, MSGBOX_SIGN
	end

GoldenrodCity_RadioTower_3F_EventScript_Sign1_Text:
	.string "It's a sign.$"

GoldenrodCity_RadioTower_3F_EventScript_Sign2::
	msgbox GoldenrodCity_RadioTower_3F_EventScript_Sign2_Text, MSGBOX_SIGN
	end

GoldenrodCity_RadioTower_3F_EventScript_Sign2_Text:
	.string "It's a sign.$"

GoldenrodCity_RadioTower_3F_EventScript_Gate::
	msgbox GoldenrodCity_RadioTower_3F_EventScript_Gate_Text, MSGBOX_SIGN
	end

GoldenrodCity_RadioTower_3F_EventScript_Gate_Text:
	.string "It's locked.$"
