GoldenrodCity_UndergroundSwitches_MapScripts::
	.byte 0

GoldenrodCity_UndergroundSwitches_EventScript_Panel1::
	msgbox GoldenrodCity_UndergroundSwitches_EventScript_Panel1_Text, MSGBOX_SIGN
	end

GoldenrodCity_UndergroundSwitches_EventScript_Panel1_Text:
	.string "A control panel.$"

GoldenrodCity_UndergroundSwitches_EventScript_Panel2::
	msgbox GoldenrodCity_UndergroundSwitches_EventScript_Panel2_Text, MSGBOX_SIGN
	end

GoldenrodCity_UndergroundSwitches_EventScript_Panel2_Text:
	.string "A control panel.$"

GoldenrodCity_UndergroundSwitches_EventScript_Panel3::
	msgbox GoldenrodCity_UndergroundSwitches_EventScript_Panel3_Text, MSGBOX_SIGN
	end

GoldenrodCity_UndergroundSwitches_EventScript_Panel3_Text:
	.string "A control panel.$"
