Blackthorn_City_MapScripts::
	.byte 0

BlackthornCity_EventScript_DragonsDenSign::
	msgbox BlackthornCity_EventScript_DragonsDenSign_Text, MSGBOX_SIGN
	end

BlackthornCity_EventScript_DragonsDenSign_Text:
	.string "It's a sign.$"

BlackthornCity_EventScript_GymSign::
	msgbox BlackthornCity_EventScript_GymSign_Text, MSGBOX_SIGN
	end

BlackthornCity_EventScript_GymSign_Text:
	.string "A POKéMON GYM statue.$"

BlackthornCity_EventScript_MoveHouseSign::
	msgbox BlackthornCity_EventScript_MoveHouseSign_Text, MSGBOX_SIGN
	end

BlackthornCity_EventScript_MoveHouseSign_Text:
	.string "It's a sign.$"

BlackthornCity_EventScript_CitySign::
	msgbox BlackthornCity_EventScript_CitySign_Text, MSGBOX_SIGN
	end

BlackthornCity_EventScript_CitySign_Text:
	.string "Welcome to town.$"
