Ecruteak_City_MapScripts::
	.byte 0

EcruteakCity_EventScript_GymSign::
	msgbox EcruteakCity_EventScript_GymSign_Text, MSGBOX_SIGN
	end

EcruteakCity_EventScript_GymSign_Text:
	.string "A POKéMON GYM statue.$"

EcruteakCity_EventScript_TheaterSign::
	msgbox EcruteakCity_EventScript_TheaterSign_Text, MSGBOX_SIGN
	end

EcruteakCity_EventScript_TheaterSign_Text:
	.string "It's a sign.$"

EcruteakCity_EventScript_OfficeSign::
	msgbox EcruteakCity_EventScript_OfficeSign_Text, MSGBOX_SIGN
	end

EcruteakCity_EventScript_OfficeSign_Text:
	.string "It's a sign.$"

EcruteakCity_EventScript_BurnedSign::
	msgbox EcruteakCity_EventScript_BurnedSign_Text, MSGBOX_SIGN
	end

EcruteakCity_EventScript_BurnedSign_Text:
	.string "It's a sign.$"

EcruteakCity_EventScript_CitySign::
	msgbox EcruteakCity_EventScript_CitySign_Text, MSGBOX_SIGN
	end

EcruteakCity_EventScript_CitySign_Text:
	.string "Welcome to town.$"
