Kanto_Furniture_EventScript_Bookshelf_Pallet::
	msgbox Kanto_Furniture_Text_Bookshelf_Pallet, MSGBOX_SIGN
	end

Kanto_Furniture_EventScript_Bookshelf_Viridian::
	msgbox Kanto_Furniture_Text_Bookshelf_Viridian, MSGBOX_SIGN
	end

Kanto_Furniture_EventScript_Bookshelf_Pewter::
	msgbox Kanto_Furniture_Text_Bookshelf_Pewter, MSGBOX_SIGN
	end

Kanto_Furniture_EventScript_Bookshelf_Cerulean::
	msgbox Kanto_Furniture_Text_Bookshelf_Cerulean, MSGBOX_SIGN
	end

Kanto_Furniture_EventScript_Bookshelf_Lavender::
	msgbox Kanto_Furniture_Text_Bookshelf_Lavender, MSGBOX_SIGN
	end

Kanto_Furniture_EventScript_TV_Pallet::
	msgbox Kanto_Furniture_Text_TV_Pallet, MSGBOX_SIGN
	end

Kanto_Furniture_EventScript_TV_Viridian::
	msgbox Kanto_Furniture_Text_TV_Viridian, MSGBOX_SIGN
	end

Kanto_Furniture_EventScript_TV_Pewter::
	msgbox Kanto_Furniture_Text_TV_Pewter, MSGBOX_SIGN
	end

Kanto_Furniture_EventScript_TV_Cerulean::
	msgbox Kanto_Furniture_Text_TV_Cerulean, MSGBOX_SIGN
	end

Kanto_Furniture_EventScript_TV_Lavender::
	msgbox Kanto_Furniture_Text_TV_Lavender, MSGBOX_SIGN
	end
