Cianwood_City_MapScripts::
	.byte 0

CianwoodCity_EventScript_CitySign::
	msgbox CianwoodCity_EventScript_CitySign_Text, MSGBOX_SIGN
	end

CianwoodCity_EventScript_CitySign_Text:
	.string "Welcome to town.$"

CianwoodCity_EventScript_Pharmacy::
	msgbox CianwoodCity_EventScript_Pharmacy_Text, MSGBOX_SIGN
	end

CianwoodCity_EventScript_Pharmacy_Text:
	.string "Cianwood Pharmacy.$"

CianwoodCity_EventScript_GymSign::
	msgbox CianwoodCity_EventScript_GymSign_Text, MSGBOX_SIGN
	end

CianwoodCity_EventScript_GymSign_Text:
	.string "A POKéMON GYM statue.$"

CianwoodCity_EventScript_CaveSign::
	msgbox CianwoodCity_EventScript_CaveSign_Text, MSGBOX_SIGN
	end

CianwoodCity_EventScript_CaveSign_Text:
	.string "To the cave.$"
