#include "global.h"

// BW summary screen graphics
const u16 gFireRedMenuElements2_Pal[] = INCBIN_U16("graphics/summary_screen_bw/dex_caught_pokeball_and_pokemon_types.gbapal");
const u8 gFireRedMenuElements_Gfx[] = INCBIN_U8("graphics/summary_screen_bw/dex_caught_pokeball_and_pokemon_types.4bpp");
const u32 gIconStatusSummaryScreen[] = INCBIN_U32("graphics/summary_screen_bw/icon_status.4bpp.lz");
const u32 gIconStatusSummaryScreenSpa[] = INCBIN_U32("graphics/summary_screen_bw/icon_status_spa.4bpp.lz");
const u16 gIconStatusPalSummaryScreen[] = INCBIN_U16("graphics/summary_screen_bw/icon_status.gbapal");
const u32 gExpBarSummaryScreen[] = INCBIN_U32("graphics/summary_screen_bw/exp_bar.4bpp.lz");
const u32 gHeartBarSummaryScreen[] = INCBIN_U32("graphics/summary_screen_bw/heart_bar.4bpp.lz");
const u32 gHpBarSummaryScreen[] = INCBIN_U32("graphics/summary_screen_bw/hp_bar.4bpp.lz");
const u32 gHpBarSummaryScreenSpa[] = INCBIN_U32("graphics/summary_screen_bw/hp_bar_spa.4bpp.lz");
const u16 gPal0SummaryScreen[] = INCBIN_U16("graphics/summary_screen_bw/hp_bar_0.gbapal");
const u16 gPal1SummaryScreen[] = INCBIN_U16("graphics/summary_screen_bw/hp_bar_1.gbapal");
const u16 gPal2SummaryScreen[] = INCBIN_U16("graphics/summary_screen_bw/hp_bar_2.gbapal");
const u16 gSelectCursorPalette[] = INCBIN_U16("graphics/summary_screen_bw/select_pointer_gfx_left.gbapal");
const u32 gSelectCursorGfxLeft[] = INCBIN_U32("graphics/summary_screen_bw/select_pointer_gfx_left.4bpp.lz");
const u32 gSelectCursorGfxRight[] = INCBIN_U32("graphics/summary_screen_bw/select_pointer_gfx_right.4bpp.lz");
const u16 gShinyIndicatorPalette[] = INCBIN_U16("graphics/summary_screen_bw/shiny_indicator_gfx.gbapal");
const u32 gShinyIndicatorGfx[] = INCBIN_U32("graphics/summary_screen_bw/shiny_indicator_gfx.4bpp.lz");
const u16 gPalSummaryScreen[] = INCBIN_U16("graphics/summary_screen_bw/palette_bg.gbapal");
const u32 gTilesSummaryScreen[] = INCBIN_U32("graphics/summary_screen_bw/tiles.4bpp.lz");
const u32 gMapSummaryScreenBg[] = INCBIN_U32("graphics/summary_screen_bw/bg.bin.lz");
const u32 gMapSummaryScreenEgg[] = INCBIN_U32("graphics/summary_screen_bw/bg_egg.bin.lz");
const u32 gMapSummaryScreenKnownMoves[] = INCBIN_U32("graphics/summary_screen_bw/bg_known_moves.bin.lz");
const u32 gMapSummaryScreenMovesInfo[] = INCBIN_U32("graphics/summary_screen_bw/bg_moves_info.bin.lz");
const u32 gMapSummaryScreenMoves[] = INCBIN_U32("graphics/summary_screen_bw/bg_moves.bin.lz");
const u32 gMapSummaryScreenMoves2[] = INCBIN_U32("graphics/summary_screen_bw/bg_moves2.bin.lz");
const u32 gMapSummaryScreenPokemonInfo[] = INCBIN_U32("graphics/summary_screen_bw/bg_pokemon_info.bin.lz");
const u32 gMapSummaryScreenPokemonSkills[] = INCBIN_U32("graphics/summary_screen_bw/bg_pokemon_skills.bin.lz");
